from __future__ import annotations

import re
import subprocess
import sys
import unittest
from pathlib import Path

from scripts.common import load_yaml


ROOT = Path(__file__).resolve().parents[2]
GENERATED_HEADER = "# Generated by scripts/sync_skill_resources.py. Do not edit manually.\n\n"
SCRIPT_REFERENCE = re.compile(r"scripts/([A-Za-z0-9_.-]+\.py)")


class SkillResourcePackagingTests(unittest.TestCase):
    def test_generated_skill_resources_are_in_sync(self) -> None:
        result = subprocess.run(
            [sys.executable, "-B", "scripts/sync_skill_resources.py", ".", "--check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)

    def test_standalone_router_does_not_require_repository_only_indexes(self) -> None:
        router = (ROOT / "skills" / "using-game-studio-skills" / "SKILL.md").read_text(
            encoding="utf-8"
        )
        workflow = re.search(r"^## Workflow\s*$\n(.*?)(?=^## |\Z)", router, re.MULTILINE | re.DOTALL)
        self.assertIsNotNone(workflow)
        self.assertNotIn("registry/", workflow.group(1))
        self.assertNotIn("docs/", workflow.group(1))

    def test_standalone_skill_bodies_make_repository_indexes_optional(self) -> None:
        for skill_path in sorted((ROOT / "skills").glob("*/SKILL.md")):
            body = skill_path.read_text(encoding="utf-8").split("---", 2)[-1]
            if "registry/" not in body:
                continue
            self.assertTrue(
                "when present" in body or "full repository clone" in body,
                skill_path,
            )

    def test_readme_marks_root_script_workflows_as_full_clone_maintenance(self) -> None:
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        section = re.search(
            r"^## Use in a game project\s*$\n(.*?)(?=^## |\Z)",
            readme,
            re.MULTILINE | re.DOTALL,
        )
        self.assertIsNotNone(section)
        self.assertIn("full repository clone", section.group(1))

    def test_referenced_helpers_are_bundled_or_declared_repository_only(self) -> None:
        registry_path = ROOT / "registry" / "skill-resources.yaml"
        self.assertTrue(registry_path.is_file(), registry_path)
        registry = load_yaml(registry_path)
        self.assertEqual({"schema_version", "bundled", "repository_only"}, set(registry))

        bundled = registry["bundled"]
        repository_only = registry["repository_only"]
        self.assertIsInstance(bundled, dict)
        self.assertIsInstance(repository_only, dict)

        for skill_path in sorted((ROOT / "skills").glob("*/SKILL.md")):
            skill_id = skill_path.parent.name
            body = skill_path.read_text(encoding="utf-8")
            referenced = set(SCRIPT_REFERENCE.findall(body))
            declared_bundled = set(bundled.get(skill_id, []))
            declared_repository_only = set(repository_only.get(skill_id, []))

            self.assertEqual(
                referenced,
                declared_bundled | declared_repository_only,
                f"resource registry mismatch for {skill_id}",
            )
            if declared_repository_only:
                self.assertIn("full repository clone", body)

            for script_name in declared_bundled:
                source = ROOT / "scripts" / script_name
                generated = skill_path.parent / "scripts" / script_name
                self.assertTrue(source.is_file(), source)
                self.assertTrue(generated.is_file(), generated)
                self.assertEqual(
                    GENERATED_HEADER + source.read_text(encoding="utf-8"),
                    generated.read_text(encoding="utf-8"),
                    generated,
                )

    def test_resource_registry_only_names_known_skills_and_scripts(self) -> None:
        registry = load_yaml(ROOT / "registry" / "skill-resources.yaml")
        known_skills = {path.parent.name for path in (ROOT / "skills").glob("*/SKILL.md")}

        for section in ("bundled", "repository_only"):
            mapping = registry[section]
            self.assertTrue(set(mapping).issubset(known_skills))
            for skill_id, script_names in mapping.items():
                self.assertIsInstance(script_names, list, skill_id)
                self.assertEqual(len(script_names), len(set(script_names)), skill_id)
                for script_name in script_names:
                    self.assertRegex(script_name, r"^[a-z0-9_]+\.py$")
                    self.assertTrue((ROOT / "scripts" / script_name).is_file(), script_name)


if __name__ == "__main__":
    unittest.main()
