from __future__ import annotations

import hashlib
import json
import unittest
from pathlib import Path
from unittest import mock

from tests._meta.support import temporary_directory


def tree_digest(root: Path) -> str:
    hasher = hashlib.sha256()
    for path in sorted(item for item in root.rglob("*") if item.is_file()):
        hasher.update(path.relative_to(root).as_posix().encode("utf-8"))
        hasher.update(path.read_bytes())
    return hasher.hexdigest()


class PackagingTests(unittest.TestCase):
    def test_pack_build_is_deterministic_and_generated(self) -> None:
        from scripts.build_packs import build_all_packs

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            output = Path(temp) / "packs"
            first = build_all_packs(source_root, output)
            first_digest = tree_digest(output)
            second = build_all_packs(source_root, output)
            second_digest = tree_digest(output)
            self.assertEqual(first_digest, second_digest)
            self.assertEqual(first, second)
            self.assertEqual(
                {"studio-core", "unity", "cpp-lua-mmorpg", "production-design-liveops"},
                set(first),
            )
            manifest = json.loads((output / "studio-core" / "manifest.json").read_text(encoding="utf-8"))
            self.assertIn("Do not edit manually", manifest["_generated"])
            generated_skill = output / "studio-core" / "skills" / "studio-project-intake" / "SKILL.md"
            generated_text = generated_skill.read_text(encoding="utf-8")
            self.assertIn("# Generated by scripts/build_packs.py", "\n".join(generated_text.splitlines()[:3]))
            generated_helper = (
                output
                / "studio-core"
                / "skills"
                / "studio-project-scaffold"
                / "scripts"
                / "project_scaffold.py"
            )
            self.assertTrue(generated_helper.is_file())
            self.assertTrue(
                generated_helper.read_text(encoding="utf-8").startswith(
                    "# Generated by scripts/build_packs.py. Do not edit manually."
                )
            )

    def test_adapters_are_deterministic_and_project_merge_preserves_local_skills(self) -> None:
        from scripts.generate_adapters import generate_adapter

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            temp_root = Path(temp)
            source_files = [path for path in (source_root / "skills").rglob("*") if path.is_file()]
            for target in ("hermes", "codex"):
                output = temp_root / target
                report = generate_adapter(source_root, target, output)
                self.assertEqual(len(source_files) + 1, len(report["created"]))
                first = tree_digest(output)
                generate_adapter(source_root, target, output)
                self.assertEqual(first, tree_digest(output))
                self.assertTrue((output / "registry.json").exists())
                registry = json.loads((output / "registry.json").read_text(encoding="utf-8"))
                self.assertEqual(33, len(registry["skills"]))
                helper = output / "skills" / "studio-project-scaffold" / "scripts" / "project_scaffold.py"
                self.assertTrue(helper.is_file())
                self.assertTrue(
                    helper.read_text(encoding="utf-8").startswith(
                        "# Generated by scripts/generate_adapters.py. Do not edit manually."
                    )
                )
            project = temp_root / "project"
            local_skill = project / ".agents" / "skills" / "project-memory" / "SKILL.md"
            local_skill.parent.mkdir(parents=True)
            local_skill.write_text("local-owned\n", encoding="utf-8")
            generate_adapter(source_root, "per-project", project)
            self.assertEqual("local-owned\n", local_skill.read_text(encoding="utf-8"))
            generated = project / ".agents" / "skills" / "studio-project-intake" / "SKILL.md"
            self.assertTrue(generated.exists())
            generated_text = generated.read_text(encoding="utf-8")
            self.assertIn("# Generated by scripts/generate_adapters.py", "\n".join(generated_text.splitlines()[:3]))
            registry = json.loads((project / ".agents" / "registry.json").read_text(encoding="utf-8"))
            self.assertIn("project-memory", registry["skills"])
            self.assertIn("studio-project-intake", registry["skills"])
            helper_relative = ".agents/skills/studio-project-scaffold/scripts/project_scaffold.py"
            self.assertIn(helper_relative, {item["path"] for item in registry["kit_adapter"]["files"]})

    def test_project_adapter_uninstall_tracks_nested_resources_and_preserves_drift(self) -> None:
        from scripts.generate_adapters import generate_adapter, uninstall_project_adapter

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            generate_adapter(source_root, "per-project", project)
            helper = project / ".agents" / "skills" / "studio-project-scaffold" / "scripts" / "project_scaffold.py"
            helper.write_text(helper.read_text(encoding="utf-8") + "# local note\n", encoding="utf-8")

            removed = uninstall_project_adapter(project)

            self.assertTrue(helper.is_file())
            self.assertNotIn("studio-project-scaffold", removed)
            registry = json.loads((project / ".agents" / "registry.json").read_text(encoding="utf-8"))
            remaining = {item["path"] for item in registry["kit_adapter"]["files"]}
            self.assertIn(
                ".agents/skills/studio-project-scaffold/scripts/project_scaffold.py",
                remaining,
            )

    def test_project_adapter_refuses_reparse_points_in_skill_destinations(self) -> None:
        import scripts.generate_adapters as adapters

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            reparse_target = project / ".agents" / "skills" / "studio-project-intake"
            reparse_target.mkdir(parents=True)
            original_check = adapters._is_reparse_point

            def reports_reparse(path: Path) -> bool:
                return path == reparse_target or original_check(path)

            with mock.patch.object(adapters, "_is_reparse_point", side_effect=reports_reparse):
                with self.assertRaisesRegex(ValueError, "symlink or reparse point"):
                    adapters.generate_adapter(source_root, "per-project", project)

    def test_project_adapter_uninstall_rejects_registry_path_traversal(self) -> None:
        from scripts.generate_adapters import generate_adapter, uninstall_project_adapter

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            generate_adapter(source_root, "per-project", project)
            protected = project / "important.txt"
            protected.write_text("keep me\n", encoding="utf-8")
            registry_path = project / ".agents" / "registry.json"
            registry = json.loads(registry_path.read_text(encoding="utf-8"))
            malicious = {
                "path": ".agents/skills/fake/../../../important.txt",
                "sha256": hashlib.sha256(protected.read_bytes()).hexdigest(),
            }
            registry["kit_adapter"]["files"].append(malicious)
            registry_path.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")

            uninstall_project_adapter(project)

            self.assertTrue(protected.is_file())
            remaining = json.loads(registry_path.read_text(encoding="utf-8"))["kit_adapter"]["files"]
            self.assertIn(malicious, remaining)

    def test_standard_adapters_are_generated_on_demand_and_ignored(self) -> None:
        from scripts.generate_adapters import generate_adapter

        source_root = Path(__file__).resolve().parents[2]
        ignore_entries = {
            line.strip()
            for line in (source_root / ".gitignore").read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        }
        self.assertIn("adapters/", ignore_entries)
        source_file_count = len(
            [path for path in (source_root / "skills").rglob("*") if path.is_file()]
        )
        with temporary_directory() as temp:
            for target in ("hermes", "codex"):
                adapter = Path(temp) / target
                generate_adapter(source_root, target, adapter)
                files = [path for path in adapter.rglob("*") if path.is_file()]
                self.assertEqual(source_file_count + 1, len(files), target)
                registry = json.loads((adapter / "registry.json").read_text(encoding="utf-8"))
                self.assertEqual(33, len(registry["skills"]), target)
                first_digest = tree_digest(adapter)
                generate_adapter(source_root, target, adapter)
                self.assertEqual(first_digest, tree_digest(adapter), target)


if __name__ == "__main__":
    unittest.main()
