from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path, PurePosixPath, PureWindowsPath

from scripts.common import load_yaml


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_REFERENCE = re.compile(r"scripts/([A-Za-z0-9_.-]+\.py)")
SUPPORTED_SUFFIXES = {".css", ".html", ".js", ".json", ".py", ".toml", ".yaml", ".yml"}


def normalize_resource(entry: object) -> tuple[str, str]:
    if isinstance(entry, str):
        return f"scripts/{entry}", f"scripts/{entry}"
    if isinstance(entry, dict):
        if set(entry) != {"source", "destination"}:
            raise AssertionError(f"invalid resource mapping: {entry}")
        source = entry["source"]
        destination = entry["destination"]
        if not isinstance(source, str) or not isinstance(destination, str):
            raise AssertionError(f"resource paths must be strings: {entry}")
        return source, destination
    raise AssertionError(f"invalid resource entry: {entry}")


def assert_safe_relative_path(test: unittest.TestCase, value: str) -> PurePosixPath:
    normalized = value.replace("\\", "/")
    raw_parts = normalized.split("/")
    path = PurePosixPath(normalized)
    windows_path = PureWindowsPath(value)
    test.assertTrue(value, "resource path must not be empty")
    test.assertFalse(path.is_absolute(), value)
    test.assertFalse(windows_path.is_absolute() or windows_path.drive, value)
    test.assertFalse(any(part in {"", ".", ".."} for part in raw_parts), value)
    return path


class SkillResourcePackagingTests(unittest.TestCase):
    def test_web_resources_receive_format_appropriate_generated_markers(self) -> None:
        from scripts.sync_skill_resources import render_generated_resource

        html = render_generated_resource(Path("index.html"), "<main>Goal</main>\n")
        css = render_generated_resource(Path("styles.css"), ":root { color: #111; }\n")
        javascript = render_generated_resource(Path("app.js"), "export const ready = true;\n")

        self.assertTrue(
            html.startswith("<!-- Generated by scripts/sync_skill_resources.py. Do not edit manually. -->\n")
        )
        self.assertTrue(
            css.startswith("/* Generated by scripts/sync_skill_resources.py. Do not edit manually. */\n")
        )
        self.assertTrue(
            javascript.startswith("// Generated by scripts/sync_skill_resources.py. Do not edit manually.\n")
        )

    def test_code_intelligence_distribution_contract(self) -> None:
        capabilities = load_yaml(ROOT / "registry" / "capabilities.yaml")["capabilities"]
        capability = next(item for item in capabilities if item["id"] == "code-intelligence-contract")
        self.assertEqual(
            {
                "id": "code-intelligence-contract",
                "path": "skills/code-intelligence-contract/SKILL.md",
                "type": "gate",
                "packs": ["studio-core"],
                "risk_level": "read-only",
                "maturity": "experimental",
                "depends_on": ["using-game-studio-skills"],
            },
            capability,
        )
        packs = {item["id"]: item for item in load_yaml(ROOT / "registry" / "packs.yaml")["packs"]}
        self.assertEqual(1, packs["studio-core"]["skills"].count("code-intelligence-contract"))

        resources = load_yaml(ROOT / "registry" / "skill-resources.yaml")["bundled"]
        self.assertEqual(
            [
                "code_intelligence.py",
                "code_intelligence_graph.py",
                {"source": "evals/schema/code-intelligence-evidence.schema.json", "destination": "schemas/code-intelligence-evidence.schema.json"},
                {"source": "registry/code-intelligence-providers.yaml", "destination": "references/code-intelligence-providers.yaml"},
            ],
            resources["code-intelligence-contract"],
        )
        scaffold = resources["studio-project-scaffold"]
        self.assertIn("code_intelligence.py", scaffold)
        self.assertIn(
            {"source": "registry/code-intelligence-providers.yaml", "destination": "references/code-intelligence-providers.yaml"},
            scaffold,
        )

        upstream = {item["id"] for item in load_yaml(ROOT / "registry" / "upstream-sources.yaml")["sources"]}
        providers = load_yaml(ROOT / "registry" / "code-intelligence-providers.yaml")["providers"]
        ids = [item["id"] for item in providers]
        self.assertEqual(len(ids), len(set(ids)))
        for provider in providers:
            self.assertFalse(any("argv" in key or "executable" in key for key in provider))
            if provider["upstream_source"] is not None:
                self.assertIn(provider["upstream_source"], upstream)

    def test_goal_progress_capabilities_and_pack_membership_are_registered(self) -> None:
        capabilities = {
            item["id"]: item
            for item in load_yaml(ROOT / "registry" / "capabilities.yaml")["capabilities"]
        }
        self.assertIn("studio-goal-progress", capabilities)
        self.assertIn("studio-context-brief", capabilities)
        self.assertEqual(
            {
                "id": "studio-goal-progress",
                "path": "skills/studio-goal-progress/SKILL.md",
                "type": "interactive",
                "packs": ["studio-core"],
                "risk_level": "low",
                "maturity": "experimental",
                "depends_on": ["using-game-studio-skills"],
            },
            capabilities["studio-goal-progress"],
        )
        self.assertEqual(
            {
                "id": "studio-context-brief",
                "path": "skills/studio-context-brief/SKILL.md",
                "type": "workflow",
                "packs": ["studio-core"],
                "risk_level": "low",
                "maturity": "experimental",
                "depends_on": ["studio-goal-progress"],
            },
            capabilities["studio-context-brief"],
        )

        packs = {item["id"]: item for item in load_yaml(ROOT / "registry" / "packs.yaml")["packs"]}
        studio_core = packs["studio-core"]["skills"]
        self.assertEqual(1, studio_core.count("studio-goal-progress"))
        self.assertEqual(1, studio_core.count("studio-context-brief"))
        self.assertTrue((ROOT / "skills" / "studio-goal-progress" / "SKILL.md").is_file())
        self.assertTrue((ROOT / "skills" / "studio-context-brief" / "SKILL.md").is_file())

    def test_goal_progress_and_context_brief_resources_are_registered(self) -> None:
        resources = load_yaml(ROOT / "registry" / "skill-resources.yaml")["bundled"]

        self.assertEqual(
            [
                "goal_progress.py",
                "goal_progress_core.py",
                "goal_progress_store.py",
                "goal_progress_server.py",
                "goal_progress_app_server.py",
                {
                    "source": "evals/schema/studio-goal-manifest.schema.json",
                    "destination": "schemas/studio-goal-manifest.schema.json",
                },
                {
                    "source": "evals/schema/studio-goal-event.schema.json",
                    "destination": "schemas/studio-goal-event.schema.json",
                },
                {
                    "source": "evals/schema/studio-goal-state.schema.json",
                    "destination": "schemas/studio-goal-state.schema.json",
                },
                {
                    "source": "resources/goal-progress/index.html",
                    "destination": "assets/index.html",
                },
                {
                    "source": "resources/goal-progress/styles.css",
                    "destination": "assets/styles.css",
                },
                {
                    "source": "resources/goal-progress/app.js",
                    "destination": "assets/app.js",
                },
            ],
            resources["studio-goal-progress"],
        )
        self.assertEqual(
            [
                "context_brief.py",
                {
                    "source": "evals/schema/studio-goal-state.schema.json",
                    "destination": "schemas/studio-goal-state.schema.json",
                },
                {
                    "source": "evals/schema/studio-context-projection.schema.json",
                    "destination": "schemas/studio-context-projection.schema.json",
                },
            ],
            resources["studio-context-brief"],
        )

    def test_isolated_goal_progress_and_context_brief_execute_bundled_resources(self) -> None:
        goal_source = ROOT / "skills" / "studio-goal-progress"
        context_source = ROOT / "skills" / "studio-context-brief"
        manifest = {
            "schema_version": 1,
            "goal_id": "goal-packaging-test",
            "title": "Verify isolated skill packaging",
            "repository_root": "D:/work/game",
            "repository_snapshot": "main@0123456789abcdef0123456789abcdef01234567",
            "created_at": "2026-09-04T02:00:00Z",
            "plan_version": 1,
            "scope": ["scripts/goal_progress.py"],
            "do_not_touch": ["Assets/Production"],
            "packets": [
                {
                    "id": "packet-packaging",
                    "workflow_id": "studio-goal-progress",
                    "owner": "main-thread",
                    "objective": "Verify isolated skill packaging",
                    "progress_weight": 1,
                    "dependencies": [],
                    "completion_criteria": ["Packaging test passes"],
                    "required_evidence": ["test-command"],
                    "estimate_seconds": {"low": 1, "high": 2},
                    "owned_paths": ["scripts/goal_progress.py"],
                    "excluded_paths": ["Assets/Production"],
                }
            ],
            "final_verification_required": ["packaging-tests"],
            "runtime_bindings": [{"kind": "codex_thread", "id": "thread-packaging"}],
            "timing_policy": {"max_active_timed_packets": 1},
        }
        state = {
            "goal_id": manifest["goal_id"],
            "blockers": [],
            "packets": [
                {
                    "id": "packet-packaging",
                    "status": "running",
                    "summary": "Verify isolated skill packaging",
                }
            ],
            "next_action": "Run the copied entrypoints.",
        }
        clean_environment = os.environ.copy()
        clean_environment.pop("PYTHONPATH", None)

        with tempfile.TemporaryDirectory() as temp:
            base = Path(temp)
            isolated_goal = base / goal_source.name
            isolated_context = base / context_source.name
            shutil.copytree(goal_source, isolated_goal)
            shutil.copytree(context_source, isolated_context)

            manifest_path = base / "manifest.json"
            manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
            goals = base / "goals"
            goals.mkdir()
            goal_root = goals / str(manifest["goal_id"])

            goal_help = subprocess.run(
                [sys.executable, "-B", "scripts/goal_progress.py", "--help"],
                cwd=isolated_goal,
                env=clean_environment,
                capture_output=True,
                text=True,
                check=False,
            )
            goal_preflight = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "scripts/goal_progress.py",
                    "preflight",
                    "--manifest",
                    str(manifest_path),
                    "--goal-root",
                    str(goal_root),
                    "--json",
                ],
                cwd=isolated_goal,
                env=clean_environment,
                capture_output=True,
                text=True,
                check=False,
            )
            goal_resolution = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "-c",
                    (
                        "import json, pathlib; "
                        "from scripts.goal_progress_server import discover_dashboard_assets; "
                        "root=pathlib.Path('.').resolve(); "
                        "assets=discover_dashboard_assets(root/'scripts'/'goal_progress_server.py'); "
                        "schema_names=['studio-goal-manifest.schema.json','studio-goal-event.schema.json','studio-goal-state.schema.json']; "
                        "schemas=[json.loads((root/'schemas'/name).read_text(encoding='utf-8'))['$id'] for name in schema_names]; "
                        "print(json.dumps({'assets':sorted(item.name for item in assets.iterdir()),'schemas':schemas},sort_keys=True))"
                    ),
                ],
                cwd=isolated_goal,
                env=clean_environment,
                capture_output=True,
                text=True,
                check=False,
            )

            context_goal = base / "context-goal"
            context_goal.mkdir()
            (context_goal / "goal.json").write_text(json.dumps(manifest), encoding="utf-8")
            (context_goal / "state.json").write_text(json.dumps(state), encoding="utf-8")
            context_help = subprocess.run(
                [sys.executable, "-B", "scripts/context_brief.py", "--help"],
                cwd=isolated_context,
                env=clean_environment,
                capture_output=True,
                text=True,
                check=False,
            )
            context_projection = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "scripts/context_brief.py",
                    "--goal-root",
                    str(context_goal),
                    "--projection",
                    "brief",
                    "--json",
                ],
                cwd=isolated_context,
                env=clean_environment,
                capture_output=True,
                text=True,
                check=False,
            )
            context_resolution = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "-c",
                    (
                        "import json, pathlib; "
                        "root=pathlib.Path('.').resolve(); "
                        "schema_names=['studio-goal-state.schema.json','studio-context-projection.schema.json']; "
                        "print(json.dumps([json.loads((root/'schemas'/name).read_text(encoding='utf-8'))['$id'] for name in schema_names]))"
                    ),
                ],
                cwd=isolated_context,
                env=clean_environment,
                capture_output=True,
                text=True,
                check=False,
            )
            goal_root_exists = goal_root.exists()
            projected_paths = [Path(path) for path in json.loads(context_projection.stdout)] if context_projection.returncode == 0 else []
            projected_files_exist = bool(projected_paths) and all(
                path.is_file() for path in projected_paths
            )

        for result in (
            goal_help,
            goal_preflight,
            goal_resolution,
            context_help,
            context_projection,
            context_resolution,
        ):
            self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        self.assertEqual("READY", json.loads(goal_preflight.stdout)["status"])
        self.assertFalse(goal_root_exists)
        goal_resources = json.loads(goal_resolution.stdout)
        self.assertEqual(["app.js", "index.html", "styles.css"], goal_resources["assets"])
        self.assertEqual(3, len(goal_resources["schemas"]))
        self.assertEqual(2, len(json.loads(context_resolution.stdout)))
        self.assertEqual(2, len(projected_paths))
        self.assertTrue(projected_files_exist, projected_paths)

    def test_generated_skill_resources_are_in_sync(self) -> None:
        result = subprocess.run(
            [sys.executable, "-B", "scripts/sync_skill_resources.py", ".", "--check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)

    def test_isolated_release_preflight_skill_loads_its_bundled_schema(self) -> None:
        source = ROOT / "skills" / "release-candidate-preflight"
        with tempfile.TemporaryDirectory() as temp:
            isolated = Path(temp) / "release-candidate-preflight"
            shutil.copytree(source, isolated)
            script = isolated / "scripts" / "release_preflight.py"
            schema = isolated / "schemas" / "release-preflight.schema.json"
            self.assertTrue(schema.is_file(), schema)
            result = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "-c",
                    (
                        "import importlib.util, pathlib, sys; "
                        "path=pathlib.Path(sys.argv[1]); "
                        "spec=importlib.util.spec_from_file_location('isolated_release_preflight', path); "
                        "module=importlib.util.module_from_spec(spec); "
                        "spec.loader.exec_module(module); "
                        "print(module.load_release_preflight_schema()['$id'])"
                    ),
                    str(script),
                ],
                cwd=isolated,
                capture_output=True,
                text=True,
                check=False,
            )

        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        self.assertIn("release-preflight.schema.json", result.stdout)

    def test_isolated_ui_art_motion_skill_loads_bundled_schemas(self) -> None:
        source = ROOT / "skills" / "unity-ui-art-and-motion-production"
        with tempfile.TemporaryDirectory() as temp:
            isolated = Path(temp) / source.name
            shutil.copytree(source, isolated)
            script = isolated / "scripts" / "ui_art_motion.py"
            self.assertTrue((isolated / "schemas" / "ui-asset-manifest.schema.json").is_file())
            self.assertTrue((isolated / "schemas" / "ui-motion-manifest.schema.json").is_file())
            result = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "-c",
                    (
                        "import importlib.util, pathlib, sys; "
                        "path=pathlib.Path(sys.argv[1]); "
                        "spec=importlib.util.spec_from_file_location('isolated_ui_art_motion', path); "
                        "module=importlib.util.module_from_spec(spec); "
                        "spec.loader.exec_module(module); "
                        "paths=module.schema_paths(); "
                        "assert all(item.is_file() for item in paths.values()), paths; "
                        "print(paths)"
                    ),
                    str(script),
                ],
                cwd=isolated,
                capture_output=True,
                text=True,
                check=False,
            )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        self.assertIn("ui-asset-manifest.schema.json", result.stdout)
        self.assertIn("ui-motion-manifest.schema.json", result.stdout)

    def test_isolated_ui_art_qc_skill_loads_bundled_helper(self) -> None:
        source = ROOT / "skills" / "unity-ui-art-and-motion-production"
        with tempfile.TemporaryDirectory() as temp:
            isolated = Path(temp) / source.name
            shutil.copytree(source, isolated)
            script = isolated / "scripts" / "ui_art_qc.py"
            self.assertTrue((isolated / "schemas" / "ui-design-brief.schema.json").is_file())
            self.assertTrue((isolated / "schemas" / "ui-art-qc-report.schema.json").is_file())
            result = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "-c",
                    (
                        "import importlib.util, pathlib, sys; "
                        "path=pathlib.Path(sys.argv[1]); "
                        "spec=importlib.util.spec_from_file_location('isolated_ui_art_qc', path); "
                        "module=importlib.util.module_from_spec(spec); "
                        "spec.loader.exec_module(module); "
                        "candidates=module._schema_candidates(pathlib.Path('missing/ui-design-brief.schema.json')); "
                        "schema=next(item for item in candidates if item.is_file()); "
                        "print(schema)"
                    ),
                    str(script),
                ],
                cwd=isolated,
                capture_output=True,
                text=True,
                check=False,
            )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        self.assertIn("ui-design-brief.schema.json", result.stdout)

    def test_isolated_screenshot_showcase_skill_loads_bundled_schemas(self) -> None:
        source = ROOT / "skills" / "game-screenshot-showcase-and-store-packaging"
        with tempfile.TemporaryDirectory() as temp:
            isolated = Path(temp) / source.name
            shutil.copytree(source, isolated)
            script = isolated / "scripts" / "screenshot_showcase.py"
            result = subprocess.run(
                [
                    sys.executable,
                    "-B",
                    "-c",
                    (
                        "import importlib.util, pathlib, sys; "
                        "path=pathlib.Path(sys.argv[1]); "
                        "spec=importlib.util.spec_from_file_location('isolated_screenshot_showcase', path); "
                        "module=importlib.util.module_from_spec(spec); "
                        "spec.loader.exec_module(module); "
                        "names=['capture-plan','capture-record','showcase-deck','store-export-manifest']; "
                        "loaded={name: module._load_schema(name)[0]['$id'] for name in names}; "
                        "print(loaded)"
                    ),
                    str(script),
                ],
                cwd=isolated,
                capture_output=True,
                text=True,
                check=False,
            )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        self.assertIn("capture-plan.schema.json", result.stdout)
        self.assertIn("store-export-manifest.schema.json", result.stdout)

    def test_release_preflight_skill_documents_helper_dependencies(self) -> None:
        skill = (
            ROOT / "skills" / "release-candidate-preflight" / "SKILL.md"
        ).read_text(encoding="utf-8")

        self.assertIn("Python 3.11+", skill)
        self.assertIn("jsonschema", skill)

    def test_standalone_router_does_not_require_repository_only_indexes(self) -> None:
        router = (ROOT / "skills" / "using-game-studio-skills" / "SKILL.md").read_text(
            encoding="utf-8"
        )
        workflow = re.search(r"^## Workflow\s*$\n(.*?)(?=^## |\Z)", router, re.MULTILINE | re.DOTALL)
        self.assertIsNotNone(workflow)
        self.assertNotIn("registry/", workflow.group(1))
        self.assertNotIn("docs/", workflow.group(1))

    def test_standalone_skill_bodies_make_repository_indexes_optional(self) -> None:
        for skill_path in sorted((ROOT / "skills").glob("*/SKILL.md")):
            body = skill_path.read_text(encoding="utf-8").split("---", 2)[-1]
            if "registry/" not in body:
                continue
            self.assertTrue(
                "when present" in body or "full repository clone" in body,
                skill_path,
            )

    def test_wiki_marks_root_script_workflows_as_full_clone_maintenance(self) -> None:
        guide = (ROOT / "docs" / "wiki-skill-agent-user-guide.md").read_text(
            encoding="utf-8"
        )
        section = re.search(
            r"^### Scaffold skills and agents into a game project\s*$\n(.*?)(?=^## |\Z)",
            guide,
            re.MULTILINE | re.DOTALL,
        )
        self.assertIsNotNone(section)
        self.assertIn("full repository clone", section.group(1))

    def test_screenshot_showcase_capability_pack_and_resources_are_registered(self) -> None:
        capabilities = load_yaml(ROOT / "registry" / "capabilities.yaml")["capabilities"]
        capability = next(
            item
            for item in capabilities
            if item["id"] == "game-screenshot-showcase-and-store-packaging"
        )
        self.assertEqual(
            {
                "id": "game-screenshot-showcase-and-store-packaging",
                "path": "skills/game-screenshot-showcase-and-store-packaging/SKILL.md",
                "type": "workflow",
                "packs": ["content-production"],
                "risk_level": "medium",
                "maturity": "experimental",
                "depends_on": [
                    "playtest-evidence",
                    "build-and-runtime-verification",
                    "store-submission-checklist",
                ],
            },
            capability,
        )

        packs = {item["id"]: item for item in load_yaml(ROOT / "registry" / "packs.yaml")["packs"]}
        self.assertIn(
            "game-screenshot-showcase-and-store-packaging",
            packs["content-production"]["skills"],
        )

        registry = load_yaml(ROOT / "registry" / "skill-resources.yaml")
        self.assertEqual(
            [
                "screenshot_showcase.py",
                {
                    "source": "evals/schema/capture-plan.schema.json",
                    "destination": "schemas/capture-plan.schema.json",
                },
                {
                    "source": "evals/schema/capture-record.schema.json",
                    "destination": "schemas/capture-record.schema.json",
                },
                {
                    "source": "evals/schema/showcase-deck.schema.json",
                    "destination": "schemas/showcase-deck.schema.json",
                },
                {
                    "source": "evals/schema/store-export-manifest.schema.json",
                    "destination": "schemas/store-export-manifest.schema.json",
                },
            ],
            registry["bundled"]["game-screenshot-showcase-and-store-packaging"],
        )
        self.assertIn(
            {
                "source": "agents/game-showcase-capture-producer.toml",
                "destination": "templates/specialists/game-showcase-capture-producer.toml",
            },
            registry["bundled"]["studio-project-scaffold"],
        )

    def test_referenced_helpers_are_bundled_or_declared_repository_only(self) -> None:
        from scripts.sync_skill_resources import render_generated_resource

        registry_path = ROOT / "registry" / "skill-resources.yaml"
        self.assertTrue(registry_path.is_file(), registry_path)
        registry = load_yaml(registry_path)
        self.assertEqual({"schema_version", "bundled", "repository_only"}, set(registry))
        self.assertEqual(2, registry["schema_version"])

        bundled = registry["bundled"]
        repository_only = registry["repository_only"]
        self.assertIsInstance(bundled, dict)
        self.assertIsInstance(repository_only, dict)

        for skill_path in sorted((ROOT / "skills").glob("*/SKILL.md")):
            skill_id = skill_path.parent.name
            body = skill_path.read_text(encoding="utf-8")
            referenced = set(SCRIPT_REFERENCE.findall(body))
            bundled_resources = [normalize_resource(entry) for entry in bundled.get(skill_id, [])]
            repository_resources = [
                normalize_resource(entry) for entry in repository_only.get(skill_id, [])
            ]
            declared_bundled = {
                source.parts[1]
                for source_value, _destination in bundled_resources
                if (source := PurePosixPath(source_value)).parts[:1] == ("scripts",)
                and len(source.parts) == 2
                and source.suffix == ".py"
            }
            declared_repository_only = {
                source.parts[1]
                for source_value, _destination in repository_resources
                if (source := PurePosixPath(source_value)).parts[:1] == ("scripts",)
                and len(source.parts) == 2
                and source.suffix == ".py"
            }

            self.assertEqual(
                referenced,
                declared_bundled | declared_repository_only,
                f"resource registry mismatch for {skill_id}",
            )
            if declared_repository_only:
                self.assertTrue(
                    "full repository clone" in body or "full kit clone" in body,
                    skill_path,
                )

            for source_value, destination_value in bundled_resources:
                source = ROOT.joinpath(*PurePosixPath(source_value).parts)
                generated = skill_path.parent.joinpath(*PurePosixPath(destination_value).parts)
                self.assertTrue(source.is_file(), source)
                self.assertTrue(generated.is_file(), generated)
                self.assertEqual(
                    render_generated_resource(
                        generated,
                        source.read_text(encoding="utf-8"),
                    ),
                    generated.read_text(encoding="utf-8"),
                    generated,
                )

    def test_resource_registry_only_names_known_skills_and_scripts(self) -> None:
        registry = load_yaml(ROOT / "registry" / "skill-resources.yaml")
        known_skills = {path.parent.name for path in (ROOT / "skills").glob("*/SKILL.md")}
        declared_destinations: set[tuple[str, str]] = set()

        for section in ("bundled", "repository_only"):
            mapping = registry[section]
            self.assertTrue(set(mapping).issubset(known_skills))
            for skill_id, entries in mapping.items():
                self.assertIsInstance(entries, list, skill_id)
                normalized = [normalize_resource(entry) for entry in entries]
                self.assertEqual(len(normalized), len(set(normalized)), skill_id)
                for entry, (source_value, destination_value) in zip(entries, normalized):
                    if isinstance(entry, str):
                        self.assertRegex(entry, r"^[a-z0-9_]+\.py$")
                    source_path = assert_safe_relative_path(self, source_value)
                    destination_path = assert_safe_relative_path(self, destination_value)
                    self.assertIn(source_path.suffix.casefold(), SUPPORTED_SUFFIXES, source_value)
                    self.assertEqual(source_path.suffix.casefold(), destination_path.suffix.casefold())

                    source = ROOT.joinpath(*source_path.parts)
                    self.assertTrue(source.is_file(), source)

                    destination_key = (skill_id, destination_path.as_posix())
                    self.assertNotIn(destination_key, declared_destinations, destination_key)
                    declared_destinations.add(destination_key)


if __name__ == "__main__":
    unittest.main()
