from __future__ import annotations

import json
import unittest
from pathlib import Path

from scripts.generated_resources import (
    CapturedSource,
    is_generated_resource,
    render_generated_resource,
)
from tests._meta.support import temporary_directory


MARKER = "Generated by test. Do not edit manually."


class GeneratedResourcesTests(unittest.TestCase):
    def test_render_uses_captured_bytes_and_replaces_an_accepted_json_comment(self) -> None:
        with temporary_directory() as temp:
            path = Path(temp) / "schema.json"
            original = b'{"$comment":"upstream marker","type":"object"}\n'
            path.write_bytes(original)
            captured = CapturedSource(path=path, data=original)
            path.write_text('{"type":"changed"}\n', encoding="utf-8")

            rendered = render_generated_resource(
                captured,
                marker=MARKER,
                accepted_json_comments=("upstream marker",),
            )

            self.assertEqual(
                {"$comment": MARKER, "type": "object"},
                json.loads(rendered),
            )
            self.assertTrue(rendered.endswith("\n"))

    def test_ownership_detection_is_syntax_specific_and_supports_metadata_files(self) -> None:
        javascript = Path("app.js")
        css = Path("styles.css")
        registry = Path("registry.json")

        self.assertTrue(
            is_generated_resource(
                javascript,
                f"// {MARKER}\n",
                marker=MARKER,
            )
        )
        self.assertFalse(
            is_generated_resource(
                javascript,
                f"/* {MARKER} */\n",
                marker=MARKER,
            )
        )
        self.assertFalse(
            is_generated_resource(
                css,
                f"// {MARKER}\n",
                marker=MARKER,
            )
        )
        self.assertTrue(
            is_generated_resource(
                registry,
                json.dumps({"_generated": MARKER}),
                marker=MARKER,
                metadata_names=("registry.json",),
            )
        )


if __name__ == "__main__":
    unittest.main()
