from __future__ import annotations

import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from tests.packaging.packs_adapters_support import (
    PackagingTestCase,
    apply_reviewed_project_adapter,
    temporary_directory,
    tree_digest,
)


class PackBuildTests(PackagingTestCase):
    def test_pack_build_is_deterministic_and_generated(self) -> None:
        from scripts.build_packs import build_all_packs
        from scripts.catalog_graph import resolve_pack_skill_closure
        from scripts.common import load_yaml

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            output = Path(temp) / "packs"
            first = build_all_packs(source_root, output)
            first_digest = tree_digest(output)
            second = build_all_packs(source_root, output)
            second_digest = tree_digest(output)
            self.assertEqual(first_digest, second_digest)
            self.assertEqual(first, second)
            self.assertEqual(
                {"studio-core", "unity", "cpp-lua-mmorpg", "production-design-liveops", "production-management", "content-production", "product-analytics"},
                set(first),
            )
            content_manifest = json.loads(
                (output / "content-production" / "manifest.json").read_text(encoding="utf-8")
            )
            packs = load_yaml(source_root / "registry" / "packs.yaml")["packs"]
            capabilities = load_yaml(
                source_root / "registry" / "capabilities.yaml"
            )["capabilities"]
            resolved_skills = resolve_pack_skill_closure(
                packs,
                capabilities,
                "content-production",
            )
            self.assertEqual(resolved_skills, content_manifest["skills"])
            for skill in resolved_skills:
                self.assertTrue(
                    (output / "content-production" / "skills" / skill).is_dir(),
                    skill,
                )
            self.assertEqual(
                [
                    "level-and-content-design-review",
                    "narrative-quest-content-contract",
                    "art-asset-pipeline-preflight",
                    "animation-rigging-import-audit",
                    "audio-content-pipeline-review",
                    "unity-ui-art-and-motion-production",
                    "game-screenshot-showcase-and-store-packaging",
                ],
                content_manifest["declared_skills"],
            )
            manifest = json.loads((output / "studio-core" / "manifest.json").read_text(encoding="utf-8"))
            self.assertIn("Do not edit manually", manifest["_generated"])
            generated_skill = output / "studio-core" / "skills" / "studio-project-intake" / "SKILL.md"
            generated_text = generated_skill.read_text(encoding="utf-8")
            self.assertIn("# Generated by scripts/build_packs.py", "\n".join(generated_text.splitlines()[:3]))
            generated_helper = (
                output
                / "studio-core"
                / "skills"
                / "studio-project-scaffold"
                / "scripts"
                / "project_scaffold.py"
            )
            self.assertTrue(generated_helper.is_file())
            self.assertTrue(
                generated_helper.read_text(encoding="utf-8").startswith(
                    "# Generated by scripts/build_packs.py. Do not edit manually."
                )
            )
            scaffold_copies = sorted(output.glob("*/skills/studio-project-scaffold"))
            self.assertTrue(scaffold_copies)
            for scaffold in scaffold_copies:
                for role in ("investigator", "implementer", "verifier"):
                    template = scaffold / "templates" / "agents" / f"{role}.toml"
                    self.assertTrue(template.is_file(), template)
                    text = template.read_text(encoding="utf-8")
                    self.assertTrue(
                        text.startswith("# Generated by scripts/build_packs.py. Do not edit manually.")
                    )
                    self.assertIn(
                        "# Generated by scripts/sync_skill_resources.py. Do not edit manually.",
                        text,
                    )
            generated_schema = (
                output
                / "production-design-liveops"
                / "skills"
                / "release-candidate-preflight"
                / "schemas"
                / "release-preflight.schema.json"
            )
            schema = json.loads(generated_schema.read_text(encoding="utf-8"))
            self.assertEqual(
                "Generated by scripts/build_packs.py. Do not edit manually.",
                schema["$comment"],
            )

    def test_pack_build_rejects_partial_catalog_before_mutation(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            registry = root / "registry"
            registry.mkdir()
            (registry / "packs.yaml").write_text(
                "schema_version: 1\npacks:\n"
                "- id: demo-pack\n"
                "  description: Demo pack\n"
                "  skills: [demo]\n"
                "  depends_on: []\n",
                encoding="utf-8",
            )
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            output = Path(temp) / "packs"

            with self.assertRaisesRegex(FileNotFoundError, "capabilities.yaml"):
                build_pack(root, pack, output)

            self.assertFalse(output.exists())

    def test_pack_build_rejects_caller_metadata_drift_from_catalog(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            registry = root / "registry"
            registry.mkdir()
            (registry / "packs.yaml").write_text(
                "schema_version: 1\npacks:\n"
                "- id: demo-pack\n"
                "  description: Canonical pack\n"
                "  skills: [demo]\n"
                "  depends_on: []\n",
                encoding="utf-8",
            )
            (registry / "capabilities.yaml").write_text(
                "schema_version: 1\ncapabilities:\n"
                "- id: demo\n"
                "  path: skills/demo/SKILL.md\n"
                "  depends_on: []\n",
                encoding="utf-8",
            )
            caller_pack = {
                "id": "demo-pack",
                "description": "Caller drift",
                "skills": ["demo"],
                "depends_on": [],
            }
            output = Path(temp) / "packs"

            with self.assertRaisesRegex(ValueError, "does not match canonical catalog"):
                build_pack(root, caller_pack, output)

            self.assertFalse(output.exists())

    def test_pack_build_rejects_output_nested_in_skill_source_before_mutation(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output = skill / "generated"
            before = tree_digest(skill)
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }

            with self.assertRaisesRegex(ValueError, "overlaps"):
                build_pack(root, pack, output)

            self.assertEqual(before, tree_digest(skill))
            self.assertFalse(output.exists())

    def test_pack_cleanup_rejects_marker_only_in_unmanaged_body(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output = Path(temp) / "packs"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            build_pack(root, pack, output)
            note = output / "demo-pack" / "notes.txt"
            note_text = (
                "Local note mentions Generated by scripts/build_packs.py. "
                "Do not edit manually.\n"
            )
            note.write_text(note_text, encoding="utf-8")

            with self.assertRaisesRegex(RuntimeError, "unmanaged"):
                build_pack(root, pack, output)

            self.assertEqual(note_text, note.read_text(encoding="utf-8"))

    def test_pack_build_rejects_unsafe_pack_id_before_mutation(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            temp_root = Path(temp)
            root = temp_root / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = temp_root / "nested" / "packs"
            escaped = temp_root / "escaped"
            pack = {
                "id": "../../escaped",
                "description": "Unsafe pack",
                "skills": ["demo"],
                "depends_on": [],
            }

            with self.assertRaisesRegex(ValueError, "unsafe pack id"):
                build_pack(root, pack, output_root)

            self.assertFalse(output_root.exists())
            self.assertFalse(escaped.exists())

    def test_pack_build_rejects_unsafe_skill_name_before_mutation(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            outside = root / "outside"
            outside.mkdir(parents=True)
            (outside / "SKILL.md").write_text(
                "---\nname: outside\n---\n\n# Outside\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            pack = {
                "id": "demo-pack",
                "description": "Unsafe skill",
                "skills": ["../outside"],
                "depends_on": [],
            }

            with self.assertRaisesRegex(ValueError, "unsafe pack skill"):
                build_pack(root, pack, output_root)

            self.assertFalse(output_root.exists())

    def test_pack_rejects_output_in_unselected_canonical_skills_sibling(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            skills_root = root / "skills"
            before = tree_digest(skills_root)
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }

            with self.assertRaisesRegex(ValueError, "canonical skills"):
                build_pack(root, pack, skills_root / "generated-packs")

            self.assertEqual(before, tree_digest(skills_root))

    def test_pack_source_swap_after_walk_never_packages_external_content(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            temp_root = Path(temp)
            root = temp_root / "kit"
            skill = root / "skills" / "demo"
            resources = skill / "resources"
            resources.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            (resources / "note.txt").write_text("trusted source\n", encoding="utf-8")
            external = temp_root / "external"
            external.mkdir()
            (external / "note.txt").write_text("external payload\n", encoding="utf-8")
            backup = skill / "resources.original"
            output_root = temp_root / "packs"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            original_walk = packs._walk_files
            swapped = False

            def swap_after_walk(path: Path, **kwargs: object) -> object:
                nonlocal swapped
                walked = original_walk(path, **kwargs)
                if path == skill and kwargs.get("ignore_runtime_cache") and not swapped:
                    resources.rename(backup)
                    self.create_directory_alias(resources, external)
                    swapped = True
                return walked

            try:
                with mock.patch.object(packs, "_walk_files", side_effect=swap_after_walk):
                    packs.build_pack(root, pack, output_root)
            finally:
                if os.path.lexists(resources) and swapped:
                    self.remove_directory_alias(resources)
                if backup.exists():
                    backup.rename(resources)

            generated = (
                output_root / "demo-pack" / "skills" / "demo" / "resources" / "note.txt"
            ).read_text(encoding="utf-8")
            self.assertIn("trusted source", generated)
            self.assertNotIn("external payload", generated)

    def test_pack_rejects_nested_directory_replaced_after_parent_scan(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            temp_root = Path(temp)
            root = temp_root / "kit"
            skill = root / "skills" / "demo"
            nested = skill / "resources"
            nested.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            (nested / "note.txt").write_text("trusted source\n", encoding="utf-8")
            external = temp_root / "external"
            external.mkdir()
            (external / "note.txt").write_text("external payload\n", encoding="utf-8")
            external_before = tree_digest(external)
            backup = skill / "resources.original"
            output_root = temp_root / "packs"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            original_scandir = packs.os.scandir
            swapped = False

            class SwapOnDirectoryCheck:
                def __init__(self, entry: os.DirEntry[str]) -> None:
                    self._entry = entry

                def __getattr__(self, name: str) -> object:
                    return getattr(self._entry, name)

                def is_dir(self, *, follow_symlinks: bool = True) -> bool:
                    nonlocal swapped
                    result = self._entry.is_dir(follow_symlinks=follow_symlinks)
                    if Path(self._entry.path) == nested and result and not swapped:
                        nested.rename(backup)
                        self_outer.create_directory_alias(nested, external)
                        swapped = True
                    return result

            self_outer = self

            def scanning(path: str | os.PathLike[str]) -> object:
                entries = list(original_scandir(path))
                if Path(path) == skill:
                    return iter(SwapOnDirectoryCheck(entry) for entry in entries)
                return iter(entries)

            try:
                with mock.patch.object(packs.os, "scandir", side_effect=scanning):
                    with self.assertRaisesRegex(ValueError, "reparse point|changed"):
                        packs.build_pack(root, pack, output_root)
            finally:
                if os.path.lexists(nested) and swapped:
                    self.remove_directory_alias(nested)
                if backup.exists():
                    backup.rename(nested)

            self.assertFalse((output_root / "demo-pack").exists())
            self.assertEqual(external_before, tree_digest(external))

    def test_pack_rejects_directory_replaced_inside_scandir(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            temp_root = Path(temp)
            root = temp_root / "kit"
            skill = root / "skills" / "demo"
            nested = skill / "resources"
            nested.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            (nested / "note.txt").write_text("trusted source\n", encoding="utf-8")
            external = temp_root / "external"
            external.mkdir()
            (external / "note.txt").write_text("external payload\n", encoding="utf-8")
            external_before = tree_digest(external)
            backup = skill / "resources.original"
            output_root = temp_root / "packs"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            original_scandir = packs.os.scandir
            swapped = False

            def swap_inside_scan(path: str | os.PathLike[str]) -> object:
                nonlocal swapped
                if Path(path) == nested and not swapped:
                    nested.rename(backup)
                    self.create_directory_alias(nested, external)
                    swapped = True
                return original_scandir(path)

            try:
                with mock.patch.object(packs.os, "scandir", side_effect=swap_inside_scan):
                    with self.assertRaisesRegex(ValueError, "reparse point|changed"):
                        packs.build_pack(root, pack, output_root)
            finally:
                if os.path.lexists(nested) and swapped:
                    self.remove_directory_alias(nested)
                if backup.exists():
                    backup.rename(nested)

            self.assertFalse((output_root / "demo-pack").exists())
            self.assertEqual(external_before, tree_digest(external))

    def test_pack_render_failure_preserves_previous_output(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            build_pack(root, pack, output_root)
            before = tree_digest(output)
            before_siblings = sorted(path.name for path in output_root.iterdir())
            (skill / "unsupported.bin").write_bytes(b"unsupported\n")

            with self.assertRaisesRegex(ValueError, "unsupported skill resource"):
                build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            self.assertEqual(
                before_siblings,
                sorted(path.name for path in output_root.iterdir()),
            )

    def test_pack_swap_failure_restores_previous_output(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            before = tree_digest(output)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory

            def fail_stage_rename(source: Path, target: Path) -> Path:
                if source.name.endswith(".stage"):
                    raise OSError("injected stage swap failure")
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=fail_stage_rename,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            recovery = json.loads(
                (output_root / ".demo-pack.swap-recovery.json").read_text(encoding="utf-8")
            )
            self.assertTrue(Path(recovery["stage"]).is_dir())

    def test_pack_publication_journal_exists_before_stage_rename(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text("---\nname: demo\n---\n\n# Demo\n", encoding="utf-8")
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            skill_file.write_text("---\nname: demo\n---\n\n# Changed\n", encoding="utf-8")
            original_rename = packs._rename_owned_directory
            journal_seen = False

            def observe_before_publish(source: Path, target: Path) -> Path:
                nonlocal journal_seen
                if source.name.endswith(".stage"):
                    journal_seen = (output_root / ".demo-pack.swap-recovery.json").is_file()
                    raise OSError("stop at publication boundary")
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=observe_before_publish,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertTrue(journal_seen)

    def test_pack_recovery_journal_tracks_prepared_and_output_moved_states(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text("---\nname: demo\n---\n\n# Demo\n", encoding="utf-8")
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            recovery_path = output_root / ".demo-pack.swap-recovery.json"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            skill_file.write_text("---\nname: demo\n---\n\n# Changed\n", encoding="utf-8")
            original_rename = packs._rename_owned_directory
            observed_states: list[str] = []

            def observe_transition(source: Path, target: Path) -> Path:
                if source == output or source.name.endswith(".stage"):
                    recovery = json.loads(recovery_path.read_text(encoding="utf-8"))
                    observed_states.append(recovery["state"])
                if source.name.endswith(".stage"):
                    raise OSError("stop after output move")
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=observe_transition,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(["prepared", "output-moved"], observed_states)

    def test_pack_prejournal_failure_keeps_output_visible_without_rename(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text("---\nname: demo\n---\n\n# Demo\n", encoding="utf-8")
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            before = tree_digest(output)
            skill_file.write_text("---\nname: demo\n---\n\n# Changed\n", encoding="utf-8")
            rename_calls = 0

            def count_rename(source: Path, target: Path) -> Path:
                nonlocal rename_calls
                rename_calls += 1
                return target

            with mock.patch.object(
                packs,
                "_write_swap_recovery",
                side_effect=OSError("injected prejournal failure"),
            ), mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=count_rename,
            ):
                with self.assertRaisesRegex(OSError, "injected prejournal failure"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(0, rename_calls)
            self.assertEqual(before, tree_digest(output))
            self.assertEqual(1, len(list(output_root.glob(".demo-pack.*.stage"))))

    def test_pack_first_swap_rename_failure_preserves_previous_output(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            before = tree_digest(output)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory

            def fail_old_output_rename(source: Path, target: Path) -> Path:
                if source == output:
                    raise OSError("injected old-output rename failure")
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=fail_old_output_rename,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            recovery = json.loads(
                (output_root / ".demo-pack.swap-recovery.json").read_text(encoding="utf-8")
            )
            self.assertTrue(Path(recovery["stage"]).is_dir())

    def test_pack_concurrent_edit_before_old_output_rename_is_restored_visible(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            generated_skill = output / "skills" / "demo" / "SKILL.md"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# New staged content\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory
            injected = False

            def edit_before_rename(source: Path, target: Path) -> Path:
                nonlocal injected
                if source == output and not injected:
                    generated_skill.write_text(
                        generated_skill.read_text(encoding="utf-8")
                        + "\n# concurrent user edit\n",
                        encoding="utf-8",
                    )
                    injected = True
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=edit_before_rename,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery|changed"):
                    packs.build_pack(root, pack, output_root)

            visible = generated_skill.read_text(encoding="utf-8")
            self.assertIn("# Demo", visible)
            self.assertIn("concurrent user edit", visible)
            self.assertNotIn("New staged content", visible)
            self.assertEqual(1, len(list(output_root.glob(".demo-pack.*.stage"))))
            self.assertTrue((output_root / ".demo-pack.swap-recovery.json").is_file())

    def test_pack_cleanup_preserves_concurrent_stage_replacement(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            before = tree_digest(output)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory
            original_validate = packs._validate_owned_temp
            foreign_path: Path | None = None

            def fail_stage_rename(source: Path, target: Path) -> Path:
                if source.name.endswith(".stage"):
                    raise OSError("injected stage swap failure")
                return original_rename(source, target)

            def replace_before_validation(
                path: Path,
                output_path: Path,
                suffix: str,
                *args: object,
                **kwargs: object,
            ) -> None:
                nonlocal foreign_path
                if suffix == "stage" and foreign_path is None:
                    shutil.rmtree(path)
                    path.mkdir()
                    foreign_path = path / "foreign.txt"
                    foreign_path.write_text("concurrent owner\n", encoding="utf-8")
                original_validate(path, output_path, suffix, *args, **kwargs)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=fail_stage_rename,
            ), mock.patch.object(
                packs,
                "_validate_owned_temp",
                side_effect=replace_before_validation,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            self.assertIsNotNone(foreign_path)
            assert foreign_path is not None
            self.assertEqual("concurrent owner\n", foreign_path.read_text(encoding="utf-8"))

    def test_pack_failure_cleanup_preserves_snapshot_boundary_replacement(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            before = tree_digest(output)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory
            original_snapshot = packs._tree_snapshot
            stage_snapshot_count = 0
            foreign_path: Path | None = None

            def fail_stage_rename(source: Path, target: Path) -> Path:
                if source.name.endswith(".stage"):
                    raise OSError("injected stage swap failure")
                return original_rename(source, target)

            def replace_after_snapshot(path: Path):
                nonlocal stage_snapshot_count, foreign_path
                snapshot = original_snapshot(path)
                if path.name.endswith(".stage"):
                    stage_snapshot_count += 1
                    if stage_snapshot_count == 2:
                        shutil.rmtree(path)
                        path.mkdir()
                        foreign_path = path / "foreign.txt"
                        foreign_path.write_text("snapshot-boundary owner\n", encoding="utf-8")
                return snapshot

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=fail_stage_rename,
            ), mock.patch.object(
                packs,
                "_tree_snapshot",
                side_effect=replace_after_snapshot,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            self.assertIsNotNone(foreign_path)
            assert foreign_path is not None
            self.assertEqual(
                "snapshot-boundary owner\n",
                foreign_path.read_text(encoding="utf-8"),
            )
            recovery_path = output_root / ".demo-pack.swap-recovery.json"
            self.assertTrue(recovery_path.is_file())

            with self.assertRaisesRegex(RuntimeError, "manual recovery"):
                packs.build_pack(root, pack, output_root)
            self.assertEqual(
                "snapshot-boundary owner\n",
                foreign_path.read_text(encoding="utf-8"),
            )

    def test_pack_publish_no_clobber_preserves_concurrent_output_and_stage(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory
            foreign_file = output / "foreign.txt"
            injected = False

            def create_concurrent_output(source: Path, target: Path) -> Path:
                nonlocal injected
                if source.name.endswith(".stage") and target == output and not injected:
                    output.mkdir()
                    foreign_file.write_text("concurrent output\n", encoding="utf-8")
                    injected = True
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=create_concurrent_output,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual("concurrent output\n", foreign_file.read_text(encoding="utf-8"))
            recovery_path = output_root / ".demo-pack.swap-recovery.json"
            recovery = json.loads(recovery_path.read_text(encoding="utf-8"))
            self.assertTrue(Path(recovery["stage"]).is_dir())
            self.assertTrue(Path(recovery["rollback"]).is_dir())

            with self.assertRaisesRegex(RuntimeError, "manual recovery"):
                packs.build_pack(root, pack, output_root)
            self.assertEqual("concurrent output\n", foreign_file.read_text(encoding="utf-8"))

    def test_pack_success_preserves_hash_bound_completion_without_duplicate_retry(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            packs.build_pack(root, pack, output_root)

            completion_paths = list(
                output_root.glob(".demo-pack.*.swap-completion.json")
            )
            self.assertEqual(1, len(completion_paths))
            completion = json.loads(completion_paths[0].read_text(encoding="utf-8"))
            self.assertEqual("pack-output-swap-completion", completion["kind"])
            self.assertEqual("published", completion["status"])
            self.assertTrue(Path(completion["rollback"]).is_dir())
            before_siblings = sorted(path.name for path in output_root.iterdir())

            packs.build_pack(root, pack, output_root)

            self.assertEqual(
                before_siblings,
                sorted(path.name for path in output_root.iterdir()),
            )

    def test_pack_double_swap_failure_persists_and_resumes_recovery(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            skill_file = skill / "SKILL.md"
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            packs.build_pack(root, pack, output_root)
            before = tree_digest(output)
            initial_recovery_count = len(
                list(output_root.glob(".demo-pack.*.swap-recovery.json"))
            )
            skill_file.write_text(
                "---\nname: demo\n---\n\n# Changed\n",
                encoding="utf-8",
            )
            original_rename = packs._rename_owned_directory

            def fail_publish_and_restore(source: Path, target: Path) -> Path:
                if source.name.endswith((".stage", ".rollback")):
                    raise OSError("injected double rename failure")
                return original_rename(source, target)

            with mock.patch.object(
                packs,
                "_rename_owned_directory",
                side_effect=fail_publish_and_restore,
            ):
                with self.assertRaisesRegex(RuntimeError, "swap recovery"):
                    packs.build_pack(root, pack, output_root)

            recovery_path = output_root / ".demo-pack.swap-recovery.json"
            recovery = json.loads(recovery_path.read_text(encoding="utf-8"))
            self.assertEqual(str(output), recovery["output"])
            rollback = Path(recovery["rollback"])
            stage = Path(recovery["stage"])
            self.assertTrue(rollback.is_dir())
            self.assertTrue(stage.is_dir())
            self.assertFalse(output.exists())

            with mock.patch.object(
                packs,
                "_generated_resource",
                side_effect=ValueError("stop after recovery"),
            ):
                with self.assertRaisesRegex(ValueError, "stop after recovery"):
                    packs.build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            self.assertFalse(recovery_path.exists())
            self.assertFalse(rollback.exists())
            self.assertTrue(stage.is_dir())
            self.assertEqual(
                initial_recovery_count + 1,
                len(list(output_root.glob(".demo-pack.*.swap-recovery.json"))),
            )

    def test_pack_regeneration_refuses_and_preserves_unmanaged_empty_directory(self) -> None:
        from scripts.build_packs import build_pack

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "---\nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            output_root = Path(temp) / "packs"
            output = output_root / "demo-pack"
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }
            build_pack(root, pack, output_root)
            unmanaged = output / "local-empty"
            unmanaged.mkdir()
            before = tree_digest(output)

            with self.assertRaisesRegex(RuntimeError, "unmanaged.*directory"):
                build_pack(root, pack, output_root)

            self.assertEqual(before, tree_digest(output))
            self.assertTrue(unmanaged.is_dir())


if __name__ == "__main__":
    unittest.main()
