from __future__ import annotations

import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from tests.packaging.packs_adapters_support import (
    PackagingTestCase,
    apply_reviewed_project_adapter,
    temporary_directory,
    tree_digest,
)


class GeneratedResourcesIntegrationTests(PackagingTestCase):
    def test_json_resource_generation_is_valid_deterministic_and_replaces_sync_marker(self) -> None:
        import scripts.build_packs as packs
        import scripts.generate_adapters as adapters

        with temporary_directory() as temp:
            resource = Path(temp) / "schema.json"
            resource.write_text(
                '{\n  "$comment": "Generated by scripts/sync_skill_resources.py. '
                'Do not edit manually.",\n  "type": "object",\n  "properties": {}\n}\n',
                encoding="utf-8",
            )

            for module, marker in (
                (packs, packs.MARKER),
                (adapters, adapters.MARKER),
            ):
                first = module._generated_resource(resource)
                second = module._generated_resource(resource)
                parsed = json.loads(first)
                self.assertEqual(marker, parsed["$comment"])
                self.assertEqual("object", parsed["type"])
                self.assertEqual({}, parsed["properties"])
                self.assertEqual(first, second)
                self.assertTrue(first.endswith("\n"))

    def test_adapter_resource_generation_uses_syntax_safe_markers_for_web_assets(self) -> None:
        import scripts.generate_adapters as adapters

        with temporary_directory() as temp:
            resource_root = Path(temp)
            cases = (
                ("app.js", "const ready = true;\n", f"// {adapters.MARKER}\n\n"),
                ("styles.css", ":root { color: black; }\n", f"/* {adapters.MARKER} */\n\n"),
                ("index.html", "<!doctype html>\n", f"<!-- {adapters.MARKER} -->\n\n"),
            )

            for filename, content, header in cases:
                with self.subTest(filename=filename):
                    resource = resource_root / filename
                    resource.write_bytes(content.encode("utf-8"))
                    try:
                        first = adapters._generated_resource(resource)
                    except ValueError as error:
                        self.fail(f"adapter rejected supported web resource {filename}: {error}")
                    self.assertEqual(header + content, first)
                    self.assertEqual(first, adapters._generated_resource(resource))
                    self.assertTrue(adapters._is_standard_generated_artifact(resource, first))

    def test_pack_resource_generation_uses_syntax_safe_markers_for_web_assets(self) -> None:
        import scripts.build_packs as packs

        with temporary_directory() as temp:
            resource_root = Path(temp)
            cases = (
                ("app.js", "const ready = true;\n", f"// {packs.MARKER}\n\n"),
                ("styles.css", ":root { color: black; }\n", f"/* {packs.MARKER} */\n\n"),
                ("index.html", "<!doctype html>\n", f"<!-- {packs.MARKER} -->\n\n"),
            )

            for filename, content, header in cases:
                with self.subTest(filename=filename):
                    resource = resource_root / filename
                    resource.write_bytes(content.encode("utf-8"))
                    try:
                        first = packs._generated_resource(resource)
                    except ValueError as error:
                        self.fail(f"pack rejected supported web resource {filename}: {error}")
                    self.assertEqual(header + content, first)
                    self.assertEqual(first, packs._generated_resource(resource))
                    self.assertTrue(packs._is_generated_artifact(resource, first))

    def test_adapter_generated_ownership_rejects_web_marker_suffix_collisions(self) -> None:
        import scripts.generate_adapters as adapters

        with temporary_directory() as temp:
            resource_root = Path(temp)
            markers = {
                ".js": f"// {adapters.MARKER}\n",
                ".css": f"/* {adapters.MARKER} */\n",
                ".html": f"<!-- {adapters.MARKER} -->\n",
            }
            for suffix, expected_marker in markers.items():
                resource = resource_root / f"resource{suffix}"
                resource.write_bytes(b"placeholder\n")
                self.assertTrue(
                    adapters._is_standard_generated_artifact(resource, expected_marker)
                )
                for marker_suffix, marker in markers.items():
                    if marker_suffix == suffix:
                        continue
                    with self.subTest(resource=suffix, marker=marker_suffix):
                        self.assertFalse(
                            adapters._is_standard_generated_artifact(resource, marker)
                        )

    def test_pack_and_adapter_reject_binary_web_resources_without_mutation(self) -> None:
        import scripts.build_packs as packs
        import scripts.generate_adapters as adapters

        with temporary_directory() as temp:
            resource_root = Path(temp)
            for filename, content in (
                ("app.js", b"const ready = true;\x00\n"),
                ("styles.css", b"\xff\xfebinary"),
            ):
                resource = resource_root / filename
                resource.write_bytes(content)
                for module in (packs, adapters):
                    with self.subTest(filename=filename, module=module.__name__):
                        with self.assertRaisesRegex(ValueError, "binary or non-UTF-8 resource"):
                            module._generated_resource(resource)
                        self.assertEqual(content, resource.read_bytes())

    def test_json_resource_generation_rejects_non_object_and_incompatible_comment(self) -> None:
        import scripts.build_packs as packs
        import scripts.generate_adapters as adapters

        with temporary_directory() as temp:
            resource = Path(temp) / "schema.json"
            for content, message in (
                ('["not", "an", "object"]\n', "JSON object"),
                ('{"$comment": "owned elsewhere", "type": "object"}\n', "incompatible"),
                (
                    '{"$comment": "first", "$comment": "second", "type": "object"}\n',
                    "duplicate JSON key",
                ),
            ):
                resource.write_text(content, encoding="utf-8")
                for module in (packs, adapters):
                    with self.assertRaisesRegex(ValueError, message):
                        module._generated_resource(resource)

    def test_pack_and_adapter_normalize_parser_valid_frontmatter(self) -> None:
        from scripts.build_packs import build_pack
        from scripts.generate_adapters import generate_adapter

        with temporary_directory() as temp:
            root = Path(temp) / "kit"
            skill = root / "skills" / "demo"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text(
                "--- \nname: demo\n---\n\n# Demo\n",
                encoding="utf-8",
            )
            registry = root / "registry"
            registry.mkdir()
            (registry / "packs.yaml").write_text(
                "schema_version: 1\npacks:\n"
                "- id: demo-pack\n"
                "  description: Demo pack\n"
                "  skills: [demo]\n"
                "  depends_on: []\n",
                encoding="utf-8",
            )
            (registry / "capabilities.yaml").write_text(
                "schema_version: 1\ncapabilities:\n"
                "- id: demo\n  path: skills/demo/SKILL.md\n",
                encoding="utf-8",
            )
            pack = {
                "id": "demo-pack",
                "description": "Demo pack",
                "skills": ["demo"],
                "depends_on": [],
            }

            pack_output = Path(temp) / "packs"
            build_pack(root, pack, pack_output)
            pack_lines = (
                pack_output / "demo-pack" / "skills" / "demo" / "SKILL.md"
            ).read_text(encoding="utf-8").splitlines()
            self.assertEqual("---", pack_lines[0])
            self.assertEqual(
                "# Generated by scripts/build_packs.py. Do not edit manually.",
                pack_lines[1],
            )

            adapter_output = Path(temp) / "adapter"
            generate_adapter(root, "hermes", adapter_output)
            adapter_lines = (
                adapter_output / "skills" / "demo" / "SKILL.md"
            ).read_text(encoding="utf-8").splitlines()
            self.assertEqual("---", adapter_lines[0])
            self.assertEqual(
                "# Generated by scripts/generate_adapters.py. Do not edit manually.",
                adapter_lines[1],
            )


if __name__ == "__main__":
    unittest.main()
