from __future__ import annotations

import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from tests.packaging.packs_adapters_support import (
    PackagingTestCase,
    apply_reviewed_project_adapter,
    temporary_directory,
    tree_digest,
)


class PackagingCatalogTests(PackagingTestCase):
    def test_sync_packages_readme_markdown_as_template(self) -> None:
        from scripts.sync_skill_resources import sync_skill_resources

        with temporary_directory() as temp:
            root = Path(temp)
            skill = root / "skills" / "example-skill"
            skill.mkdir(parents=True)
            (skill / "SKILL.md").write_text("---\nname: example-skill\n---\n", encoding="utf-8")
            (root / "README.md").write_text("# Reviewer reproduction\n", encoding="utf-8")
            registry = root / "registry" / "skill-resources.yaml"
            registry.parent.mkdir()
            registry.write_text(
                "\n".join([
                    "schema_version: 2",
                    "bundled:",
                    "  example-skill:",
                    "  - source: README.md",
                    "    destination: templates/readme.md",
                    "repository_only: {}",
                    "",
                ]),
                encoding="utf-8",
            )
            destination = skill / "templates" / "readme.md"

            self.assertEqual([destination], sync_skill_resources(root))
            self.assertEqual(
                "<!-- Generated by scripts/sync_skill_resources.py. Do not edit manually. -->",
                destination.read_text(encoding="utf-8").splitlines()[0],
            )

    def test_agent_overlay_plan_is_pure_and_materializes_generic_roles(self) -> None:
        from scripts.agent_overlay import plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "missing-project"

            plan = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
            )

            self.assertFalse(project.exists())
            self.assertEqual([], plan["preserved"])
            self.assertEqual([], plan["collisions"])
            self.assertEqual(
                ["implementer", "investigator", "verifier"],
                plan["activated_roles"],
            )
            self.assertEqual(
                {
                    ".codex/agents/implementer.toml",
                    ".codex/agents/investigator.toml",
                    ".codex/agents/verifier.toml",
                    ".codex/agents.generated.toml",
                },
                {operation["path"] for operation in plan["operations"]},
            )

    def test_agent_overlay_plan_adds_profile_specialists_deterministically(self) -> None:
        import tomllib
        import yaml

        from scripts.agent_overlay import plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            profile_path = project / ".agents" / "project-profile.yaml"
            profile_path.parent.mkdir(parents=True)
            profile_path.write_text(
                yaml.safe_dump(
                    {
                        "schema_version": 1,
                        "workspace": {
                            "name": "sample-game",
                            "root_git": False,
                            "default_concurrency": 2,
                        },
                        "repositories": [
                            {
                                "id": "server",
                                "path": "server",
                                "git_root": True,
                                "subsystems": ["server", "lua"],
                                "owner_skill": "studio-project-intake",
                                "validation": [],
                            }
                        ],
                        "exclusions": [],
                        "agents": {
                            "specialists": [
                                {
                                    "id": "server-specialist",
                                    "repository": "server",
                                    "reasoning_effort": "xhigh",
                                    "constraints": [
                                        "preserve frame budget",
                                        "preserve protocol compatibility",
                                    ],
                                }
                            ]
                        },
                        "cross_project_contracts": [],
                    },
                    sort_keys=False,
                ),
                encoding="utf-8",
            )

            first = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
                profile_path=profile_path,
                known_skills={"studio-project-intake"},
            )
            second = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
                profile_path=profile_path,
                known_skills={"studio-project-intake"},
            )

            self.assertEqual(first, second)
            self.assertEqual(
                ["implementer", "investigator", "server-specialist", "verifier"],
                first["activated_roles"],
            )
            operations = {operation["path"]: operation["content"] for operation in first["operations"]}
            specialist_path = ".codex/agents/server-specialist.toml"
            self.assertIn(specialist_path, operations)
            specialist = tomllib.loads(operations[specialist_path])
            self.assertEqual("server-specialist", specialist["name"])
            self.assertEqual("xhigh", specialist["model_reasoning_effort"])
            self.assertEqual("workspace-write", specialist["sandbox_mode"])
            self.assertIn("preserve frame budget", specialist["developer_instructions"])
            activation = tomllib.loads(operations[".codex/agents.generated.toml"])
            self.assertEqual(
                "./agents/server-specialist.toml",
                activation["agents"]["server-specialist"]["config_file"],
            )

    def test_agent_overlay_omits_unmanaged_specialist_from_activation(self) -> None:
        import yaml

        from scripts.agent_overlay import plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            profile_path = project / ".agents" / "project-profile.yaml"
            profile_path.parent.mkdir(parents=True)
            profile_path.write_text(
                yaml.safe_dump(
                    {
                        "schema_version": 1,
                        "workspace": {
                            "name": "sample-game",
                            "root_git": False,
                            "default_concurrency": 2,
                        },
                        "repositories": [
                            {
                                "id": "server",
                                "path": "server",
                                "git_root": True,
                                "subsystems": ["server"],
                                "owner_skill": "studio-project-intake",
                                "validation": [],
                            }
                        ],
                        "exclusions": [],
                        "agents": {
                            "specialists": [
                                {
                                    "id": "server-specialist",
                                    "repository": "server",
                                    "reasoning_effort": "high",
                                    "constraints": ["preserve protocol compatibility"],
                                }
                            ]
                        },
                        "cross_project_contracts": [],
                    },
                    sort_keys=False,
                ),
                encoding="utf-8",
            )
            unmanaged = project / ".codex" / "agents" / "server-specialist.toml"
            unmanaged.parent.mkdir(parents=True)
            unmanaged.write_text('name = "local-server-specialist"\n', encoding="utf-8")

            plan = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
                profile_path=profile_path,
                known_skills={"studio-project-intake"},
            )

            self.assertIn(".codex/agents/server-specialist.toml", plan["preserved"])
            self.assertIn(
                {
                    "path": ".codex/agents/server-specialist.toml",
                    "kind": "unmanaged-agent",
                    "role_id": "server-specialist",
                },
                plan["collisions"],
            )
            self.assertNotIn("server-specialist", plan["activated_roles"])
            activation = next(
                operation["content"]
                for operation in plan["operations"]
                if operation["path"] == ".codex/agents.generated.toml"
            )
            self.assertNotIn("server-specialist", activation)

    def test_agent_overlay_marker_mention_does_not_claim_local_agent(self) -> None:
        from scripts.agent_overlay import MARKER, plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            local_agent = project / ".codex" / "agents" / "investigator.toml"
            local_agent.parent.mkdir(parents=True)
            local_agent.write_text(
                f'name = "local-investigator"\ndescription = "mentions {MARKER}"\n',
                encoding="utf-8",
            )

            plan = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
            )

            relative = ".codex/agents/investigator.toml"
            self.assertIn(relative, plan["preserved"])
            self.assertIn(
                {"path": relative, "kind": "unmanaged-agent", "role_id": "investigator"},
                plan["collisions"],
            )
            self.assertNotIn(relative, {operation["path"] for operation in plan["operations"]})

    def test_agent_overlay_marker_mention_does_not_claim_local_activation(self) -> None:
        from scripts.agent_overlay import MARKER, plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            activation = project / ".codex" / "agents.generated.toml"
            activation.parent.mkdir(parents=True)
            activation.write_text(
                f'[agents.local]\ndescription = "mentions {MARKER}"\n',
                encoding="utf-8",
            )

            plan = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
            )

            relative = ".codex/agents.generated.toml"
            self.assertIn(relative, plan["preserved"])
            self.assertIn(
                {"path": relative, "kind": "unmanaged-activation"},
                plan["collisions"],
            )
            self.assertNotIn(relative, {operation["path"] for operation in plan["operations"]})
            self.assertEqual([], plan["activated_roles"])

    def test_agent_overlay_preserves_unmanaged_activation(self) -> None:
        from scripts.agent_overlay import plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp) / "project"
            activation = project / ".codex" / "agents.generated.toml"
            activation.parent.mkdir(parents=True)
            activation.write_text('[agents.local]\nconfig_file = "./agents/local.toml"\n', encoding="utf-8")

            plan = plan_agent_overlay(
                project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
            )

            self.assertIn(".codex/agents.generated.toml", plan["preserved"])
            self.assertIn(
                {"path": ".codex/agents.generated.toml", "kind": "unmanaged-activation"},
                plan["collisions"],
            )
            self.assertNotIn(
                ".codex/agents.generated.toml",
                {operation["path"] for operation in plan["operations"]},
            )
            self.assertEqual([], plan["activated_roles"])

    def test_agent_overlay_rejects_invalid_generic_role_ids(self) -> None:
        from scripts.agent_overlay import plan_agent_overlay

        with temporary_directory() as temp:
            temp_root = Path(temp)
            template_root = temp_root / "templates"
            template_root.mkdir()
            (template_root / "safe.toml").write_text(
                'name = "con"\ndescription = "bad"\ndeveloper_instructions = "bad"\n',
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, "invalid generic role id"):
                plan_agent_overlay(temp_root / "project", template_root=template_root)

    def test_agent_overlay_rejects_reserved_profile_specialist_defensively(self) -> None:
        import scripts.agent_overlay as overlay

        source_root = Path(__file__).resolve().parents[2]
        profile = {
            "repositories": [
                {
                    "id": "server",
                    "path": "server",
                }
            ],
            "agents": {
                "specialists": [
                    {
                        "id": "con",
                        "repository": "server",
                        "reasoning_effort": "high",
                        "constraints": ["preserve protocol compatibility"],
                    }
                ]
            },
        }
        with temporary_directory() as temp:
            temp_root = Path(temp)
            profile_path = temp_root / "profile.yaml"
            profile_path.write_text("placeholder\n", encoding="utf-8")

            with mock.patch.object(overlay, "load_project_profile", return_value=profile):
                with self.assertRaisesRegex(ValueError, "invalid specialist role id"):
                    overlay.plan_agent_overlay(
                        temp_root / "project",
                        template_root=(
                            source_root
                            / "skills"
                            / "studio-project-scaffold"
                            / "templates"
                            / "agents"
                        ),
                        profile_path=profile_path,
                    )

    def test_agent_overlay_reports_unmanaged_noncolliding_local_roles(self) -> None:
        from scripts.agent_overlay import plan_agent_overlay

        source_root = Path(__file__).resolve().parents[2]
        with tempfile.TemporaryDirectory(
            prefix="gamestudio-packaging-relative-",
            dir=Path.cwd(),
        ) as temp:
            project = Path(temp) / "project"
            local_role = project / ".codex" / "agents" / "local-reviewer.toml"
            local_role.parent.mkdir(parents=True)
            local_role.write_text(
                'name = "local-reviewer"\ndescription = "Local role"\n',
                encoding="utf-8",
            )

            relative_project = Path(os.path.relpath(project, Path.cwd()))
            plan = plan_agent_overlay(
                relative_project,
                template_root=(
                    source_root / "skills" / "studio-project-scaffold" / "templates" / "agents"
                ),
            )

            self.assertIn(".codex/agents/local-reviewer.toml", plan["preserved"])
            self.assertNotIn(
                ".codex/agents/local-reviewer.toml",
                {collision["path"] for collision in plan["collisions"]},
            )
            self.assertNotIn(
                ".codex/agents/local-reviewer.toml",
                {operation["path"] for operation in plan["operations"]},
            )


if __name__ == "__main__":
    unittest.main()
