# Generated by scripts/sync_skill_resources.py. Do not edit manually.

from __future__ import annotations

from typing import Any


def review_balance_change(
    before: dict[str, float],
    after: dict[str, float],
    bounds: dict[str, dict[str, float]],
) -> dict[str, Any]:
    changes: dict[str, dict[str, float]] = {}
    out_of_bounds: list[str] = []
    missing_bounds: list[str] = []
    for key in sorted(set(before) | set(after)):
        if key not in before or key not in after:
            changes[key] = {"before": before.get(key), "after": after.get(key), "delta": None}
            missing_bounds.append(key)
            continue
        delta = round(float(after[key]) - float(before[key]), 6)
        changes[key] = {"before": float(before[key]), "after": float(after[key]), "delta": delta}
        bound = bounds.get(key)
        if not isinstance(bound, dict) or "max_abs_delta" not in bound:
            missing_bounds.append(key)
        elif abs(delta) > float(bound["max_abs_delta"]):
            out_of_bounds.append(key)
    status = "BLOCKED" if missing_bounds else "FAIL" if out_of_bounds else "PASS"
    return {
        "status": status,
        "changes": changes,
        "out_of_bounds": out_of_bounds,
        "missing_bounds": missing_bounds,
    }
