# Generated by scripts/sync_skill_resources.py. Do not edit manually.

from __future__ import annotations

from typing import Any


def analyze_economy(
    sources: list[dict[str, Any]],
    sinks: list[dict[str, Any]],
    *,
    max_positive_net: float = 0,
) -> dict[str, Any]:
    source_total = sum(float(item.get("amount", 0)) for item in sources)
    sink_total = sum(float(item.get("amount", 0)) for item in sinks)
    net_flow = source_total - sink_total
    return {
        "status": "FAIL" if net_flow > max_positive_net else "PASS",
        "source_total": source_total,
        "sink_total": sink_total,
        "net_flow": net_flow,
        "max_positive_net": max_positive_net,
        "sources": sources,
        "sinks": sinks,
        "limitations": ["Model uses the supplied period and does not infer player behavior."],
    }
