from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import unittest
from pathlib import Path

from tests._meta.support import temporary_directory, write_plugin_package


class DoctorTests(unittest.TestCase):
    def test_health_checks_disable_bytecode_and_leave_no_cache(self) -> None:
        from scripts.doctor import health

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            root = Path(temp)
            for directory in ("scripts", "skills", "registry", "personas", "evals"):
                shutil.copytree(source_root / directory, root / directory)
            write_plugin_package(root)
            subprocess.run(["git", "init", "-q"], cwd=root, check=True)

            result = health(root)

            self.assertEqual("PASS", result["status"])
            for check in result["checks"]:
                self.assertEqual("-B", check["command"][1])
            self.assertEqual([], list(root.rglob("__pycache__")))

    def test_installs_hook_and_invalid_skill_blocks_commit(self) -> None:
        from scripts.doctor import install_hook

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            root = Path(temp)
            git_environment = os.environ.copy()
            git_environment["GIT_CEILING_DIRECTORIES"] = str(root.parent)
            subprocess.run(
                ["git", "init"],
                cwd=root,
                env=git_environment,
                check=True,
                capture_output=True,
                text=True,
            )
            subprocess.run(["git", "config", "user.email", "test@example.invalid"], cwd=root, check=True)
            subprocess.run(["git", "config", "user.name", "Test User"], cwd=root, check=True)
            shutil.copytree(source_root / "scripts", root / "scripts")
            (root / "skills" / "broken").mkdir(parents=True)
            (root / "skills" / "broken" / "SKILL.md").write_text("---\nname: wrong\n---\n", encoding="utf-8")
            install_hook(root, python_executable=sys.executable)
            hook = root / ".git" / "hooks" / "pre-commit"
            self.assertTrue(hook.exists())
            self.assertIn('[sys.executable, "-B",', hook.read_text(encoding="utf-8"))
            subprocess.run(["git", "add", "."], cwd=root, check=True)
            result = subprocess.run(
                ["git", "commit", "-m", "invalid skill"],
                cwd=root,
                capture_output=True,
                text=True,
            )
            self.assertNotEqual(0, result.returncode)
            count = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"],
                cwd=root,
                capture_output=True,
                text=True,
            )
            self.assertNotEqual(0, count.returncode)

    def test_adapter_install_and_uninstall_preserve_project_local_skills(self) -> None:
        from scripts.doctor import install_adapter, uninstall_adapter

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp)
            local_skill = project / ".agents" / "skills" / "project-memory" / "SKILL.md"
            local_skill.parent.mkdir(parents=True)
            local_skill.write_text("local-owned\n", encoding="utf-8")
            install_adapter(source_root, "per-project", project)
            generated = project / ".agents" / "skills" / "studio-project-intake" / "SKILL.md"
            self.assertTrue(generated.exists())
            removed = uninstall_adapter(project)
            self.assertIn("studio-project-intake", removed)
            self.assertFalse(generated.exists())
            self.assertEqual("local-owned\n", local_skill.read_text(encoding="utf-8"))

    def test_adapter_uninstall_does_not_trust_marker_substrings(self) -> None:
        from scripts.doctor import install_adapter, uninstall_adapter

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp)
            install_adapter(source_root, "per-project", project)
            local_skill = project / ".agents" / "skills" / "local-notes" / "SKILL.md"
            local_skill.parent.mkdir(parents=True)
            local_skill.write_text(
                "Local notes mention Generated by scripts/generate_adapters.py. Do not edit manually.\n",
                encoding="utf-8",
            )
            removed = uninstall_adapter(project)
            self.assertNotIn("local-notes", removed)
            self.assertTrue(local_skill.exists())

    def test_adapter_uninstall_refuses_to_remove_drifted_generated_skill(self) -> None:
        from scripts.doctor import install_adapter, uninstall_adapter

        source_root = Path(__file__).resolve().parents[2]
        with temporary_directory() as temp:
            project = Path(temp)
            install_adapter(source_root, "per-project", project)
            generated = project / ".agents" / "skills" / "studio-project-intake" / "SKILL.md"
            generated.write_text(generated.read_text(encoding="utf-8") + "local drift\n", encoding="utf-8")
            removed = uninstall_adapter(project)
            self.assertNotIn("studio-project-intake", removed)
            self.assertTrue(generated.exists())
            registry = json.loads((project / ".agents" / "registry.json").read_text(encoding="utf-8"))
            remaining = registry["kit_adapter"]["files"]
            self.assertEqual(
                [".agents/skills/studio-project-intake/SKILL.md"],
                [entry["path"] for entry in remaining],
            )


if __name__ == "__main__":
    unittest.main()
