from __future__ import annotations

import os
import re
import stat
from pathlib import Path, PurePosixPath
from typing import Any

try:
    from scripts.common import load_yaml
    from scripts.generated_resources import (
        CapturedSource as _CapturedSource,
        render_generated_resource,
    )
except ModuleNotFoundError:
    from common import load_yaml
    from generated_resources import (
        CapturedSource as _CapturedSource,
        render_generated_resource,
    )


MARKER = "Generated by scripts/generate_adapters.py. Do not edit manually."
_SYNC_RESOURCE_JSON_COMMENT = (
    "Generated by scripts/sync_skill_resources.py. Do not edit manually."
)
_SAFE_COMPONENT = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def _is_reparse_point(path: Path) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    attributes = getattr(info, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return path.is_symlink() or bool(attributes & reparse_flag)

def _generated_resource(source: Path | _CapturedSource) -> str:
    return render_generated_resource(
        source,
        marker=MARKER,
        accepted_json_comments=(_SYNC_RESOURCE_JSON_COMMENT,),
    )

def _assert_no_reparse_path(path: Path) -> None:
    absolute = Path(os.path.abspath(str(path)))
    for candidate in [*list(absolute.parents)[::-1], absolute]:
        if _is_reparse_point(candidate):
            raise ValueError(f"symlink or reparse point is not allowed: {candidate}")

def _safe_component(value: object, label: str) -> str:
    if not isinstance(value, str) or _SAFE_COMPONENT.fullmatch(value) is None:
        raise ValueError(f"unsafe {label}: {value}")
    return value

def _stat_identity(info: os.stat_result) -> tuple[int, int, int, int, int, int]:
    return (
        info.st_dev,
        info.st_ino,
        info.st_mode,
        info.st_size,
        info.st_mtime_ns,
        info.st_ctime_ns,
    )

def _listing_identity(info: os.stat_result) -> tuple[int, int, int, int]:
    return (info.st_mode, info.st_size, info.st_mtime_ns, info.st_ctime_ns)

def _is_reparse_info(info: os.stat_result) -> bool:
    attributes = getattr(info, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return bool(attributes & reparse_flag)

def _capture_source_file(path: Path, expected: os.stat_result) -> _CapturedSource:
    if _is_reparse_info(expected) or not stat.S_ISREG(expected.st_mode):
        raise ValueError(f"source file is not a safe regular file: {path}")
    flags = os.O_RDONLY | getattr(os, "O_BINARY", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise ValueError(f"source file changed during capture: {path}") from error
    try:
        opened_before = os.fstat(descriptor)
        path_before = path.lstat()
        if (
            _is_reparse_info(path_before)
            or _listing_identity(expected) != _listing_identity(path_before)
            or _stat_identity(opened_before) != _stat_identity(path_before)
        ):
            raise ValueError(f"source file changed during capture: {path}")
        with os.fdopen(descriptor, "rb", closefd=False) as stream:
            data = stream.read()
        opened_after = os.fstat(descriptor)
        path_after = path.lstat()
        if (
            _is_reparse_info(path_after)
            or _stat_identity(opened_before) != _stat_identity(opened_after)
            or _stat_identity(opened_after) != _stat_identity(path_after)
        ):
            raise ValueError(f"source file changed during capture: {path}")
    finally:
        os.close(descriptor)
    return _CapturedSource(path=path, data=data)

def _walk_adapter_files(
    path: Path,
    *,
    reject_empty_directories: bool,
    ignore_runtime_cache: bool = False,
) -> list[Path] | list[_CapturedSource]:
    _assert_no_reparse_path(path)
    if not path.is_dir():
        raise RuntimeError(f"adapter tree is not a directory: {path}")
    root_info = path.lstat()
    if _is_reparse_info(root_info) or not stat.S_ISDIR(root_info.st_mode):
        raise ValueError(f"adapter directory is not a safe real directory: {path}")
    files: list[Path] = []
    captured: list[_CapturedSource] = []
    pending = [(path, root_info)]
    while pending:
        current, queued_info = pending.pop()
        _assert_no_reparse_path(current)
        current_info = current.lstat()
        if (
            _is_reparse_info(current_info)
            or not stat.S_ISDIR(current_info.st_mode)
            or _stat_identity(current_info) != _stat_identity(queued_info)
        ):
            raise ValueError(f"adapter directory changed before scan: {current}")
        entries = list(os.scandir(current))
        # Windows traversal is not directory-handle-bound, so fail closed on lexical drift.
        _assert_no_reparse_path(current)
        post_scan_info = current.lstat()
        if (
            _is_reparse_info(post_scan_info)
            or not stat.S_ISDIR(post_scan_info.st_mode)
            or _stat_identity(post_scan_info) != _stat_identity(queued_info)
        ):
            raise ValueError(f"adapter directory changed during scan: {current}")
        if not entries and current != path and reject_empty_directories:
            raise RuntimeError(f"refusing to replace unmanaged adapter directory: {current}")
        for entry in entries:
            candidate = Path(entry.path)
            info = entry.stat(follow_symlinks=False)
            attributes = getattr(info, "st_file_attributes", 0)
            reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
            if entry.is_symlink() or bool(attributes & reparse_flag):
                raise ValueError(f"symlink or reparse point is not allowed: {candidate}")
            _assert_no_reparse_path(candidate)
            candidate_info = candidate.lstat()
            if _is_reparse_info(candidate_info):
                raise ValueError(f"symlink or reparse point is not allowed: {candidate}")
            if entry.is_dir(follow_symlinks=False):
                if ignore_runtime_cache and entry.name == "__pycache__":
                    continue
                queued_candidate = candidate.lstat()
                if (
                    _is_reparse_info(queued_candidate)
                    or not stat.S_ISDIR(queued_candidate.st_mode)
                ):
                    raise ValueError(f"adapter directory changed while queued: {candidate}")
                pending.append((candidate, queued_candidate))
            elif entry.is_file(follow_symlinks=False):
                if not stat.S_ISREG(candidate_info.st_mode):
                    raise ValueError(f"adapter file changed while scanned: {candidate}")
                if ignore_runtime_cache and candidate.suffix.casefold() == ".pyc":
                    continue
                if ignore_runtime_cache:
                    captured.append(_capture_source_file(candidate, info))
                else:
                    files.append(candidate)
            else:
                raise RuntimeError(f"unsupported adapter tree entry: {candidate}")
    if ignore_runtime_cache:
        return sorted(captured, key=lambda item: item.path.relative_to(path).as_posix())
    return sorted(files, key=lambda item: item.relative_to(path).as_posix())

def _skill_files(skill_file: Path) -> list[_CapturedSource]:
    if not skill_file.is_file() or _is_reparse_point(skill_file):
        raise ValueError(f"capability SKILL.md is missing or unsafe: {skill_file}")
    captured = _walk_adapter_files(
        skill_file.parent,
        reject_empty_directories=False,
        ignore_runtime_cache=True,
    )
    assert all(isinstance(source, _CapturedSource) for source in captured)
    return captured

def _validated_capability(root: Path, capability: object) -> dict[str, Any]:
    if not isinstance(capability, dict):
        raise ValueError("capability registry entries must be objects")
    capability_id = _safe_component(capability.get("id"), "capability id")
    raw_path = capability.get("path")
    if not isinstance(raw_path, str):
        raise ValueError(f"capability {capability_id} path must be a string")
    normalized = raw_path.replace("\\", "/")
    raw_parts = normalized.split("/")
    pure = PurePosixPath(normalized)
    parts = pure.parts
    if (
        pure.is_absolute()
        or not parts
        or any(part in {"", ".", ".."} for part in raw_parts)
        or ".." in parts
        or "." in parts
        or parts[0] != "skills"
    ):
        raise ValueError(
            f"capability {capability_id} path is outside canonical skills: {raw_path}"
        )
    if len(parts) < 3 or parts[-1] != "SKILL.md":
        raise ValueError(f"capability {capability_id} path must name a canonical SKILL.md")
    for component in parts[1:-1]:
        _safe_component(component, "capability path component")
    root_path = root.resolve()
    skills_root = root_path / "skills"
    candidate = root_path.joinpath(*parts)
    _assert_no_reparse_path(skills_root)
    _assert_no_reparse_path(candidate)
    try:
        candidate.resolve().relative_to(skills_root.resolve())
    except ValueError as error:
        raise ValueError(
            f"capability {capability_id} path is outside canonical skills: {raw_path}"
        ) from error
    if not candidate.is_file():
        raise ValueError(f"capability {capability_id} SKILL.md is missing: {candidate}")
    validated = dict(capability)
    validated["id"] = capability_id
    validated["path"] = PurePosixPath(*parts).as_posix()
    return validated

def _capabilities(root: Path) -> list[dict[str, Any]]:
    registry = load_yaml(root / "registry" / "capabilities.yaml")
    capabilities = registry.get("capabilities", [])
    if not isinstance(capabilities, list):
        raise ValueError("capability registry capabilities must be a list")
    validated = [_validated_capability(root, capability) for capability in capabilities]
    capability_ids = [capability["id"] for capability in validated]
    if len(set(capability_ids)) != len(capability_ids):
        raise ValueError("capability registry contains duplicate capability ids")
    return validated
