from __future__ import annotations

import hashlib
import json
import re
import stat
import tomllib
import unicodedata
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, Iterable

try:
    from scripts.project_profile import load_project_profile
except ModuleNotFoundError:
    from project_profile import load_project_profile


MARKER = "Generated by scripts/generate_adapters.py. Do not edit manually."
ROLE_ID_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
REQUIRED_TEMPLATE_FIELDS = ("name", "description", "developer_instructions")
WINDOWS_FORBIDDEN_ROLE_CHARACTERS = set('<>:"|?*')
RESERVED_WINDOWS_BASENAMES = {
    "con",
    "prn",
    "aux",
    "nul",
    "conin$",
    "conout$",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
}
RESERVED_NUMBERED_WINDOWS_BASENAME = re.compile(
    r"^(?:com|lpt)(?:[1-9¹²³])$",
    re.IGNORECASE,
)


def _validate_role_id(value: object, *, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"invalid {label} role id: {value}")
    basename = value.split(".", 1)[0].rstrip(" .").casefold()
    if (
        "/" in value
        or "\\" in value
        or value.endswith((".", " "))
        or any(character in WINDOWS_FORBIDDEN_ROLE_CHARACTERS for character in value)
        or any(unicodedata.category(character) == "Cc" for character in value)
        or basename in RESERVED_WINDOWS_BASENAMES
        or RESERVED_NUMBERED_WINDOWS_BASENAME.fullmatch(basename)
        or ROLE_ID_PATTERN.fullmatch(value) is None
    ):
        raise ValueError(f"invalid {label} role id: {value}")
    return value


def _has_generated_header(text: str) -> bool:
    lines = text.splitlines()
    return bool(lines) and lines[0] == f"# {MARKER}"


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _is_reparse_point(path: Path) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    attributes = getattr(info, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return path.is_symlink() or bool(attributes & reparse_flag)


def _safe_project_path(project: Path, relative: str) -> Path:
    normalized = relative.replace("\\", "/")
    pure = PurePosixPath(normalized)
    windows = PureWindowsPath(relative)
    parts = pure.parts
    is_agent_root = parts == (".codex", "agents")
    is_agent = len(parts) == 3 and parts[:2] == (".codex", "agents")
    is_activation = parts == (".codex", "agents.generated.toml")
    if (
        pure.is_absolute()
        or windows.is_absolute()
        or windows.drive
        or not parts
        or "." in parts
        or ".." in parts
        or not (is_agent_root or is_agent or is_activation)
    ):
        raise ValueError(f"unsafe agent overlay path: {relative}")

    project_root = project.resolve()
    candidate = project_root.joinpath(*parts)
    current = project_root
    if _is_reparse_point(current):
        raise ValueError(f"project root is a symlink or reparse point: {current}")
    for part in parts:
        current = current / part
        if current.exists() and _is_reparse_point(current):
            raise ValueError(f"symlink or reparse point is not allowed: {current}")

    owned_root = project_root / ".codex"
    resolved = candidate.resolve()
    try:
        resolved.relative_to(owned_root.resolve())
    except ValueError as error:
        raise ValueError(f"agent overlay path escapes its owned scope: {relative}") from error
    return candidate


def _load_generic_roles(template_root: Path) -> list[dict[str, str]]:
    roles: list[dict[str, str]] = []
    role_ids: set[str] = set()
    for template in template_root.glob("*.toml"):
        content = template.read_text(encoding="utf-8")
        parsed = tomllib.loads(content)
        role_id = _validate_role_id(parsed.get("name"), label="generic")
        if role_id in role_ids:
            raise ValueError(f"duplicate generic role id: {role_id}")
        role_ids.add(role_id)
        for field in REQUIRED_TEMPLATE_FIELDS:
            value = parsed.get(field)
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"generic role {role_id} requires {field}")
        roles.append(
            {
                "id": role_id,
                "description": parsed["description"],
                "content": f"# {MARKER}\n\n{content}",
            }
        )
    return sorted(roles, key=lambda role: role["id"])


def _activation_text(roles: list[dict[str, str]]) -> str:
    lines = [f"# {MARKER}", ""]
    for role in roles:
        role_id = role["id"]
        lines.extend(
            [
                f"[agents.{role_id}]",
                f"description = {json.dumps(role['description'])}",
                f"config_file = {json.dumps(f'./agents/{role_id}.toml')}",
                "",
            ]
        )
    return "\n".join(lines)


def _unmanaged_agent_paths(
    project: Path,
    *,
    planned_paths: set[str],
) -> list[str]:
    agents_root = _safe_project_path(project, ".codex/agents")
    if not agents_root.exists():
        return []
    preserved: list[str] = []
    for candidate in sorted(agents_root.iterdir(), key=lambda path: path.name):
        if _is_reparse_point(candidate) or not candidate.is_file():
            continue
        if candidate.suffix.casefold() != ".toml":
            continue
        relative = PurePosixPath(".codex", "agents", candidate.name).as_posix()
        if relative in planned_paths:
            continue
        existing = candidate.read_text(encoding="utf-8", errors="replace")
        if not _has_generated_header(existing):
            preserved.append(relative)
    return preserved


def _specialist_role(
    specialist: dict[str, Any],
    repository: dict[str, Any],
) -> dict[str, str]:
    role_id = str(specialist["id"])
    repository_id = str(repository["id"])
    repository_path = str(repository["path"])
    constraints = [str(item) for item in specialist["constraints"]]
    instructions = [
        f"Own only repository {repository_id} at {repository_path} and the exact files assigned by the main thread.",
        "Preserve project-profile ownership, validation, generated-file, and do-not-touch rules.",
        *constraints,
        "Do not revert concurrent edits, expand into sibling repositories, or create child agents.",
        "Return changed paths, commands, exit codes, artifacts, and remaining rollout risk.",
    ]
    description = f"Project specialist for {repository_id} ({repository_path})."
    content = "\n".join(
        [
            f"# {MARKER}",
            "",
            f"name = {json.dumps(role_id)}",
            f"description = {json.dumps(description)}",
            f"model_reasoning_effort = '{specialist['reasoning_effort']}'",
            "sandbox_mode = 'workspace-write'",
            f"developer_instructions = {json.dumps(chr(10).join(instructions))}",
            "",
        ]
    )
    return {"id": role_id, "description": description, "content": content}


def plan_agent_overlay(
    project: Path | str,
    *,
    template_root: Path | str,
    profile_path: Path | str | None = None,
    known_skills: Iterable[str] = (),
) -> dict[str, object]:
    project_path = Path(project)
    generic_roles = _load_generic_roles(Path(template_root))
    roles = list(generic_roles)
    generic_role_ids = {role["id"] for role in generic_roles}
    if profile_path is not None and Path(profile_path).is_file():
        profile = load_project_profile(profile_path, known_skills=known_skills)
        repositories = {
            str(repository["id"]): repository for repository in profile["repositories"]
        }
        for specialist in profile.get("agents", {}).get("specialists", []):
            specialist_id = _validate_role_id(specialist.get("id"), label="specialist")
            if specialist_id in generic_role_ids:
                raise ValueError(f"specialist id collides with generic role: {specialist_id}")
            repository = repositories[str(specialist["repository"])]
            roles.append(_specialist_role(specialist, repository))
    roles.sort(key=lambda role: role["id"])
    operations: list[dict[str, str]] = []
    planned_paths = {
        PurePosixPath(".codex", "agents", f"{role['id']}.toml").as_posix()
        for role in roles
    }
    preserved = _unmanaged_agent_paths(project_path, planned_paths=planned_paths)
    collisions: list[dict[str, str]] = []
    managed_roles: list[dict[str, str]] = []

    for role in roles:
        relative = PurePosixPath(".codex", "agents", f"{role['id']}.toml").as_posix()
        destination = _safe_project_path(project_path, relative)
        existing = destination.read_text(encoding="utf-8", errors="replace") if destination.exists() else ""
        if destination.exists() and not _has_generated_header(existing):
            preserved.append(relative)
            collisions.append({"path": relative, "kind": "unmanaged-agent", "role_id": role["id"]})
            continue
        operations.append({"path": relative, "content": role["content"]})
        managed_roles.append(role)

    activation_relative = ".codex/agents.generated.toml"
    activation_destination = _safe_project_path(project_path, activation_relative)
    activation_existing = (
        activation_destination.read_text(encoding="utf-8", errors="replace")
        if activation_destination.exists()
        else ""
    )
    activated_roles: list[str] = []
    if activation_destination.exists() and not _has_generated_header(activation_existing):
        preserved.append(activation_relative)
        collisions.append({"path": activation_relative, "kind": "unmanaged-activation"})
    else:
        operations.append(
            {"path": activation_relative, "content": _activation_text(managed_roles)}
        )
        activated_roles = [role["id"] for role in managed_roles]

    operations.sort(key=lambda operation: operation["path"])
    return {
        "operations": operations,
        "preserved": sorted(preserved),
        "collisions": sorted(collisions, key=lambda collision: collision["path"]),
        "owned_files": [
            {"path": operation["path"], "sha256": _sha256_text(operation["content"])}
            for operation in operations
        ],
        "activated_roles": activated_roles,
    }
