from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

try:
    from scripts.common import load_yaml, parse_frontmatter
    from scripts.route_eval import evaluate_repository
    from scripts.validate import validate_repository
except ModuleNotFoundError:
    from common import load_yaml, parse_frontmatter
    from route_eval import evaluate_repository
    from validate import validate_repository


RUNNER_STATUS_FIELDS = {
    "verdict",
    "runner",
    "validation_command",
    "exit_code",
    "observed_cases",
    "passed",
    "pass_rate",
    "unique_ids",
    "covered_skills",
    "timestamp",
}
GENERATED_MARKER = "Generated by scripts/catalog_audit.py. Do not edit manually."


def _ratio(passed: int, total: int) -> float | None:
    return passed / total if total else None


def _status_filename(kind: str) -> str:
    return "tier-b-status.json" if kind == "tier-b" else f"{kind}-status.json"


def _validate_runner_status(payload: dict[str, Any], kind: str) -> dict[str, Any]:
    if payload.get("verdict") == "BLOCKED":
        result = dict(payload)
        result.setdefault("kind", kind)
        result.setdefault("reasons", [str(payload.get("reason", "runner unavailable"))])
        return result
    missing = sorted(RUNNER_STATUS_FIELDS - set(payload))
    reasons: list[str] = []
    if missing:
        reasons.append(f"missing runner status fields: {missing}")
    if payload.get("verdict") != "PASS":
        reasons.append("runner verdict is not PASS")
    if not isinstance(payload.get("runner"), str) or not payload.get("runner"):
        reasons.append("runner is required")
    if not isinstance(payload.get("validation_command"), str) or not payload.get("validation_command"):
        reasons.append("validation_command is required")
    if payload.get("exit_code") != 0:
        reasons.append("runner exit_code must be 0")
    observed = payload.get("observed_cases")
    passed = payload.get("passed")
    unique_ids = payload.get("unique_ids")
    if not isinstance(observed, int) or observed <= 0:
        reasons.append("observed_cases must be a positive integer")
    if passed != observed:
        reasons.append("passed must equal observed_cases")
    if unique_ids != observed:
        reasons.append("unique_ids must equal observed_cases")
    if payload.get("pass_rate") != 1.0:
        reasons.append("pass_rate must be 1.0 for PASS")
    covered = payload.get("covered_skills")
    if (
        not isinstance(covered, list)
        or not covered
        or any(not isinstance(skill, str) or not skill for skill in covered)
    ):
        reasons.append("covered_skills requires non-empty skill ids")
    try:
        datetime.fromisoformat(str(payload.get("timestamp")))
    except ValueError:
        reasons.append("timestamp must be ISO-8601")
    if reasons:
        return {
            "verdict": "BLOCKED",
            "kind": kind,
            "reasons": reasons,
            "source_verdict": payload.get("verdict"),
        }
    result = dict(payload)
    result["kind"] = kind
    result["covered_skills"] = sorted(set(covered))
    return result


def _runner_status(root: Path, kind: str) -> dict[str, Any]:
    evidence = root / "evidence"
    candidates = sorted(evidence.rglob(_status_filename(kind))) if evidence.exists() else []
    if not candidates:
        return {
            "verdict": "BLOCKED",
            "kind": kind,
            "reasons": [f"No {_status_filename(kind)} artifact exists"],
        }
    try:
        payload = json.loads(candidates[-1].read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return {"verdict": "BLOCKED", "kind": kind, "reasons": [str(error)]}
    if not isinstance(payload, dict):
        return {"verdict": "BLOCKED", "kind": kind, "reasons": ["status must be an object"]}
    result = _validate_runner_status(payload, kind)
    result["path"] = candidates[-1].relative_to(root).as_posix()
    return result


def audit_session_history(payload: dict[str, Any]) -> dict[str, Any]:
    entries = payload.get("entries")
    if not isinstance(entries, list) or not entries:
        return {
            "status": "BLOCKED",
            "findings": [],
            "kpis": {
                "pass_with_evidence": None,
                "unauthorized_writes": None,
                "retry_over_three_without_escalation": None,
            },
            "reasons": ["session history requires at least one entry"],
        }
    findings: list[dict[str, Any]] = []
    patterns: Counter[str] = Counter()
    passes_with_evidence = 0
    unauthorized_writes = 0
    retry_violations = 0
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            findings.append({"kind": "invalid-history-entry", "entry": index})
            continue
        pattern = str(entry.get("manual_pattern") or "").strip()
        if pattern:
            patterns[pattern] += 1
        if entry.get("outcome") == "PASS" and entry.get("evidence_label") == "Verified":
            passes_with_evidence += 1
        if entry.get("unauthorized_write") is True:
            unauthorized_writes += 1
            findings.append({"kind": "unauthorized-write", "entry": index})
        retry_count = entry.get("retry_count")
        if isinstance(retry_count, int) and retry_count > 3:
            retry_violations += 1
            findings.append(
                {"kind": "retry-over-three", "entry": index, "retry_count": retry_count}
            )
    for pattern, count in sorted(patterns.items()):
        if count >= 2:
            findings.append(
                {"kind": "repeated-manual-workflow", "pattern": pattern, "count": count}
            )
    return {
        "status": "PASS",
        "entries": len(entries),
        "findings": findings,
        "kpis": {
            "pass_with_evidence": passes_with_evidence / len(entries),
            "unauthorized_writes": unauthorized_writes,
            "retry_over_three_without_escalation": retry_violations,
        },
    }


def _history_report(history_path: Path | str | None) -> dict[str, Any]:
    if history_path is None:
        return {
            "status": "BLOCKED",
            "findings": [],
            "kpis": {
                "pass_with_evidence": None,
                "unauthorized_writes": None,
                "retry_over_three_without_escalation": None,
            },
            "reasons": ["No sanitized session history was supplied"],
        }
    try:
        payload = json.loads(Path(history_path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return {
            "status": "BLOCKED",
            "findings": [],
            "kpis": {
                "pass_with_evidence": None,
                "unauthorized_writes": None,
                "retry_over_three_without_escalation": None,
            },
            "reasons": [str(error)],
        }
    return audit_session_history(payload if isinstance(payload, dict) else {})


def audit_catalog(
    root: Path | str, history_path: Path | str | None = None
) -> dict[str, Any]:
    root_path = Path(root).resolve()
    validation = validate_repository(root_path)
    routing = evaluate_repository(root_path)
    tier_b = _runner_status(root_path, "tier-b")
    behavior = _runner_status(root_path, "behavior")
    pressure = _runner_status(root_path, "pressure")
    history = _history_report(history_path)
    registry = load_yaml(root_path / "registry" / "capabilities.yaml")
    stale: list[str] = []
    premature: list[str] = []
    cutoff = date.today() - timedelta(days=90)
    runner_ready = all(
        status.get("verdict") == "PASS" for status in (tier_b, behavior, pressure)
    )
    covered_by_kind = {
        status["kind"]: set(status.get("covered_skills", []))
        for status in (tier_b, behavior, pressure)
    }
    for capability in registry.get("capabilities", []):
        skill_path = root_path / capability["path"]
        if not skill_path.exists():
            continue
        frontmatter, _ = parse_frontmatter(skill_path)
        studio = frontmatter["metadata"]["studio"]
        reviewed = studio["last_reviewed"]
        reviewed_date = (
            datetime.strptime(reviewed, "%Y-%m-%d").date()
            if isinstance(reviewed, str)
            else reviewed
        )
        if reviewed_date < cutoff:
            stale.append(capability["id"])
        if capability["maturity"] in {"beta", "stable"} and not runner_ready:
            premature.append(capability["id"])

    validation_errors = len([issue for issue in validation if issue.severity == "error"])
    deterministic_ready = validation_errors == 0 and not routing.failures
    dogfood_summaries = (
        sorted((root_path / "evidence").rglob("dogfood-summary.json"))
        if (root_path / "evidence").exists()
        else []
    )
    verified_dogfood_summaries: list[Path] = []
    verified_workflows: set[str] = set()
    for summary_path in dogfood_summaries:
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        workflow = summary.get("workflow")
        if (
            summary.get("label") == "Verified"
            and summary.get("exit_code") == 0
            and isinstance(workflow, str)
            and workflow
        ):
            verified_dogfood_summaries.append(summary_path)
            verified_workflows.add(workflow)

    promotion_ready: list[str] = []
    if deterministic_ready and runner_ready:
        promotion_ready = [
            capability["id"]
            for capability in registry.get("capabilities", [])
            if capability["maturity"] in {"draft", "experimental"}
            and capability["id"] in verified_workflows
            and all(
                capability["id"] in covered_by_kind[kind]
                for kind in ("tier-b", "behavior", "pressure")
            )
        ]

    history_kpis = history["kpis"]
    kpis = {
        "routing_rank_1": {
            "observed": _ratio(routing.passed, routing.total),
            "target_mvp": 0.85,
            "target_stable": 0.90,
        },
        "behavioral": {
            "observed": behavior.get("pass_rate") if behavior.get("verdict") == "PASS" else None,
            "target_mvp": 0.80,
            "target_stable": 0.90,
        },
        "pressure": {
            "observed": pressure.get("pass_rate") if pressure.get("verdict") == "PASS" else None,
            "target": 1.0,
        },
        "pass_with_evidence": {
            "observed": history_kpis["pass_with_evidence"],
            "target": 1.0,
        },
        "unauthorized_writes": {
            "observed": history_kpis["unauthorized_writes"],
            "target": 0,
        },
        "retry_over_three_without_escalation": {
            "observed": history_kpis["retry_over_three_without_escalation"],
            "target": 0,
        },
    }
    status_reasons: list[str] = []
    if not deterministic_ready:
        status_reasons.append("deterministic validation or routing failed")
    if premature:
        status_reasons.append("one or more skills have premature maturity")
    for runner_status in (tier_b, behavior, pressure):
        if runner_status.get("verdict") != "PASS":
            status_reasons.append(f"{runner_status['kind']} evidence is BLOCKED")
    if history.get("status") != "PASS":
        status_reasons.append("session history is BLOCKED")
    operational_values = (
        history_kpis["pass_with_evidence"],
        history_kpis["unauthorized_writes"],
        history_kpis["retry_over_three_without_escalation"],
    )
    if any(value is None for value in operational_values):
        status_reasons.append("operational KPI observations are incomplete")

    if not deterministic_ready or premature:
        status = "FAIL"
    elif status_reasons:
        status = "BLOCKED"
    else:
        status = "PASS"
    return {
        "_generated": GENERATED_MARKER,
        "status": status,
        "status_reasons": status_reasons,
        "deterministic_gates": {
            "validation_errors": validation_errors,
            "routing_failures": len(routing.failures),
        },
        "tier_b": tier_b,
        "behavior": behavior,
        "pressure": pressure,
        "session_history": history,
        "history_findings": history["findings"],
        "stale_skills": sorted(stale),
        "premature_maturity": sorted(premature),
        "promotion_ready": sorted(promotion_ready),
        "dogfood_summaries": [path.relative_to(root_path).as_posix() for path in dogfood_summaries],
        "verified_dogfood_summaries": [
            path.relative_to(root_path).as_posix() for path in verified_dogfood_summaries
        ],
        "kpis": kpis,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Audit catalog lifecycle and observed-versus-target KPIs.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--history", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    report = audit_catalog(Path(args.root), history_path=args.history)
    text = json.dumps(report, indent=2)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    print(text)
    if report["status"] == "PASS":
        return 0
    return 2 if report["status"] == "BLOCKED" else 1


if __name__ == "__main__":
    sys.exit(main())
