from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter
from datetime import date, datetime, timedelta, timezone
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any

try:
    from scripts.common import load_yaml, parse_frontmatter
    from scripts.dogfood_eval import load_profile
    from scripts.promotion_evidence import load_promotion_records, validate_promotion_record
    from scripts.release_preflight import load_release_preflight_schema
    from scripts.route_eval import evaluate_repository
    from scripts.validate import validate_repository
except ModuleNotFoundError:
    from common import load_yaml, parse_frontmatter
    from dogfood_eval import load_profile
    from promotion_evidence import load_promotion_records, validate_promotion_record
    from release_preflight import load_release_preflight_schema
    from route_eval import evaluate_repository
    from validate import validate_repository


RUNNER_STATUS_FIELDS = {
    "verdict",
    "runner",
    "validation_command",
    "exit_code",
    "observed_cases",
    "passed",
    "pass_rate",
    "unique_ids",
    "covered_skills",
    "timestamp",
    "input_digest",
}
RUNNER_INPUT_SCRIPTS = (
    "behavior_eval.py",
    "catalog_audit.py",
    "common.py",
    "context_brief.py",
    "goal_progress_core.py",
    "pressure_eval.py",
    "route_eval.py",
    "runner_eval.py",
    "studio_experience.py",
    "tier_b_eval.py",
)
GENERATED_MARKER = "Generated by scripts/catalog_audit.py. Do not edit manually."
DOGFOOD_FIELDS = {
    "label",
    "workflow",
    "case_id",
    "exit_code",
    "command",
    "artifact_root",
    "artifacts",
    "project_snapshot",
    "reviewer",
    "timestamp",
    "unauthorized_write",
    "restore",
}


def _ratio(passed: int, total: int) -> float | None:
    return passed / total if total else None


def _status_filename(kind: str) -> str:
    return "tier-b-status.json" if kind == "tier-b" else f"{kind}-status.json"


def runner_input_digest(root: Path) -> str:
    """Bind a governed run to catalog, shipped resources and evaluation inputs.

    Capture before running a model and compare again afterwards. Evidence outputs
    are deliberately excluded; never retrofit this digest onto historical results.
    """
    root = root.resolve()
    paths = {root / "registry" / "capabilities.yaml"}
    for directory in ("skills", "evals"):
        paths.update(path for path in (root / directory).rglob("*") if path.is_file())
    paths.update(root / "scripts" / name for name in RUNNER_INPUT_SCRIPTS)
    digest = hashlib.sha256(b"catalog-runner-inputs-v1\0")
    for path in sorted(paths):
        if not path.is_file():
            continue
        if path.is_symlink() or not path.resolve().is_relative_to(root):
            raise ValueError("runner inputs must remain within the repository")
        digest.update(path.relative_to(root).as_posix().encode("utf-8") + b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
    return digest.hexdigest()


def _runner_timestamp(payload: dict[str, Any]) -> datetime:
    raw_timestamp = payload.get("timestamp")
    if not isinstance(raw_timestamp, str) or not raw_timestamp.strip():
        raise ValueError("missing runner timestamp")
    timestamp = datetime.fromisoformat(raw_timestamp)
    if timestamp.tzinfo is None or timestamp.utcoffset() is None:
        raise ValueError("runner timestamp requires a timezone")
    return timestamp.astimezone(timezone.utc)


def _validate_runner_status(payload: dict[str, Any], kind: str) -> dict[str, Any]:
    if payload.get("verdict") == "BLOCKED":
        result = dict(payload)
        result.setdefault("kind", kind)
        result.setdefault("reasons", [str(payload.get("reason", "runner unavailable"))])
        return result
    missing = sorted(RUNNER_STATUS_FIELDS - set(payload))
    reasons: list[str] = []
    if missing:
        reasons.append(f"missing runner status fields: {missing}")
    if payload.get("verdict") != "PASS":
        reasons.append("runner verdict is not PASS")
    if (
        not isinstance(payload.get("runner"), str)
        or not payload["runner"].strip()
    ):
        reasons.append("runner is required")
    if (
        not isinstance(payload.get("validation_command"), str)
        or not payload["validation_command"].strip()
    ):
        reasons.append("validation_command is required")
    if type(payload.get("exit_code")) is not int or payload["exit_code"] != 0:
        reasons.append("runner exit_code must be 0")
    observed = payload.get("observed_cases")
    passed = payload.get("passed")
    unique_ids = payload.get("unique_ids")
    if type(observed) is not int or observed <= 0:
        reasons.append("observed_cases must be a positive integer")
    if type(passed) is not int or passed != observed:
        reasons.append("passed must equal observed_cases")
    if type(unique_ids) is not int or unique_ids != observed:
        reasons.append("unique_ids must equal observed_cases")
    pass_rate = payload.get("pass_rate")
    if type(pass_rate) not in {int, float} or pass_rate != 1.0:
        reasons.append("pass_rate must be 1.0 for PASS")
    covered = payload.get("covered_skills")
    if (
        not isinstance(covered, list)
        or not covered
        or any(not isinstance(skill, str) or not skill.strip() for skill in covered)
    ):
        reasons.append("covered_skills requires non-empty skill ids")
    try:
        timestamp = _runner_timestamp(payload)
        age = datetime.now(timezone.utc) - timestamp
        if age < timedelta(0) or age > timedelta(days=90):
            reasons.append("runner evidence is future-dated or older than 90 days")
    except ValueError:
        reasons.append("timestamp must be ISO-8601")
    if reasons:
        return {
            "verdict": "BLOCKED",
            "kind": kind,
            "reasons": reasons,
            "source_verdict": payload.get("verdict"),
        }
    result = dict(payload)
    result["kind"] = kind
    result["covered_skills"] = sorted(set(covered))
    return result


def _runner_status(root: Path, kind: str) -> dict[str, Any]:
    evidence = root / "evidence"
    candidates = sorted(evidence.rglob(_status_filename(kind))) if evidence.exists() else []
    if not candidates:
        return {
            "verdict": "BLOCKED",
            "kind": kind,
            "reasons": [f"No {_status_filename(kind)} artifact exists"],
        }
    # Do not silently discard an unreadable run: it could be the latest failure.
    runs = []
    try:
        for path in candidates:
            payload = json.loads(path.read_text(encoding="utf-8"))
            if not isinstance(payload, dict):
                raise ValueError("status must be an object")
            runs.append((_runner_timestamp(payload), path, payload))
        runs.sort(key=lambda item: item[0], reverse=True)
        if len(runs) > 1 and runs[0][0] == runs[1][0]:
            raise ValueError("ambiguous runner runs: latest timestamps tie")
        timestamp, path, payload = runs[0]
        age = datetime.now(timezone.utc) - timestamp
        if age < timedelta(0) or age > timedelta(days=90):
            raise ValueError("runner evidence is future-dated or older than 90 days")
        if payload.get("input_digest") != runner_input_digest(root):
            raise ValueError("runner input_digest is missing or does not match current inputs")
    except (OSError, UnicodeError, ValueError) as error:
        return {"verdict": "BLOCKED", "kind": kind, "reasons": [str(error)]}
    if payload.get("verdict") == "FAIL":
        result = {
            "verdict": "FAIL",
            "kind": kind,
            "runner": payload.get("runner"),
            "reasons": ["latest bound runner run failed"],
        }
    else:
        result = _validate_runner_status(payload, kind)
    result["path"] = path.relative_to(root).as_posix()
    return result


def audit_session_history(payload: dict[str, Any]) -> dict[str, Any]:
    entries = payload.get("entries")
    if not isinstance(entries, list) or not entries:
        return {
            "status": "BLOCKED",
            "findings": [],
            "kpis": {
                "pass_with_evidence": None,
                "unauthorized_writes": None,
                "retry_over_three_without_escalation": None,
            },
            "reasons": ["session history requires at least one entry"],
        }
    findings: list[dict[str, Any]] = []
    patterns: Counter[str] = Counter()
    passes_with_evidence = 0
    unauthorized_writes = 0
    retry_violations = 0
    failed_entries = 0
    blocked_entries = 0
    unsupported_passes = 0
    for index, entry in enumerate(entries):
        required = {
            "timestamp",
            "workflow",
            "outcome",
            "evidence_label",
            "retry_count",
            "unauthorized_write",
            "manual_pattern",
        }
        if (
            not isinstance(entry, dict)
            or set(entry) != required
            or entry.get("outcome") not in {"PASS", "FAIL", "BLOCKED"}
            or entry.get("evidence_label")
            not in {"Verified", "Snapshot", "Unverified", "BLOCKED"}
            or type(entry.get("unauthorized_write")) is not bool
            or type(entry.get("retry_count")) is not int
            or entry["retry_count"] < 0
            or not isinstance(entry.get("workflow"), str)
            or not entry["workflow"].strip()
            or not isinstance(entry.get("manual_pattern"), str)
        ):
            findings.append({"kind": "invalid-history-entry", "entry": index})
            continue
        try:
            _runner_timestamp(entry)
        except (ValueError, TypeError):
            findings.append({"kind": "invalid-history-entry", "entry": index})
            continue
        pattern = str(entry.get("manual_pattern") or "").strip()
        if pattern:
            patterns[pattern] += 1
        outcome = entry["outcome"]
        evidence_label = entry["evidence_label"]
        if outcome == "PASS":
            if evidence_label == "Verified":
                passes_with_evidence += 1
            else:
                unsupported_passes += 1
                findings.append({"kind": "pass-without-verified-evidence", "entry": index})
        elif outcome == "FAIL":
            failed_entries += 1
            findings.append({"kind": "failed-history-entry", "entry": index})
        else:
            blocked_entries += 1
            findings.append({"kind": "blocked-history-entry", "entry": index})
        if entry.get("unauthorized_write") is True:
            unauthorized_writes += 1
            findings.append({"kind": "unauthorized-write", "entry": index})
        retry_count = entry.get("retry_count")
        if isinstance(retry_count, int) and retry_count > 3:
            retry_violations += 1
            findings.append(
                {"kind": "retry-over-three", "entry": index, "retry_count": retry_count}
            )
    for pattern, count in sorted(patterns.items()):
        if count >= 2:
            findings.append(
                {"kind": "repeated-manual-workflow", "pattern": pattern, "count": count}
            )
    invalid = any(item["kind"] == "invalid-history-entry" for item in findings)
    failed = bool(
        unauthorized_writes
        or retry_violations
        or failed_entries
        or unsupported_passes
    )
    blocked = bool(invalid or blocked_entries)
    return {
        "status": "FAIL" if failed else "BLOCKED" if blocked else "PASS",
        "entries": len(entries),
        "findings": findings,
        "kpis": {
            "pass_with_evidence": (
                None if blocked else passes_with_evidence / len(entries)
            ),
            "unauthorized_writes": None if invalid else unauthorized_writes,
            "retry_over_three_without_escalation": None if invalid else retry_violations,
        },
    }


def _history_report(history_path: Path | str | None) -> dict[str, Any]:
    if history_path is None:
        return {
            "status": "BLOCKED",
            "findings": [],
            "kpis": {
                "pass_with_evidence": None,
                "unauthorized_writes": None,
                "retry_over_three_without_escalation": None,
            },
            "reasons": ["No sanitized session history was supplied"],
        }
    try:
        payload = json.loads(Path(history_path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return {
            "status": "BLOCKED",
            "findings": [],
            "kpis": {
                "pass_with_evidence": None,
                "unauthorized_writes": None,
                "retry_over_three_without_escalation": None,
            },
            "reasons": [str(error)],
        }
    return audit_session_history(payload if isinstance(payload, dict) else {})


def _sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _valid_dogfood_summary(payload: Any) -> bool:
    if not isinstance(payload, dict) or not DOGFOOD_FIELDS.issubset(payload):
        return False
    if payload.get("label") != "Verified" or payload.get("exit_code") != 0:
        return False
    required_text = ("workflow", "case_id", "command", "project_snapshot", "reviewer", "restore")
    if not all(
        isinstance(payload.get(field), str) and payload[field].strip() for field in required_text
    ):
        return False
    if payload.get("unauthorized_write") is not False:
        return False
    artifact_root_value = payload.get("artifact_root")
    if not isinstance(artifact_root_value, str) or not artifact_root_value.strip():
        return False
    artifact_root = Path(artifact_root_value).resolve()
    if not artifact_root.is_dir():
        return False
    artifacts = payload.get("artifacts")
    if not isinstance(artifacts, list) or not artifacts:
        return False
    seen_kinds: set[str] = set()
    for item in artifacts:
        if (
            not isinstance(item, dict)
            or not isinstance(item.get("kind"), str)
            or not item["kind"].strip()
            or item["kind"] in seen_kinds
            or not isinstance(item.get("path"), str)
            or not item["path"].strip()
            or not isinstance(item.get("sha256"), str)
            or len(item["sha256"]) != 64
        ):
            return False
        seen_kinds.add(item["kind"])
        normalized = item["path"].replace("\\", "/")
        pure = PurePosixPath(normalized)
        windows = PureWindowsPath(item["path"])
        if (
            pure.is_absolute()
            or windows.is_absolute()
            or windows.drive
            or not pure.parts
            or "." in pure.parts
            or ".." in pure.parts
        ):
            return False
        artifact = artifact_root.joinpath(*pure.parts).resolve()
        try:
            artifact.relative_to(artifact_root)
        except ValueError:
            return False
        if not artifact.is_file() or _sha256_path(artifact) != item["sha256"]:
            return False
    try:
        datetime.fromisoformat(str(payload.get("timestamp")))
    except ValueError:
        return False
    return True


def _promotion_evidence_audit(
    root: Path, capabilities: list[dict[str, Any]]
) -> dict[str, list[str]]:
    report = {"verified": [], "stale": [], "invalid": [], "unsupported": []}
    registry_path = root / "registry" / "promotion-evidence.yaml"
    if not registry_path.is_file():
        return report
    try:
        records = load_promotion_records(registry_path)
    except (OSError, ValueError):
        return {"verified": [], "stale": [], "invalid": ["<registry>"], "unsupported": []}

    profile_cases: dict[str, set[str]] = {}
    for profile_path in sorted((root / "evals" / "dogfood" / "profiles").glob("*.json")):
        try:
            profile_cases[profile_path.stem] = set(load_profile(root, profile_path.stem)["case_ids"])
        except (OSError, ValueError):
            continue
    known_skills = {
        str(capability.get("id"))
        for capability in capabilities
        if isinstance(capability.get("id"), str) and capability.get("id")
    }
    maturity_by_skill = {
        str(capability.get("id")): capability.get("maturity")
        for capability in capabilities
    }
    today = date.today()
    for index, record in enumerate(records):
        record_id = str(record.get("id") or f"record-{index}")
        errors = validate_promotion_record(
            record,
            known_skills=known_skills,
            known_profiles=profile_cases,
            profile_cases=profile_cases,
            artifact_root=root,
            repository_root=root,
        )
        if errors:
            report["invalid"].append(record_id)
            continue
        try:
            expires_at = date.fromisoformat(str(record["expires_at"]))
        except ValueError:
            report["invalid"].append(record_id)
            continue
        skill_id = str(record["skill_id"])
        target = str(record["target_maturity"])
        if expires_at < today:
            report["stale"].append(record_id)
        elif maturity_by_skill.get(skill_id) != target:
            report["unsupported"].append(record_id)
        else:
            report["verified"].append(record_id)
    return {key: sorted(value) for key, value in report.items()}


def audit_catalog(
    root: Path | str, history_path: Path | str | None = None
) -> dict[str, Any]:
    root_path = Path(root).resolve()
    validation = validate_repository(root_path)
    routing = evaluate_repository(root_path)
    tier_b = _runner_status(root_path, "tier-b")
    behavior = _runner_status(root_path, "behavior")
    pressure = _runner_status(root_path, "pressure")
    history = _history_report(history_path)
    registry = load_yaml(root_path / "registry" / "capabilities.yaml")
    capabilities = registry.get("capabilities", []) if isinstance(registry, dict) else []
    release_schema = {"verdict": "NOT_APPLICABLE", "path": None, "reason": None}
    if any(capability.get("id") == "release-candidate-preflight" for capability in capabilities):
        release_schema_path = root_path / "evals" / "schema" / "release-preflight.schema.json"
        release_schema["path"] = release_schema_path.relative_to(root_path).as_posix()
        try:
            load_release_preflight_schema(release_schema_path)
            release_schema["verdict"] = "PASS"
        except (OSError, ValueError) as error:
            release_schema["verdict"] = "FAIL"
            release_schema["reason"] = str(error)
    promotion_evidence = _promotion_evidence_audit(root_path, capabilities)
    verified_promotion_ids = set(promotion_evidence["verified"])
    verified_promotion_targets: set[tuple[str, str]] = set()
    try:
        promotion_records = load_promotion_records(
            root_path / "registry" / "promotion-evidence.yaml"
        )
    except (OSError, ValueError):
        promotion_records = []
    for record in promotion_records:
        if record.get("id") in verified_promotion_ids:
            verified_promotion_targets.add(
                (str(record.get("skill_id")), str(record.get("target_maturity")))
            )
    stale: list[str] = []
    premature: list[str] = []
    cutoff = date.today() - timedelta(days=90)
    runner_ready = all(
        status.get("verdict") == "PASS" for status in (tier_b, behavior, pressure)
    )
    covered_by_kind = {
        status["kind"]: set(status.get("covered_skills", []))
        for status in (tier_b, behavior, pressure)
    }
    for capability in capabilities:
        skill_path = root_path / capability["path"]
        if not skill_path.exists():
            continue
        frontmatter, _ = parse_frontmatter(skill_path)
        studio = frontmatter["metadata"]["studio"]
        reviewed = studio["last_reviewed"]
        reviewed_date = (
            datetime.strptime(reviewed, "%Y-%m-%d").date()
            if isinstance(reviewed, str)
            else reviewed
        )
        if reviewed_date < cutoff:
            stale.append(capability["id"])
        if (
            capability["maturity"] in {"stable", "release"}
            and (capability["id"], capability["maturity"])
            not in verified_promotion_targets
        ):
            premature.append(capability["id"])

    validation_errors = len([issue for issue in validation if issue.severity == "error"])
    deterministic_ready = validation_errors == 0 and not routing.failures
    dogfood_summaries = (
        sorted((root_path / "evidence").rglob("dogfood-summary.json"))
        if (root_path / "evidence").exists()
        else []
    )
    verified_dogfood_summaries: list[Path] = []
    invalid_dogfood_summaries: list[Path] = []
    verified_workflows: set[str] = set()
    for summary_path in dogfood_summaries:
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            invalid_dogfood_summaries.append(summary_path)
            continue
        workflow = summary.get("workflow")
        if _valid_dogfood_summary(summary):
            verified_dogfood_summaries.append(summary_path)
            verified_workflows.add(workflow)
        else:
            invalid_dogfood_summaries.append(summary_path)

    promotion_ready: list[str] = []
    if deterministic_ready and runner_ready:
        promotion_ready = [
            capability["id"]
            for capability in registry.get("capabilities", [])
            if capability["maturity"] in {"draft", "experimental", "beta"}
            and capability["id"] in verified_workflows
            and all(
                capability["id"] in covered_by_kind[kind]
                for kind in ("tier-b", "behavior", "pressure")
            )
        ]

    history_kpis = history["kpis"]
    kpis = {
        "routing_rank_1": {
            "observed": _ratio(routing.passed, routing.total),
            "target_mvp": 0.85,
            "target_stable": 0.90,
        },
        "behavioral": {
            "observed": behavior.get("pass_rate") if behavior.get("verdict") == "PASS" else None,
            "target_mvp": 0.80,
            "target_stable": 0.90,
        },
        "pressure": {
            "observed": pressure.get("pass_rate") if pressure.get("verdict") == "PASS" else None,
            "target": 1.0,
        },
        "pass_with_evidence": {
            "observed": history_kpis["pass_with_evidence"],
            "target": 1.0,
        },
        "unauthorized_writes": {
            "observed": history_kpis["unauthorized_writes"],
            "target": 0,
        },
        "retry_over_three_without_escalation": {
            "observed": history_kpis["retry_over_three_without_escalation"],
            "target": 0,
        },
    }
    status_reasons: list[str] = []
    if not deterministic_ready:
        status_reasons.append("deterministic validation or routing failed")
    if release_schema["verdict"] == "FAIL":
        status_reasons.append("release preflight schema is invalid")
    if premature:
        status_reasons.append("one or more skills have premature maturity")
    for runner_status in (tier_b, behavior, pressure):
        if runner_status.get("verdict") != "PASS":
            status_reasons.append(
                f"{runner_status['kind']} evidence is {runner_status.get('verdict')}"
            )
    if history.get("status") != "PASS":
        status_reasons.append(f"session history is {history.get('status')}")
    if not verified_dogfood_summaries:
        status_reasons.append("verified dogfood evidence is BLOCKED")
    operational_values = (
        history_kpis["pass_with_evidence"],
        history_kpis["unauthorized_writes"],
        history_kpis["retry_over_three_without_escalation"],
    )
    if any(value is None for value in operational_values):
        status_reasons.append("operational KPI observations are incomplete")

    operational_failure = any(
        value is not None and value != target
        for value, target in zip(operational_values, (1.0, 0, 0))
    )
    if operational_failure:
        status_reasons.append("operational KPIs violate required thresholds")
    if (
        not deterministic_ready
        or premature
        or operational_failure
        or history.get("status") == "FAIL"
        or any(
            item.get("verdict") == "FAIL"
            for item in (tier_b, behavior, pressure)
        )
    ):
        status = "FAIL"
    elif status_reasons:
        status = "BLOCKED"
    else:
        status = "PASS"
    if history.get("status") != "PASS" or operational_failure:
        promotion_ready = []
    return {
        "_generated": GENERATED_MARKER,
        "status": status,
        "status_reasons": status_reasons,
        "deterministic_gates": {
            "validation_errors": validation_errors,
            "routing_failures": len(routing.failures),
        },
        "tier_b": tier_b,
        "behavior": behavior,
        "pressure": pressure,
        "session_history": history,
        "history_findings": history["findings"],
        "stale_skills": sorted(stale),
        "premature_maturity": sorted(premature),
        "promotion_ready": sorted(promotion_ready),
        "promotion_evidence": promotion_evidence,
        "release_preflight_schema": release_schema,
        "dogfood_summaries": [path.relative_to(root_path).as_posix() for path in dogfood_summaries],
        "invalid_dogfood_summaries": [
            path.relative_to(root_path).as_posix() for path in invalid_dogfood_summaries
        ],
        "verified_dogfood_summaries": [
            path.relative_to(root_path).as_posix() for path in verified_dogfood_summaries
        ],
        "kpis": kpis,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Audit catalog lifecycle and observed-versus-target KPIs."
    )
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--history", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--input-digest",
        action="store_true",
        help=(
            "Print current runner input binding before a governed run; "
            "does not certify results"
        ),
    )
    args = parser.parse_args(argv)
    if args.input_digest:
        print(runner_input_digest(Path(args.root).resolve()))
        return 0
    report = audit_catalog(Path(args.root), history_path=args.history)
    text = json.dumps(report, indent=2)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text + "\n", encoding="utf-8")
    print(text)
    if report["status"] == "PASS":
        return 0
    return 2 if report["status"] == "BLOCKED" else 1


if __name__ == "__main__":
    sys.exit(main())
