from __future__ import annotations

import hashlib
import hmac
import json
import subprocess
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable, Protocol


STATE_MARKER = "Generated by scripts/codegraph_adapter.py. Do not edit manually."
CODEGRAPH_PACKAGE = "@colbymchenry/codegraph@latest"
VALID_PREFERENCES = {"skip_once", "never_suggest"}
BROKEN_INDEX_STATES = {"broken", "error", "failed", "partial"}
STALE_INDEX_STATES = {"indexing", "stale"}


class CommandResult(Protocol):
    returncode: int
    stdout: str
    stderr: str


CommandRunner = Callable[..., CommandResult]


@dataclass(frozen=True)
class CodeGraphStatus:
    state: str
    blocking: bool
    detail: str
    version: str | None
    existing_index: bool
    index_ownership: str | None
    status_argv: tuple[str, ...]
    raw_status: dict[str, Any] | None = None

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def _default_runner(argv: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
        shell=False,
    )


def _numeric_total(value: object) -> int:
    if isinstance(value, bool):
        return 0
    if isinstance(value, (int, float)):
        return max(0, int(value))
    if isinstance(value, list):
        return len(value)
    if isinstance(value, dict):
        return sum(_numeric_total(item) for item in value.values())
    return 0


def _index_payload(payload: dict[str, Any]) -> dict[str, Any]:
    index = payload.get("index")
    return index if isinstance(index, dict) else {}


def _worktree_payload(payload: dict[str, Any]) -> dict[str, Any]:
    worktree = payload.get("worktree")
    return worktree if isinstance(worktree, dict) else {}


def inspect_codegraph(
    root: Path | str,
    *,
    runner: CommandRunner | None = None,
    preference: str | None = None,
) -> CodeGraphStatus:
    root_path = Path(root).resolve()
    existing_index = (root_path / ".codegraph").is_dir()
    ownership = "USER_OWNED" if existing_index else None
    argv = ["codegraph", "status", str(root_path), "--json", "--no-color"]

    if preference == "never_suggest":
        return CodeGraphStatus(
            state="USER_DISABLED",
            blocking=False,
            detail="CodeGraph advice disabled by project-owned preference.",
            version=None,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
        )

    command_runner = runner or _default_runner
    try:
        completed = command_runner(argv, cwd=root_path)
    except (FileNotFoundError, OSError) as error:
        return CodeGraphStatus(
            state="UNAVAILABLE",
            blocking=False,
            detail=str(error) or "CodeGraph CLI is unavailable.",
            version=None,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
        )
    except Exception as error:
        return CodeGraphStatus(
            state="INITIALIZED_BROKEN",
            blocking=False,
            detail=f"CodeGraph status probe failed: {error}",
            version=None,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
        )

    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "CodeGraph status failed.").strip()
        return CodeGraphStatus(
            state="INITIALIZED_BROKEN",
            blocking=False,
            detail=detail,
            version=None,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
        )

    try:
        payload = json.loads(completed.stdout)
    except (json.JSONDecodeError, TypeError) as error:
        return CodeGraphStatus(
            state="INITIALIZED_BROKEN",
            blocking=False,
            detail=f"Invalid CodeGraph status JSON: {error}",
            version=None,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
        )
    if not isinstance(payload, dict):
        return CodeGraphStatus(
            state="INITIALIZED_BROKEN",
            blocking=False,
            detail="Invalid CodeGraph status JSON object.",
            version=None,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
        )

    version = payload.get("version")
    version_text = str(version) if version is not None else None
    if payload.get("initialized") is not True:
        return CodeGraphStatus(
            state="AVAILABLE_NOT_INITIALIZED",
            blocking=False,
            detail="CodeGraph CLI is available but this project is not initialized.",
            version=version_text,
            existing_index=existing_index,
            index_ownership=ownership,
            status_argv=tuple(argv),
            raw_status=payload,
        )

    index = _index_payload(payload)
    worktree = _worktree_payload(payload)
    index_state = str(index.get("state", "complete")).casefold()
    if index_state in BROKEN_INDEX_STATES or bool(worktree.get("worktreeMismatch")):
        state = "INITIALIZED_BROKEN"
        detail = "CodeGraph reports a broken or mismatched index."
    else:
        pending_changes = _numeric_total(payload.get("pendingChanges"))
        pending_refs = _numeric_total(index.get("pendingRefs")) + _numeric_total(
            worktree.get("pendingRefs")
        )
        stale = (
            bool(index.get("reindexRecommended"))
            or pending_changes > 0
            or pending_refs > 0
            or index_state in STALE_INDEX_STATES
        )
        if stale:
            state = "INITIALIZED_STALE"
            detail = "CodeGraph index exists but refresh signals are present."
        else:
            state = "INITIALIZED_HEALTHY"
            detail = "CodeGraph index reports healthy."

    return CodeGraphStatus(
        state=state,
        blocking=False,
        detail=detail,
        version=version_text,
        existing_index=existing_index,
        index_ownership=ownership,
        status_argv=tuple(argv),
        raw_status=payload,
    )


def _utc_now(now: datetime | None) -> datetime:
    value = now or datetime.now(timezone.utc)
    if value.tzinfo is None:
        raise ValueError("plan time must include a timezone")
    return value.astimezone(timezone.utc)


def _plan_digest(plan: dict[str, object]) -> str:
    unsigned = {key: value for key, value in plan.items() if key != "digest"}
    canonical = json.dumps(unsigned, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def create_install_plan(
    root: Path | str,
    *,
    reviewer: str,
    now: datetime | None = None,
    ttl: timedelta = timedelta(minutes=30),
    cli_available: bool = False,
) -> dict[str, object]:
    if not reviewer.strip():
        raise ValueError("reviewer is required for CodeGraph install planning")
    if ttl <= timedelta(0):
        raise ValueError("CodeGraph install plan ttl must be positive")

    root_path = Path(root).resolve()
    created_at = _utc_now(now)
    existing_index = (root_path / ".codegraph").is_dir()
    actions: list[dict[str, object]] = []
    if not cli_available:
        actions.append(
            {
                "id": "install-cli",
                "argv": ["npm", "install", "--global", CODEGRAPH_PACKAGE],
                "owner": "CodeGraph",
            }
        )
    if not existing_index:
        actions.append(
            {
                "id": "initialize-project",
                "argv": ["codegraph", "init", str(root_path)],
                "owner": "CodeGraph",
            }
        )

    restore_argv: list[list[str]] = []
    if not existing_index:
        restore_argv.append(["codegraph", "uninit", str(root_path), "--force"])
    if not cli_available:
        restore_argv.append(["npm", "uninstall", "--global", "@colbymchenry/codegraph"])

    plan: dict[str, object] = {
        "schema_version": 1,
        "kind": "CODEGRAPH_INSTALL",
        "root": str(root_path),
        "created_at": created_at.isoformat(),
        "expires_at": (created_at + ttl).isoformat(),
        "reviewer": reviewer.strip(),
        "existing_index": existing_index,
        "existing_index_ownership": "USER_OWNED" if existing_index else None,
        "actions": actions,
        "restore_argv": restore_argv,
        "apply_requires": ["reviewer", "digest", "unexpired_plan"],
    }
    plan["digest"] = _plan_digest(plan)
    return plan


def verify_install_plan(
    plan: dict[str, object],
    *,
    reviewer: str,
    digest: str,
    now: datetime | None = None,
) -> dict[str, object]:
    if plan.get("kind") != "CODEGRAPH_INSTALL":
        raise ValueError("not a CodeGraph install plan")
    expected_digest = _plan_digest(plan)
    if not hmac.compare_digest(str(plan.get("digest", "")), expected_digest):
        raise ValueError("CodeGraph install plan content has drifted")
    if not hmac.compare_digest(digest, expected_digest):
        raise ValueError("CodeGraph install plan digest does not match")
    if reviewer.strip() != str(plan.get("reviewer", "")):
        raise ValueError("CodeGraph install plan reviewer does not match")
    try:
        expires_at = datetime.fromisoformat(str(plan["expires_at"]))
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError("CodeGraph install plan expiry is invalid") from error
    if _utc_now(now) > expires_at.astimezone(timezone.utc):
        raise ValueError("CodeGraph install plan has expired")
    return plan


def apply_install_plan(
    plan: dict[str, object],
    *,
    reviewer: str,
    digest: str,
    runner: CommandRunner | None = None,
    now: datetime | None = None,
) -> dict[str, object]:
    verified = verify_install_plan(
        plan,
        reviewer=reviewer,
        digest=digest,
        now=now,
    )
    root_path = Path(str(verified["root"])).resolve()
    command_runner = runner or _default_runner
    completed_actions: list[dict[str, object]] = []
    for action in verified.get("actions", []):
        if not isinstance(action, dict):
            raise ValueError("CodeGraph install action must be an object")
        argv = action.get("argv")
        if not isinstance(argv, list) or not argv or not all(isinstance(item, str) and item for item in argv):
            raise ValueError("CodeGraph install action argv is invalid")
        try:
            completed = command_runner(list(argv), cwd=root_path)
        except OSError as error:
            return {
                "status": "FAIL",
                "root": str(root_path),
                "completed_actions": completed_actions,
                "failed_action": action.get("id"),
                "detail": str(error),
                "restore_argv": verified.get("restore_argv", []),
            }
        record = {
            "id": action.get("id"),
            "argv": list(argv),
            "exit_code": completed.returncode,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
        }
        completed_actions.append(record)
        if completed.returncode != 0:
            return {
                "status": "FAIL",
                "root": str(root_path),
                "completed_actions": completed_actions,
                "failed_action": action.get("id"),
                "detail": (completed.stderr or completed.stdout).strip(),
                "restore_argv": verified.get("restore_argv", []),
            }
    return {
        "status": "PASS",
        "root": str(root_path),
        "reviewer": reviewer.strip(),
        "plan_digest": digest,
        "completed_actions": completed_actions,
        "restore_argv": verified.get("restore_argv", []),
    }


def plan_codegraph_preference(root: Path | str, preference: str) -> dict[str, str]:
    if preference not in VALID_PREFERENCES:
        raise ValueError(f"unsupported CodeGraph preference: {preference}")
    root_path = Path(root).resolve()
    target = root_path / ".agents" / "gamestudio-state.json"
    state: dict[str, object] = {
        "_generated": STATE_MARKER,
        "schema_version": 1,
    }
    if target.exists():
        try:
            loaded = json.loads(target.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise ValueError(f"invalid owned GameStudio state: {target}") from error
        if not isinstance(loaded, dict) or loaded.get("_generated") != STATE_MARKER:
            raise ValueError(f"refusing to replace unmanaged GameStudio state: {target}")
        state.update(loaded)

    advice: dict[str, object] = {"mode": preference}
    if preference == "skip_once":
        advice["remaining_runs"] = 1
    state["codegraph_advice"] = advice
    return {
        "path": ".agents/gamestudio-state.json",
        "content": json.dumps(state, indent=2, sort_keys=True) + "\n",
    }
