from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

try:
    from scripts.generate_adapters import generate_adapter, uninstall_project_adapter
except ModuleNotFoundError:
    from generate_adapters import generate_adapter, uninstall_project_adapter


HOOK_MARKER = "# Generated by scripts/doctor.py. Do not edit manually."


def hook_text(python_executable: str = "python") -> str:
    python_path = Path(python_executable).as_posix()
    return f'''#!{python_path}
{HOOK_MARKER}
from pathlib import Path
import subprocess
import sys

root = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())
for script in ("validate.py", "route_eval.py", "secret_scan.py"):
    result = subprocess.run([sys.executable, "-B", str(root / "scripts" / script), str(root)], cwd=root)
    if result.returncode:
        raise SystemExit(result.returncode)
'''


def _git_dir(root: Path) -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    git_dir = Path(result.stdout.strip())
    return git_dir if git_dir.is_absolute() else root / git_dir


def install_hook(root: Path | str, python_executable: str = sys.executable) -> Path:
    root_path = Path(root).resolve()
    hooks_dir = _git_dir(root_path) / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"
    if hook_path.exists() and HOOK_MARKER not in hook_path.read_text(encoding="utf-8", errors="replace"):
        raise RuntimeError(f"refusing to overwrite unmanaged hook: {hook_path}")
    hook_path.write_text(hook_text(python_executable), encoding="utf-8", newline="\n")
    return hook_path


def uninstall_hook(root: Path | str) -> bool:
    hook_path = _git_dir(Path(root).resolve()) / "hooks" / "pre-commit"
    if not hook_path.exists():
        return False
    if HOOK_MARKER not in hook_path.read_text(encoding="utf-8", errors="replace"):
        raise RuntimeError(f"refusing to remove unmanaged hook: {hook_path}")
    hook_path.unlink()
    return True


def install_adapter(root: Path | str, target: str, destination: Path | str) -> dict[str, object]:
    return generate_adapter(Path(root), target, Path(destination))


def uninstall_adapter(destination: Path | str) -> list[str]:
    return uninstall_project_adapter(Path(destination))


def health(root: Path | str) -> dict[str, object]:
    root_path = Path(root).resolve()
    checks: list[dict[str, object]] = []
    for script in ("validate.py", "route_eval.py", "secret_scan.py"):
        command = [sys.executable, "-B", str(root_path / "scripts" / script), str(root_path)]
        result = subprocess.run(command, cwd=root_path, capture_output=True, text=True)
        checks.append(
            {
                "script": script,
                "command": command,
                "exit_code": result.returncode,
                "stdout": result.stdout.strip(),
                "stderr": result.stderr.strip(),
            }
        )
    hook_path = _git_dir(root_path) / "hooks" / "pre-commit"
    managed_hook = hook_path.exists() and HOOK_MARKER in hook_path.read_text(encoding="utf-8", errors="replace")
    return {
        "status": "PASS" if all(check["exit_code"] == 0 for check in checks) else "FAIL",
        "managed_pre_commit_hook": managed_hook,
        "checks": checks,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Install hooks and diagnose GameStudio-CodexKIT health.")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--install-hook", action="store_true")
    action.add_argument("--uninstall-hook", action="store_true")
    action.add_argument("--check", action="store_true")
    action.add_argument("--install-adapter", choices=["hermes", "codex", "per-project"])
    action.add_argument("--uninstall-adapter", action="store_true")
    parser.add_argument("--root", default=".")
    parser.add_argument("--destination")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if args.install_hook:
        print(install_hook(root))
        return 0
    if args.uninstall_hook:
        print("removed" if uninstall_hook(root) else "not-installed")
        return 0
    if args.install_adapter:
        if not args.destination:
            parser.error("--destination is required for --install-adapter")
        print(json.dumps(install_adapter(root, args.install_adapter, Path(args.destination)), indent=2))
        return 0
    if args.uninstall_adapter:
        if not args.destination:
            parser.error("--destination is required for --uninstall-adapter")
        print(json.dumps({"removed": uninstall_adapter(Path(args.destination))}, indent=2))
        return 0
    result = health(root)
    print(json.dumps(result, indent=2))
    return 0 if result["status"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
