from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
from pathlib import Path

try:
    from scripts.generate_adapters import (
        apply_project_adapter,
        generate_adapter,
        report_project_adapter,
        report_uninstall_project_adapter,
        uninstall_project_adapter,
        _uninstall_plan_digest,
        _validate_uninstall_backup_root,
    )
except ModuleNotFoundError:
    from generate_adapters import (
        apply_project_adapter,
        generate_adapter,
        report_project_adapter,
        report_uninstall_project_adapter,
        uninstall_project_adapter,
        _uninstall_plan_digest,
        _validate_uninstall_backup_root,
    )


HOOK_MARKER = "# Generated by scripts/doctor.py. Do not edit manually."


def hook_text(python_executable: str = "python") -> str:
    python_path = Path(python_executable).as_posix()
    return f'''#!{python_path}
{HOOK_MARKER}
from pathlib import Path
import subprocess
import sys

root = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())
for script in ("validate.py", "route_eval.py", "secret_scan.py"):
    result = subprocess.run([sys.executable, "-B", str(root / "scripts" / script), str(root)], cwd=root)
    if result.returncode:
        raise SystemExit(result.returncode)
'''


def _git_dir(root: Path) -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    git_dir = Path(result.stdout.strip())
    return git_dir if git_dir.is_absolute() else root / git_dir


def install_hook(root: Path | str, python_executable: str = sys.executable) -> Path:
    root_path = Path(root).resolve()
    hooks_dir = _git_dir(root_path) / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"
    if hook_path.exists() and HOOK_MARKER not in hook_path.read_text(encoding="utf-8", errors="replace"):
        raise RuntimeError(f"refusing to overwrite unmanaged hook: {hook_path}")
    hook_path.write_text(hook_text(python_executable), encoding="utf-8", newline="\n")
    if os.name != "nt":
        hook_path.chmod(hook_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return hook_path


def uninstall_hook(root: Path | str) -> bool:
    hook_path = _git_dir(Path(root).resolve()) / "hooks" / "pre-commit"
    if not hook_path.exists():
        return False
    if HOOK_MARKER not in hook_path.read_text(encoding="utf-8", errors="replace"):
        raise RuntimeError(f"refusing to remove unmanaged hook: {hook_path}")
    hook_path.unlink()
    return True


def install_adapter(
    root: Path | str,
    target: str,
    destination: Path | str,
    *,
    apply: bool = False,
    reviewer: str | None = None,
    backup_root: Path | str | None = None,
    approved_plan_digest: str | None = None,
) -> dict[str, object]:
    root_path = Path(root)
    destination_path = Path(destination)
    if target in {"hermes", "codex"}:
        if apply or reviewer is not None or backup_root is not None or approved_plan_digest is not None:
            raise ValueError(
                "apply, reviewer, backup_root, and approved_plan_digest are only supported for per-project adapters"
            )
        return generate_adapter(root_path, target, destination_path)
    if target == "per-project":
        if not apply:
            if reviewer is not None or backup_root is not None or approved_plan_digest is not None:
                raise ValueError("reviewer, backup_root, and approved_plan_digest require apply=True")
            return report_project_adapter(root_path, destination_path)
        if reviewer is None or not reviewer.strip():
            raise ValueError("reviewer is required for per-project apply")
        if backup_root is None:
            raise ValueError("backup_root is required for per-project apply")
        if approved_plan_digest is None or not approved_plan_digest.strip():
            raise ValueError("approved_plan_digest is required for per-project apply")
        return apply_project_adapter(
            root_path,
            destination_path,
            reviewer=reviewer,
            backup_root=backup_root,
            approved_plan_digest=approved_plan_digest,
        )
    raise ValueError(f"unsupported adapter target: {target}")


def uninstall_adapter(destination: Path | str) -> list[str]:
    return uninstall_project_adapter(Path(destination))


def health(root: Path | str) -> dict[str, object]:
    root_path = Path(root).resolve()
    checks: list[dict[str, object]] = []
    for script in ("validate.py", "route_eval.py", "secret_scan.py"):
        command = [sys.executable, "-B", str(root_path / "scripts" / script), str(root_path)]
        result = subprocess.run(command, cwd=root_path, capture_output=True, text=True)
        checks.append(
            {
                "script": script,
                "command": command,
                "exit_code": result.returncode,
                "stdout": result.stdout.strip(),
                "stderr": result.stderr.strip(),
            }
        )
    hook_path = _git_dir(root_path) / "hooks" / "pre-commit"
    managed_hook = hook_path.exists() and HOOK_MARKER in hook_path.read_text(encoding="utf-8", errors="replace")
    return {
        "status": "PASS" if all(check["exit_code"] == 0 for check in checks) else "FAIL",
        "managed_pre_commit_hook": managed_hook,
        "checks": checks,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Install hooks and diagnose GameStudio-CodexKIT health.")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--install-hook", action="store_true")
    action.add_argument("--uninstall-hook", action="store_true")
    action.add_argument("--check", action="store_true")
    action.add_argument("--install-adapter", choices=["hermes", "codex", "per-project"])
    action.add_argument("--uninstall-adapter", action="store_true")
    parser.add_argument("--root", default=".")
    parser.add_argument("--destination")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--reviewer")
    parser.add_argument("--backup-root")
    parser.add_argument("--plan-digest")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if (args.apply or args.reviewer or args.backup_root or args.plan_digest) and not (
        args.install_adapter or args.uninstall_adapter
    ):
        parser.error("--apply, --reviewer, --backup-root, and --plan-digest require an adapter action")
    if args.install_hook:
        print(install_hook(root))
        return 0
    if args.uninstall_hook:
        print("removed" if uninstall_hook(root) else "not-installed")
        return 0
    if args.install_adapter:
        if not args.destination:
            parser.error("--destination is required for --install-adapter")
        if args.install_adapter != "per-project" and (
            args.apply or args.reviewer or args.backup_root or args.plan_digest
        ):
            parser.error(
                "--apply, --reviewer, --backup-root, and --plan-digest are only supported for per-project adapters"
            )
        if args.apply:
            if not args.reviewer or not args.reviewer.strip():
                parser.error("--reviewer is required with --apply")
            if not args.backup_root:
                parser.error("--backup-root is required with --apply")
            if not args.plan_digest or not args.plan_digest.strip():
                parser.error("--plan-digest is required with --apply")
        elif args.reviewer or args.backup_root or args.plan_digest:
            parser.error("--reviewer, --backup-root, and --plan-digest require --apply")
        print(
            json.dumps(
                install_adapter(
                    root,
                    args.install_adapter,
                    Path(args.destination),
                    apply=args.apply,
                    reviewer=args.reviewer,
                    backup_root=Path(args.backup_root) if args.backup_root else None,
                    approved_plan_digest=args.plan_digest,
                ),
                indent=2,
            )
        )
        return 0
    if args.uninstall_adapter:
        if not args.destination:
            parser.error("--destination is required for --uninstall-adapter")
        if not args.apply:
            if args.reviewer or args.backup_root or args.plan_digest:
                parser.error("--reviewer, --backup-root, and --plan-digest require --apply")
            print(json.dumps(report_uninstall_project_adapter(Path(args.destination)), indent=2))
            return 0
        if not args.reviewer or not args.reviewer.strip():
            parser.error("--reviewer is required with --uninstall-adapter --apply")
        if not args.backup_root:
            parser.error("--backup-root is required with --uninstall-adapter --apply")
        if not args.plan_digest or not args.plan_digest.strip():
            parser.error("--plan-digest is required with --uninstall-adapter --apply")
        destination = Path(args.destination)
        _validate_uninstall_backup_root(destination, Path(args.backup_root))
        if args.plan_digest.strip() != _uninstall_plan_digest(destination):
            parser.error("adapter uninstall plan changed since report")
        print(json.dumps({"removed": uninstall_adapter(Path(args.destination))}, indent=2))
        return 0
    result = health(root)
    print(json.dumps(result, indent=2))
    return 0 if result["status"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
