from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import stat
import sys
import uuid
from pathlib import Path, PurePosixPath
from typing import Any

try:
    from scripts.agent_overlay import plan_agent_overlay
    from scripts.common import load_yaml
    from scripts.safe_mutation import apply_mutation, report_mutation
except ModuleNotFoundError:
    from agent_overlay import plan_agent_overlay
    from common import load_yaml
    from safe_mutation import apply_mutation, report_mutation


MARKER = "Generated by scripts/generate_adapters.py. Do not edit manually."

class _UninstallReport(dict[str, object]):
    def __contains__(self, item: object) -> bool:
        if super().__contains__(item):
            return True
        if not isinstance(item, str):
            return False
        prefix = f".agents/skills/{item}/"
        removed = self.get("removed", [])
        remaining = [
            *self.get("remaining_owned", []),
            *self.get("recovery_owned", []),
        ]
        removed_path = any(
            isinstance(path, str) and path.startswith(prefix)
            for path in removed
        )
        remaining_path = any(
            isinstance(owned, dict)
            and isinstance(owned.get("path"), str)
            and owned["path"].startswith(prefix)
            for owned in remaining
        )
        return removed_path and not remaining_path

def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _is_reparse_point(path: Path) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    attributes = getattr(info, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return path.is_symlink() or bool(attributes & reparse_flag)


def _safe_project_path(
    project: Path,
    relative: str,
    *,
    required_prefix: tuple[str, ...],
) -> Path:
    normalized = relative.replace("\\", "/")
    pure = PurePosixPath(normalized)
    parts = pure.parts
    if pure.is_absolute() or not parts or ".." in parts or "." in parts:
        raise ValueError(f"unsafe project adapter path: {relative}")
    if parts[: len(required_prefix)] != required_prefix:
        raise ValueError(f"project adapter path is outside its owned scope: {relative}")

    project_root = project.resolve()
    candidate = project_root.joinpath(*parts)
    current = project_root
    if _is_reparse_point(current):
        raise ValueError(f"project root is a symlink or reparse point: {current}")
    for part in parts:
        current = current / part
        if _is_reparse_point(current):
            raise ValueError(f"symlink or reparse point is not allowed: {current}")

    owned_root = project_root.joinpath(*required_prefix).resolve()
    resolved = candidate.resolve()
    try:
        resolved.relative_to(owned_root)
    except ValueError as error:
        raise ValueError(f"project adapter path escapes its owned scope: {relative}") from error
    return candidate


def _has_generated_header(text: str) -> bool:
    lines = text.splitlines()
    return bool(lines) and lines[0] in {f"# {MARKER}", f"<!-- {MARKER} -->"}

def _generated_skill(text: str) -> str:
    return f"# {MARKER}\n{text}"


def _generated_resource(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    if source.name == "SKILL.md":
        return _generated_skill(text)
    if source.suffix.casefold() in {".py", ".sh", ".ps1", ".yaml", ".yml", ".toml"}:
        return f"# {MARKER}\n\n{text}"
    if source.suffix.casefold() in {".md", ".txt"}:
        return f"<!-- {MARKER} -->\n{text}"
    raise ValueError(f"unsupported skill resource type: {source}")


def _skill_files(skill_file: Path) -> list[Path]:
    return sorted(path for path in skill_file.parent.rglob("*") if path.is_file())


def _capabilities(root: Path) -> list[dict[str, Any]]:
    registry = load_yaml(root / "registry" / "capabilities.yaml")
    return registry.get("capabilities", [])


def _prepare_managed_output(output: Path) -> None:
    if not output.exists():
        return
    for file in (item for item in output.rglob("*") if item.is_file()):
        text = file.read_text(encoding="utf-8", errors="replace")
        if file.name == "registry.json":
            try:
                managed = json.loads(text).get("_generated") == MARKER
            except (AttributeError, json.JSONDecodeError):
                managed = False
        else:
            managed = _has_generated_header(text)
        if not managed:
            raise RuntimeError(f"refusing to replace unmanaged adapter file: {file}")
    shutil.rmtree(output)


def _write_standard_adapter(root: Path, target: str, output: Path) -> dict[str, object]:
    _prepare_managed_output(output)
    created: list[str] = []
    capabilities = _capabilities(root)
    for capability in capabilities:
        skill_file = root / capability["path"]
        for source in _skill_files(skill_file):
            relative_resource = source.relative_to(skill_file.parent)
            destination = output / "skills" / capability["id"] / relative_resource
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(_generated_resource(source), encoding="utf-8", newline="\n")
            created.append(destination.relative_to(output).as_posix())
    registry = {
        "_generated": MARKER,
        "schema_version": 1,
        "target": target,
        "skills": [capability["id"] for capability in capabilities],
    }
    (output / "registry.json").write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
    created.append("registry.json")
    return {"target": target, "created": sorted(created), "preserved": []}


def _read_project_registry(project: Path) -> dict[str, Any]:
    path = _safe_project_path(
        project,
        ".agents/registry.json",
        required_prefix=(".agents",),
    )
    if not path.exists():
        return {"schema_version": 1, "skills": []}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("project .agents/registry.json must be an object")
    return data


def _owned_project_path(project: Path, relative: str) -> tuple[str, Path]:
    normalized = PurePosixPath(relative.replace("\\", "/")).as_posix()
    parts = PurePosixPath(normalized).parts
    if len(parts) >= 4 and parts[:2] == (".agents", "skills"):
        required_prefix = (".agents", "skills", parts[2])
    elif len(parts) == 3 and parts[:2] == (".codex", "agents"):
        required_prefix = (".codex", "agents")
    elif parts == (".codex", "agents.generated.toml"):
        required_prefix = (".codex",)
    else:
        raise ValueError(f"unsupported project adapter owned path: {relative}")
    return normalized, _safe_project_path(
        project,
        normalized,
        required_prefix=required_prefix,
    )

def _manifest_owned_project_path(project: Path, relative: str) -> tuple[str, Path]:
    normalized = PurePosixPath(relative.replace("\\", "/")).as_posix()
    parts = PurePosixPath(normalized).parts
    if len(parts) >= 4 and parts[:2] == (".agents", "skills"):
        required_prefix = (".agents", "skills", parts[2])
    elif len(parts) == 3 and parts[:2] == (".codex", "agents"):
        required_prefix = (".codex", "agents")
    elif parts == (".codex", "agents.generated.toml"):
        required_prefix = (".codex",)
    else:
        raise ValueError(f"unsupported project adapter owned path: {relative}")
    parent_relative = PurePosixPath(*parts[:-1]).as_posix()
    parent = _safe_project_path(
        project,
        parent_relative,
        required_prefix=required_prefix,
    )
    return normalized, parent / parts[-1]

def _owned_destination_identity(candidate: Path) -> str:
    parent = candidate.parent.resolve()
    return os.path.normcase(os.path.abspath(str(parent / candidate.name)))

def _project_adapter_plan(root: Path, project: Path) -> dict[str, object]:
    capabilities = _capabilities(root)
    overlay_plan = plan_agent_overlay(
        project,
        template_root=(
            root / "skills" / "studio-project-scaffold" / "templates" / "agents"
        ),
        profile_path=project / ".agents" / "project-profile.yaml",
        known_skills={str(capability["id"]) for capability in capabilities},
    )

    registry = _read_project_registry(project)
    previous_owned: dict[str, dict[str, str]] = {}
    previous_adapter = registry.get("kit_adapter", {})
    if previous_adapter.get("adapter_id") in {
        "GameStudio-CodexKIT/per-project/v1",
        "GameStudio-CodexKIT/per-project/v2",
    }:
        for owned in previous_adapter.get("files", []):
            if not isinstance(owned, dict):
                continue
            try:
                normalized, candidate = _owned_project_path(
                    project,
                    str(owned.get("path", "")),
                )
            except ValueError:
                continue
            if candidate.exists():
                previous_owned[normalized] = {
                    "path": normalized,
                    "sha256": str(owned.get("sha256", "")),
                }

    operations: list[dict[str, str]] = []
    preserved: list[str] = []
    owned_by_path = dict(previous_owned)
    skill_root = _safe_project_path(
        project,
        ".agents/skills",
        required_prefix=(".agents", "skills"),
    )
    planned_skill_names: set[str] = set()
    for capability in capabilities:
        capability_id = str(capability["id"])
        skill_file = root / capability["path"]
        for source in _skill_files(skill_file):
            relative_resource = source.relative_to(skill_file.parent)
            relative = PurePosixPath(
                ".agents",
                "skills",
                capability_id,
                *relative_resource.parts,
            ).as_posix()
            destination = _safe_project_path(
                project,
                relative,
                required_prefix=(".agents", "skills", capability_id),
            )
            if destination.exists() and not destination.is_file():
                preserved.append(destination.relative_to(project).as_posix())
                continue
            existing_text = (
                destination.read_text(encoding="utf-8", errors="replace")
                if destination.is_file()
                else ""
            )
            previous = previous_owned.get(relative)
            previous_hash_matches = (
                previous is not None
                and destination.is_file()
                and hashlib.sha256(destination.read_bytes()).hexdigest() == previous["sha256"]
            )
            if destination.exists() and not (
                _has_generated_header(existing_text) or previous_hash_matches
            ):
                preserved.append(destination.relative_to(project).as_posix())
                continue
            generated_text = _generated_resource(source)
            operations.append({"path": relative, "content": generated_text})
            owned_by_path[relative] = {
                "path": relative,
                "sha256": _sha256_text(generated_text),
            }
        planned_skill_names.add(capability_id)

    for operation in overlay_plan["operations"]:
        relative = str(operation["path"])
        normalized, _destination = _owned_project_path(project, relative)
        content = str(operation["content"])
        operations.append({"path": normalized, "content": content})
        owned_by_path[normalized] = {
            "path": normalized,
            "sha256": _sha256_text(content),
        }
    preserved.extend(str(path) for path in overlay_plan["preserved"])

    if skill_root.exists():
        planned_skill_names.update(
            directory.name
            for directory in skill_root.iterdir()
            if directory.is_dir() and (directory / "SKILL.md").exists()
        )
    registry["schema_version"] = registry.get("schema_version", 1)
    registry["skills"] = sorted(planned_skill_names)
    registry["kit_adapter"] = {
        "_generated": MARKER,
        "adapter_id": "GameStudio-CodexKIT/per-project/v2",
        "source": "GameStudio-CodexKIT",
        "target": "per-project",
        "files": sorted(owned_by_path.values(), key=lambda item: item["path"]),
    }
    registry_relative = ".agents/registry.json"
    _safe_project_path(project, registry_relative, required_prefix=(".agents",))
    operations.append(
        {
            "path": registry_relative,
            "content": json.dumps(registry, indent=2) + "\n",
        }
    )
    if any(operation["path"] == ".codex/config.toml" for operation in operations):
        raise RuntimeError("project adapter must never mutate .codex/config.toml")
    return {
        "target": "per-project",
        "operations": operations,
        "preserved": sorted(set(preserved)),
        "collisions": sorted(
            overlay_plan["collisions"],
            key=lambda collision: str(collision["path"]),
        ),
        "activated_roles": list(overlay_plan["activated_roles"]),
    }
def _plan_digest(mutation_report: dict[str, Any]) -> str:
    normalized_operations = sorted(
        (
            {
                "path": str(operation["path"]).replace("\\", "/"),
                "action": operation["action"],
                "before_sha256": operation["before_sha256"],
                "after_sha256": operation["after_sha256"],
            }
            for operation in mutation_report["operations"]
        ),
        key=lambda operation: operation["path"],
    )
    payload = {
        "root": str(Path(mutation_report["root"]).resolve()),
        "operations": normalized_operations,
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _validated_backup_root(
    project: Path,
    backup_root: Path | str,
    operations: list[dict[str, str]],
) -> Path:
    project_root = project.resolve()
    backup_path = Path(backup_root).resolve()
    try:
        relative_backup = backup_path.relative_to(project_root)
    except ValueError as error:
        raise ValueError("backup root must remain inside the project root") from error
    current = project_root
    if _is_reparse_point(current):
        raise ValueError(f"project root is a symlink or reparse point: {current}")
    for part in relative_backup.parts:
        current = current / part
        if current.exists() and _is_reparse_point(current):
            raise ValueError(f"symlink or reparse point is not allowed: {current}")
    for operation in operations:
        relative = PurePosixPath(str(operation["path"]).replace("\\", "/"))
        target = project_root.joinpath(*relative.parts).resolve()
        if (
            backup_path == target
            or target.is_relative_to(backup_path)
            or backup_path.is_relative_to(target)
        ):
            raise ValueError(
                f"backup root overlaps planned target {operation['path']}: {backup_path}"
            )
    return backup_path


def report_project_adapter(root: Path | str, project: Path | str) -> dict[str, object]:
    root_path = Path(root).resolve()
    project_path = Path(project).resolve()
    plan = _project_adapter_plan(root_path, project_path)
    operations = list(plan["operations"])
    mutation_report = report_mutation(project_path, operations)
    plan_digest = _plan_digest(mutation_report)
    created = sorted(
        item["path"] for item in mutation_report["operations"] if item["action"] == "create"
    )
    updated = sorted(
        item["path"] for item in mutation_report["operations"] if item["action"] == "update"
    )
    return {
        "status": "REPORT_ONLY",
        "target": "per-project",
        "root": str(project_path),
        "plan_digest": plan_digest,
        "proposed": sorted(item["path"] for item in operations),
        "created": created,
        "updated": updated,
        "preserved": plan["preserved"],
        "collisions": plan["collisions"],
        "activated_roles": plan["activated_roles"],
        "mutation_report": mutation_report,
    }


def apply_project_adapter(
    root: Path | str,
    project: Path | str,
    *,
    reviewer: str,
    backup_root: Path | str,
    approved_plan_digest: str,
) -> dict[str, object]:
    reviewer_name = reviewer.strip()
    if not reviewer_name:
        raise ValueError("reviewer is required for project adapter apply")
    approved_digest = approved_plan_digest.strip()
    if not approved_digest:
        raise ValueError("approved_plan_digest is required for project adapter apply")
    root_path = Path(root).resolve()
    project_path = Path(project).resolve()
    plan = _project_adapter_plan(root_path, project_path)
    operations = list(plan["operations"])
    mutation_report = report_mutation(project_path, operations)
    current_plan_digest = _plan_digest(mutation_report)
    if current_plan_digest != approved_digest:
        raise ValueError(
            "project adapter plan changed since report; review the new report and approve its plan digest"
        )
    backup_path = _validated_backup_root(project_path, backup_root, operations)
    manifest_path = apply_mutation(
        project_path,
        operations,
        backup_path,
        expected_operations=mutation_report["operations"],
    )
    created = sorted(
        item["path"] for item in mutation_report["operations"] if item["action"] == "create"
    )
    updated = sorted(
        item["path"] for item in mutation_report["operations"] if item["action"] == "update"
    )
    restore_argv = [
        sys.executable,
        "-B",
        str(Path(__file__).resolve().with_name("safe_mutation.py")),
        "--root",
        str(project_path),
        "--mode",
        "restore",
        "--manifest",
        str(manifest_path),
    ]
    return {
        "status": "PASS",
        "target": "per-project",
        "root": str(project_path),
        "reviewer": reviewer_name,
        "plan_digest": current_plan_digest,
        "manifest": str(manifest_path),
        "restore_argv": restore_argv,
        "created": created,
        "updated": updated,
        "preserved": plan["preserved"],
        "collisions": plan["collisions"],
        "activated_roles": plan["activated_roles"],
    }

def generate_adapter(root: Path | str, target: str, output: Path | str) -> dict[str, object]:
    root_path = Path(root).resolve()
    output_path = Path(output).resolve()
    if target in {"hermes", "codex"}:
        return _write_standard_adapter(root_path, target, output_path)
    if target == "per-project":
        return report_project_adapter(root_path, output_path)
    raise ValueError(f"unsupported adapter target: {target}")

def _remaining_manifest_files(adapter: object) -> list[object]:
    if not isinstance(adapter, dict):
        return []
    files = adapter.get("files", [])
    return list(files) if isinstance(files, list) else []

def _partial_uninstall_report(adapter: object) -> _UninstallReport:
    return _UninstallReport({
        "status": "PARTIAL",
        "removed": [],
        "preserved_drift": [],
        "remaining_owned": _remaining_manifest_files(adapter),
    })

def _normalized_owned_files(
    project: Path,
    adapter: dict[str, Any],
) -> list[tuple[dict[str, str], Path]] | None:
    files = adapter.get("files")
    if not isinstance(files, list):
        return None
    normalized_files: list[tuple[dict[str, str], Path]] = []
    seen_destinations: set[str] = set()
    for owned in files:
        if not isinstance(owned, dict):
            return None
        relative = owned.get("path")
        sha256 = owned.get("sha256")
        if not isinstance(relative, str) or not relative:
            return None
        if (
            not isinstance(sha256, str)
            or len(sha256) != 64
            or any(character not in "0123456789abcdefABCDEF" for character in sha256)
        ):
            return None
        try:
            normalized, candidate = _manifest_owned_project_path(project, relative)
        except ValueError:
            return None
        destination_identity = _owned_destination_identity(candidate)
        if destination_identity in seen_destinations:
            return None
        seen_destinations.add(destination_identity)
        normalized_files.append(
            ({"path": normalized, "sha256": sha256.lower()}, candidate)
        )
    return normalized_files
def _owned_cleanup_root(
    project: Path,
    relative: str,
    *,
    skill_root: Path,
    agent_root: Path,
) -> Path:
    parts = PurePosixPath(relative).parts
    if parts[:2] == (".agents", "skills"):
        return skill_root
    if parts[:2] == (".codex", "agents"):
        return agent_root
    return project / ".codex"

def _regular_file_sha256(candidate: Path) -> str | None:
    try:
        info = candidate.lstat()
    except (FileNotFoundError, OSError):
        return None
    if _is_reparse_point(candidate) or not stat.S_ISREG(info.st_mode):
        return None
    try:
        return hashlib.sha256(candidate.read_bytes()).hexdigest()
    except OSError:
        return None

def _owned_regular_file_matches(candidate: Path, expected_sha256: str) -> bool:
    return _regular_file_sha256(candidate) == expected_sha256

def _transaction_failure_report(
    normalized_files: list[tuple[dict[str, str], Path]],
    preserved_drift: set[str],
) -> _UninstallReport:
    return _UninstallReport({
        "status": "PARTIAL",
        "removed": [],
        "preserved_drift": sorted(preserved_drift),
        "remaining_owned": [owned for owned, _candidate in normalized_files],
    })

def _restore_quarantined(
    quarantined: list[tuple[dict[str, str], Path, Path]],
    preserved_drift: set[str],
) -> bool:
    restored = True
    for owned, candidate, quarantine_path in reversed(quarantined):
        if not os.path.lexists(quarantine_path):
            if not os.path.lexists(candidate):
                preserved_drift.add(owned["path"])
                restored = False
            continue
        if os.path.lexists(candidate):
            preserved_drift.add(owned["path"])
            if not _owned_regular_file_matches(quarantine_path, owned["sha256"]):
                restored = False
                continue
            try:
                quarantine_path.unlink()
            except OSError:
                restored = False
                continue
            if os.path.lexists(quarantine_path):
                restored = False
            continue
        if not _owned_regular_file_matches(quarantine_path, owned["sha256"]):
            preserved_drift.add(owned["path"])
        try:
            os.link(quarantine_path, candidate, follow_symlinks=False)
            os.unlink(quarantine_path)
        except OSError:
            preserved_drift.add(owned["path"])
            restored = False
    return restored

def _refresh_restored_recovery_records(
    recovery: dict[str, object] | None,
    quarantined: list[tuple[dict[str, str], Path, Path]],
) -> None:
    if recovery is None:
        return
    files = recovery.get("files")
    if not isinstance(files, list) or len(files) != len(quarantined):
        return
    recovery["state"] = "prepared"
    for record, (owned, candidate, quarantine_path) in zip(files, quarantined):
        if not isinstance(record, dict):
            continue
        record.pop("observed_sha256", None)
        if _owned_regular_file_matches(quarantine_path, owned["sha256"]):
            record["state"] = "moved"
            record["artifact_present"] = True
        elif _owned_regular_file_matches(candidate, owned["sha256"]):
            record["state"] = "source"
            record["artifact_present"] = False
        else:
            record["state"] = "missing"
            record["artifact_present"] = False

def _quarantine_recovery_payload(
    project: Path,
    adapter: dict[str, Any],
    transaction_id: str,
    quarantined: list[tuple[dict[str, str], Path, Path]],
) -> dict[str, object]:
    return {
        "schema_version": 1,
        "transaction_id": transaction_id,
        "adapter_id": adapter["adapter_id"],
        "state": "prepared",
        "files": [
            {
                "path": owned["path"],
                "sha256": owned["sha256"],
                "quarantine_path": quarantine_path.relative_to(project).as_posix(),
                "state": "source",
            }
            for owned, _candidate, quarantine_path in quarantined
        ],
    }

def _fsync_directory_best_effort(directory: Path) -> None:
    try:
        descriptor = os.open(directory, os.O_RDONLY)
    except (AttributeError, OSError):
        return
    try:
        try:
            os.fsync(descriptor)
        except OSError:
            pass
    finally:
        os.close(descriptor)

def _recovery_generation_revision(path: Path) -> int | None:
    name = path.name
    if name == "recovery.json":
        return 0
    if not name.startswith("recovery.") or not name.endswith(".json"):
        return None
    generation = name[len("recovery."):-len(".json")]
    if len(generation) != 8 or not generation.isdigit():
        return None
    return int(generation)

def _next_recovery_revision(recovery_path: Path, recovery: dict[str, object]) -> int:
    current = recovery.get("revision", -1)
    if not isinstance(current, int) or isinstance(current, bool) or current < -1:
        raise OSError("quarantine recovery manifest revision is invalid")
    highest = current
    root = recovery_path.parent
    try:
        with os.scandir(root) as entries:
            for entry in entries:
                revision = _recovery_generation_revision(root / entry.name)
                if revision is not None:
                    highest = max(highest, revision)
    except OSError:
        pass
    return highest + 1

def _publish_recovery_payload(
    target: Path,
    payload: str,
    recovery: dict[str, object],
) -> None:
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        with temporary.open("w", encoding="utf-8", newline="") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        if json.loads(temporary.read_text(encoding="utf-8")) != recovery:
            raise OSError("quarantine recovery manifest verification failed")
        temporary.replace(target)
        _fsync_directory_best_effort(target.parent)
        if json.loads(target.read_text(encoding="utf-8")) != recovery:
            raise OSError("quarantine recovery manifest publication verification failed")
    finally:
        if os.path.lexists(temporary):
            try:
                temporary.unlink()
            except OSError:
                pass

def _write_quarantine_recovery_manifest(
    recovery_path: Path,
    recovery: dict[str, object],
) -> Path:
    revision = _next_recovery_revision(recovery_path, recovery)
    recovery["revision"] = revision
    recovery["generation"] = revision
    payload = json.dumps(recovery, indent=2) + "\n"
    canonical = (
        recovery_path.parent / "recovery.json"
        if recovery_path.name == "recovery.json"
        or _recovery_generation_revision(recovery_path) is not None
        else recovery_path
    )
    try:
        _publish_recovery_payload(canonical, payload, recovery)
        return canonical
    except PermissionError:
        if canonical.name != "recovery.json" or not _is_real_regular_file(canonical):
            raise
    generation_path = canonical.parent / f"recovery.{revision:08d}.json"
    if os.path.lexists(generation_path):
        raise OSError("quarantine recovery generation already exists")
    _publish_recovery_payload(generation_path, payload, recovery)
    return generation_path

def _recovery_owned_records(
    project: Path,
    quarantined: list[tuple[dict[str, str], Path, Path]],
) -> list[dict[str, str]]:
    return [
        {
            "path": owned["path"],
            "quarantine_path": quarantine_path.relative_to(project).as_posix(),
            "sha256": owned["sha256"],
        }
        for owned, _candidate, quarantine_path in quarantined
        if os.path.lexists(quarantine_path)
    ]

def _existing_recovery_manifest(
    quarantine_root: Path | None,
    recovery_path: Path | None,
) -> Path | None:
    if quarantine_root is not None:
        durable = quarantine_root.with_name(f"{quarantine_root.name}.recovery.json")
        if _is_real_regular_file(durable):
            return durable
        project = quarantine_root.parent.parent
        selected = _select_recovery_journal(project, quarantine_root)
        if selected is not None:
            return selected[1]
    if recovery_path is not None and _is_real_regular_file(recovery_path):
        return recovery_path
    return None

def _recovery_report(
    project: Path,
    *,
    removed: list[str],
    preserved_drift: set[str],
    remaining_owned: list[dict[str, str]],
    recovery_manifest: Path,
    recovery_owned: list[dict[str, str]],
    unsafe_recovery: Path | None = None,
) -> _UninstallReport:
    report = _UninstallReport({
        "status": "PARTIAL",
        "removed": sorted(removed),
        "preserved_drift": sorted(preserved_drift),
        "remaining_owned": sorted(remaining_owned, key=lambda item: item["path"]),
        "recovery_manifest": recovery_manifest.relative_to(project).as_posix(),
        "recovery_owned": sorted(recovery_owned, key=lambda item: item["path"]),
    })
    if unsafe_recovery is not None:
        report["unsafe_recovery"] = unsafe_recovery.relative_to(project).as_posix()
    return report

def _unsafe_recovery_report(
    project: Path,
    *,
    remaining_owned: list[dict[str, str]],
    unsafe_recovery: Path,
) -> _UninstallReport:
    return _UninstallReport({
        "status": "PARTIAL",
        "removed": [],
        "preserved_drift": [],
        "remaining_owned": sorted(remaining_owned, key=lambda item: item["path"]),
        "unsafe_recovery": unsafe_recovery.relative_to(project).as_posix(),
    })

def _finalize_quarantined(
    quarantined: list[tuple[dict[str, str], Path, Path]],
    preserved_drift: set[str],
    recovery: dict[str, object] | None,
    recovery_path: Path | None,
) -> tuple[list[str], bool]:
    removed: list[str] = []
    finalized = True
    recovery_files = recovery.get("files") if recovery is not None else None
    removable: list[tuple[dict[str, str], Path, dict[str, object] | None]] = []
    for index, (owned, _candidate, quarantine_path) in enumerate(quarantined):
        record = recovery_files[index] if isinstance(recovery_files, list) else None
        if not os.path.lexists(quarantine_path):
            preserved_drift.add(owned["path"])
            finalized = False
            if isinstance(record, dict):
                record["state"] = "missing"
                record["artifact_present"] = False
                record.pop("observed_sha256", None)
            continue
        observed_sha256 = _regular_file_sha256(quarantine_path)
        if observed_sha256 != owned["sha256"]:
            preserved_drift.add(owned["path"])
            finalized = False
            if isinstance(record, dict):
                record["state"] = "drifted"
                record["artifact_present"] = True
                if observed_sha256 is None:
                    record.pop("observed_sha256", None)
                else:
                    record["observed_sha256"] = observed_sha256
            continue
        if isinstance(record, dict):
            record["state"] = "finalizing"
            record["artifact_present"] = True
            record.pop("observed_sha256", None)
        removable.append((owned, quarantine_path, record if isinstance(record, dict) else None))
    if recovery is not None and recovery_path is not None:
        recovery["state"] = "registry_committed"
        try:
            recovery_path = _write_quarantine_recovery_manifest(recovery_path, recovery)
        except OSError:
            return [], False
    journal_changed = False
    for owned, quarantine_path, record in removable:
        try:
            quarantine_path.unlink()
        except OSError:
            preserved_drift.add(owned["path"])
            finalized = False
            continue
        if os.path.lexists(quarantine_path):
            preserved_drift.add(owned["path"])
            finalized = False
            continue
        removed.append(owned["path"])
        if record is not None:
            record["state"] = "removed"
            record["artifact_present"] = False
            journal_changed = True
    if journal_changed and recovery is not None and recovery_path is not None:
        try:
            recovery_path = _write_quarantine_recovery_manifest(recovery_path, recovery)
        except OSError:
            finalized = False
    return removed, finalized

def _remove_quarantine_recovery(
    quarantine_root: Path | None,
    recovery_path: Path | None,
    recovery: dict[str, object] | None,
) -> bool:
    if quarantine_root is None:
        return True
    durable_recovery = quarantine_root.with_name(
        f"{quarantine_root.name}.recovery.json"
    )
    if recovery is None:
        return False
    if recovery_path is not None and recovery_path.parent == quarantine_root:
        try:
            recovery_path = _write_quarantine_recovery_manifest(
                recovery_path,
                recovery,
            )
        except OSError:
            return False
    try:
        durable_recovery = _write_quarantine_recovery_manifest(
            durable_recovery,
            recovery,
        )
    except OSError:
        return False
    project = quarantine_root.parent.parent
    selected = _select_recovery_journal(project, quarantine_root)
    if selected is None:
        return False
    _loaded, _selected_path, valid_manifests, invalid_manifests = selected
    if invalid_manifests:
        return False
    for manifest in valid_manifests:
        try:
            manifest.unlink()
        except OSError:
            return False
        if os.path.lexists(manifest):
            return False
    _fsync_directory_best_effort(quarantine_root)
    if not _remove_empty_quarantine_root(quarantine_root):
        return False
    try:
        durable_recovery.unlink()
    except OSError:
        return False
    _fsync_directory_best_effort(durable_recovery.parent)
    return not os.path.lexists(durable_recovery)

def _remove_empty_quarantine_root(quarantine_root: Path | None) -> bool:
    if quarantine_root is None or not os.path.lexists(quarantine_root):
        return True
    try:
        info = quarantine_root.lstat()
        if _is_reparse_point(quarantine_root) or not stat.S_ISDIR(info.st_mode):
            return False
        if any(quarantine_root.iterdir()):
            return False
        quarantine_root.rmdir()
    except OSError:
        return False
    return not os.path.lexists(quarantine_root)

def _write_registry_atomically(registry_path: Path, registry: dict[str, Any]) -> None:
    temporary = registry_path.with_name(
        f".{registry_path.name}.uninstall-{uuid.uuid4().hex}.tmp"
    )
    try:
        temporary.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
        temporary.replace(registry_path)
    finally:
        if temporary.exists():
            temporary.unlink()

def _is_real_directory(path: Path, *, parent: Path) -> bool:
    if path.parent != parent:
        return False
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    return stat.S_ISDIR(info.st_mode) and not _is_reparse_point(path)

def _is_real_regular_file(path: Path) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    return stat.S_ISREG(info.st_mode) and not _is_reparse_point(path)

def _stale_recovery_candidates(
    project: Path,
) -> tuple[list[Path], list[Path], list[Path]]:
    agents_root = project / ".agents"
    if not _is_real_directory(agents_root, parent=project):
        return [], [], []
    roots: list[Path] = []
    durable_manifests: list[Path] = []
    unsafe: list[Path] = []
    try:
        with os.scandir(agents_root) as entries:
            for entry in entries:
                name = entry.name
                if not name.startswith(".adapter-uninstall-quarantine-"):
                    continue
                candidate = agents_root / name
                try:
                    info = entry.stat(follow_symlinks=False)
                except OSError:
                    unsafe.append(candidate)
                    continue
                if _is_reparse_point(candidate):
                    unsafe.append(candidate)
                elif stat.S_ISDIR(info.st_mode):
                    child_count = 0
                    journal_present = False
                    journal_is_unsafe = False
                    try:
                        with os.scandir(candidate) as child_entries:
                            for child in child_entries:
                                child_count += 1
                                if not _is_recovery_journal_name(child.name):
                                    continue
                                journal_present = True
                                journal = candidate / child.name
                                try:
                                    journal_info = child.stat(follow_symlinks=False)
                                except OSError:
                                    journal_is_unsafe = True
                                    continue
                                if (
                                    not stat.S_ISREG(journal_info.st_mode)
                                    or _is_reparse_point(journal)
                                ):
                                    journal_is_unsafe = True
                    except OSError:
                        unsafe.append(candidate)
                        continue
                    if not _is_real_directory(candidate, parent=agents_root):
                        unsafe.append(candidate)
                    elif child_count == 0:
                        if not _remove_empty_quarantine_root(candidate):
                            unsafe.append(candidate)
                    elif journal_present and not journal_is_unsafe:
                        roots.append(candidate)
                    else:
                        unsafe.append(candidate)
                elif stat.S_ISREG(info.st_mode) and name.endswith(".recovery.json"):
                    durable_manifests.append(candidate)
                else:
                    unsafe.append(candidate)
    except OSError:
        return [], [], [agents_root]
    return sorted(roots), sorted(durable_manifests), sorted(unsafe)

def _quarantine_regular_file_matches(
    quarantine_root: Path,
    quarantine_path: Path,
    expected_sha256: str,
    *,
    agents_root: Path,
) -> bool:
    if not _is_real_directory(quarantine_root, parent=agents_root):
        return False
    if quarantine_path.parent != quarantine_root:
        return False
    if not _is_real_regular_file(quarantine_path):
        return False
    return hashlib.sha256(quarantine_path.read_bytes()).hexdigest() == expected_sha256

def _load_recovery_journal(
    project: Path,
    recovery_manifest: Path,
) -> tuple[
    dict[str, object],
    Path,
    list[tuple[dict[str, str], Path, Path]],
] | None:
    agents_root = project / ".agents"
    if not _is_real_directory(agents_root, parent=project):
        return None
    manifest_generation = _recovery_generation_revision(recovery_manifest)
    if manifest_generation is not None:
        quarantine_root = recovery_manifest.parent
        if not _is_real_directory(quarantine_root, parent=agents_root):
            return None
        if recovery_manifest.parent != quarantine_root:
            return None
    elif recovery_manifest.name.endswith(".recovery.json"):
        if recovery_manifest.parent != agents_root:
            return None
        quarantine_root = recovery_manifest.with_name(
            recovery_manifest.name.removesuffix(".recovery.json")
        )
        if os.path.lexists(quarantine_root) and not _is_real_directory(
            quarantine_root,
            parent=agents_root,
        ):
            return None
    else:
        return None
    if not quarantine_root.name.startswith(".adapter-uninstall-quarantine-"):
        return None
    if not _is_real_regular_file(recovery_manifest):
        return None
    try:
        recovery = json.loads(recovery_manifest.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(recovery, dict) or recovery.get("schema_version") != 1:
        return None
    revision = recovery.get("revision", 0)
    generation = recovery.get("generation", revision)
    if (
        not isinstance(revision, int)
        or isinstance(revision, bool)
        or revision < 0
        or not isinstance(generation, int)
        or isinstance(generation, bool)
        or generation != revision
        or (
            manifest_generation not in {None, 0}
            and manifest_generation != revision
        )
    ):
        return None
    recovery["revision"] = revision
    recovery["generation"] = generation
    transaction_id = recovery.get("transaction_id")
    if not isinstance(transaction_id, str) or not transaction_id:
        return None
    if recovery.get("adapter_id") not in {
        "GameStudio-CodexKIT/per-project/v1",
        "GameStudio-CodexKIT/per-project/v2",
    }:
        return None
    if recovery.get("state") not in {"prepared", "registry_committed"}:
        return None
    expected_root_name = f".adapter-uninstall-quarantine-{transaction_id}"
    if quarantine_root.name != expected_root_name:
        return None
    files = recovery.get("files")
    if not isinstance(files, list) or not files:
        return None
    normalized: list[tuple[dict[str, str], Path, Path]] = []
    seen_destinations: set[str] = set()
    for index, item in enumerate(files):
        if not isinstance(item, dict):
            return None
        relative = item.get("path")
        quarantine_relative = item.get("quarantine_path")
        sha256 = item.get("sha256")
        record_state = item.get("state")
        if (
            not isinstance(relative, str)
            or not isinstance(quarantine_relative, str)
            or not isinstance(sha256, str)
            or len(sha256) != 64
            or any(character not in "0123456789abcdefABCDEF" for character in sha256)
            or record_state not in {
                "source",
                "pending",
                "moved",
                "removing",
                "verifying",
                "finalizing",
                "removed",
                "missing",
                "drifted",
            }
        ):
            return None
        try:
            normalized_path, candidate = _manifest_owned_project_path(project, relative)
        except ValueError:
            return None
        destination_identity = _owned_destination_identity(candidate)
        if destination_identity in seen_destinations:
            return None
        seen_destinations.add(destination_identity)
        quarantine_path = quarantine_root / f"{index:08d}.owned"
        expected_quarantine = quarantine_path.relative_to(project).as_posix()
        if PurePosixPath(quarantine_relative.replace("\\", "/")).as_posix() != expected_quarantine:
            return None
        quarantine_exists = os.path.lexists(quarantine_path)
        quarantine_matches = quarantine_exists and _quarantine_regular_file_matches(
            quarantine_root,
            quarantine_path,
            sha256,
            agents_root=agents_root,
        )
        observed_sha256 = _regular_file_sha256(quarantine_path) if quarantine_exists else None
        if record_state in {"pending", "moved", "removing"} and not quarantine_matches:
            return None
        if record_state in {"removed", "missing"} and quarantine_exists:
            return None
        if record_state == "finalizing" and quarantine_exists and not quarantine_matches:
            return None
        if record_state == "drifted":
            recorded_observed = item.get("observed_sha256")
            if not quarantine_exists:
                return None
            if recorded_observed is not None:
                if (
                    not isinstance(recorded_observed, str)
                    or len(recorded_observed) != 64
                    or any(
                        character not in "0123456789abcdefABCDEF"
                        for character in recorded_observed
                    )
                    or observed_sha256 != recorded_observed.lower()
                ):
                    return None
            elif observed_sha256 is not None:
                return None
            if observed_sha256 == sha256.lower():
                return None
        if record_state == "source":
            if quarantine_exists:
                if not quarantine_matches:
                    return None
            elif not _owned_regular_file_matches(candidate, sha256):
                return None
        normalized.append(
            (
                {
                    "path": normalized_path,
                    "sha256": sha256.lower(),
                    "state": record_state,
                },
                candidate,
                quarantine_path,
            )
        )
    return recovery, quarantine_root, normalized

def _is_recovery_journal_name(name: str) -> bool:
    if name == "recovery.json":
        return True
    if not name.startswith("recovery.") or not name.endswith(".json"):
        return False
    generation = name[len("recovery."):-len(".json")]
    return len(generation) == 8 and generation.isdigit()

def _recovery_journal_header(
    project: Path,
    quarantine_root: Path,
    path: Path,
) -> tuple[int, str] | None:
    if not _is_real_regular_file(path):
        return None
    try:
        recovery = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(recovery, dict) or recovery.get("schema_version") != 1:
        return None
    revision = recovery.get("revision", 0)
    generation = recovery.get("generation", revision)
    transaction_id = recovery.get("transaction_id")
    manifest_generation = _recovery_generation_revision(path)
    durable_path = quarantine_root.with_name(
        f"{quarantine_root.name}.recovery.json"
    )
    internal_manifest = (
        path.parent == quarantine_root
        and manifest_generation is not None
        and (manifest_generation == 0 or manifest_generation == revision)
    )
    durable_manifest = path == durable_path
    if (
        not isinstance(revision, int)
        or isinstance(revision, bool)
        or revision < 0
        or not isinstance(generation, int)
        or isinstance(generation, bool)
        or generation != revision
        or not isinstance(transaction_id, str)
        or not transaction_id
        or not (internal_manifest or durable_manifest)
        or recovery.get("adapter_id") not in {
            "GameStudio-CodexKIT/per-project/v1",
            "GameStudio-CodexKIT/per-project/v2",
        }
        or recovery.get("state") not in {"prepared", "registry_committed"}
        or quarantine_root.name != f".adapter-uninstall-quarantine-{transaction_id}"
    ):
        return None
    files = recovery.get("files")
    if not isinstance(files, list) or not files:
        return None
    seen_destinations: set[str] = set()
    valid_states = {
        "source",
        "pending",
        "moved",
        "removing",
        "verifying",
        "finalizing",
        "removed",
        "missing",
        "drifted",
    }
    for index, item in enumerate(files):
        if not isinstance(item, dict):
            return None
        relative = item.get("path")
        quarantine_relative = item.get("quarantine_path")
        sha256 = item.get("sha256")
        record_state = item.get("state")
        if (
            not isinstance(relative, str)
            or not isinstance(quarantine_relative, str)
            or not isinstance(sha256, str)
            or len(sha256) != 64
            or any(character not in "0123456789abcdefABCDEF" for character in sha256)
            or record_state not in valid_states
        ):
            return None
        try:
            _normalized_path, candidate = _manifest_owned_project_path(project, relative)
        except ValueError:
            return None
        destination_identity = _owned_destination_identity(candidate)
        if destination_identity in seen_destinations:
            return None
        seen_destinations.add(destination_identity)
        expected_quarantine = (
            quarantine_root / f"{index:08d}.owned"
        ).relative_to(project).as_posix()
        if PurePosixPath(quarantine_relative.replace("\\", "/")).as_posix() != expected_quarantine:
            return None
        observed_sha256 = item.get("observed_sha256")
        if observed_sha256 is not None and (
            record_state != "drifted"
            or not isinstance(observed_sha256, str)
            or len(observed_sha256) != 64
            or any(
                character not in "0123456789abcdefABCDEF"
                for character in observed_sha256
            )
        ):
            return None
    return revision, transaction_id
def _select_recovery_journal(
    project: Path,
    quarantine_root: Path,
) -> tuple[
    tuple[dict[str, object], Path, list[tuple[dict[str, str], Path, Path]]],
    Path,
    list[Path],
    list[Path],
] | None:
    if not _is_real_directory(quarantine_root, parent=project / ".agents"):
        return None
    candidates: list[Path] = []
    unsafe: list[Path] = []
    try:
        with os.scandir(quarantine_root) as entries:
            for entry in entries:
                if not _is_recovery_journal_name(entry.name):
                    continue
                candidate = quarantine_root / entry.name
                try:
                    info = entry.stat(follow_symlinks=False)
                except OSError:
                    unsafe.append(candidate)
                    continue
                if not stat.S_ISREG(info.st_mode) or _is_reparse_point(candidate):
                    unsafe.append(candidate)
                    continue
                candidates.append(candidate)
    except OSError:
        return None
    valid: list[tuple[int, str, Path, tuple[dict[str, object], Path, list[tuple[dict[str, str], Path, Path]]]]] = []
    unloaded: list[Path] = []
    for candidate in candidates:
        loaded = _load_recovery_journal(project, candidate)
        if loaded is None:
            unloaded.append(candidate)
            continue
        recovery = loaded[0]
        valid.append((int(recovery["revision"]), candidate.name, candidate, loaded))
    if not valid:
        return None
    selected_revision, _name, selected_path, selected = max(
        valid,
        key=lambda item: (item[0], item[1]),
    )
    selected_transaction = str(selected[0]["transaction_id"])
    known_manifests = [item[2] for item in valid]
    for candidate in unloaded:
        header = _recovery_journal_header(project, quarantine_root, candidate)
        if (
            header is not None
            and header[1] == selected_transaction
            and header[0] < selected_revision
        ):
            known_manifests.append(candidate)
        else:
            unsafe.append(candidate)
    return selected, selected_path, sorted(known_manifests), sorted(set(unsafe))

def _registry_owned_files(
    project: Path,
    registry: dict[str, Any],
) -> list[tuple[dict[str, str], Path]] | None:
    adapter = registry.get("kit_adapter")
    if adapter is None:
        return []
    if not isinstance(adapter, dict) or adapter.get("adapter_id") not in {
        "GameStudio-CodexKIT/per-project/v1",
        "GameStudio-CodexKIT/per-project/v2",
    }:
        return None
    return _normalized_owned_files(project, adapter)

def _cleanup_stale_recovery(
    quarantine_root: Path,
    recovery_manifest: Path,
    recovery: dict[str, object],
) -> tuple[bool, Path | None]:
    if recovery_manifest.parent == quarantine_root:
        cleaned = _remove_quarantine_recovery(
            quarantine_root,
            recovery_manifest,
            recovery,
        )
        return cleaned, _existing_recovery_manifest(
            quarantine_root,
            recovery_manifest,
        )
    if os.path.lexists(quarantine_root) and not _remove_empty_quarantine_root(
        quarantine_root
    ):
        return False, recovery_manifest
    try:
        recovery_manifest.unlink()
    except OSError:
        return False, recovery_manifest
    return not os.path.lexists(recovery_manifest), None

def _recover_stale_uninstall(
    project: Path,
    registry: dict[str, Any] | None,
) -> _UninstallReport | None:
    agents_root = project / ".agents"
    roots, durable_manifests, unsafe_recovery = _stale_recovery_candidates(project)
    registry_owned = (
        _registry_owned_files(project, registry) if registry is not None else None
    )
    remaining_owned = (
        [owned for owned, _candidate in registry_owned]
        if registry_owned is not None
        else _remaining_manifest_files(registry.get("kit_adapter"))
        if registry is not None
        else []
    )
    if unsafe_recovery:
        return _unsafe_recovery_report(
            project,
            remaining_owned=remaining_owned,
            unsafe_recovery=unsafe_recovery[0],
        )
    recovery_entries: list[tuple[dict[str, object], Path, list[tuple[dict[str, str], Path, Path]], Path]] = []
    remaining_durable = set(durable_manifests)
    for root in roots:
        selected = _select_recovery_journal(project, root)
        if selected is None:
            return _unsafe_recovery_report(
                project,
                remaining_owned=remaining_owned,
                unsafe_recovery=root,
            )
        loaded, recovery_manifest, _valid_manifests, invalid_manifests = selected
        recovery, quarantine_root, quarantined = loaded
        if invalid_manifests:
            return _recovery_report(
                project,
                removed=[],
                preserved_drift={
                    owned["path"]
                    for owned, _candidate, _quarantine_path in quarantined
                    if owned["state"] in {"missing", "drifted"}
                },
                remaining_owned=remaining_owned,
                recovery_manifest=recovery_manifest,
                recovery_owned=_recovery_owned_records(project, quarantined),
                unsafe_recovery=invalid_manifests[0],
            )
        durable_sibling = root.with_name(f"{root.name}.recovery.json")
        if durable_sibling in remaining_durable:
            sibling_loaded = _load_recovery_journal(project, durable_sibling)
            sibling_is_valid = (
                sibling_loaded is not None
                and sibling_loaded[1] == root
                and sibling_loaded[0]["transaction_id"] == recovery["transaction_id"]
            )
            sibling_header = (
                None
                if sibling_is_valid
                else _recovery_journal_header(
                    project,
                    root,
                    durable_sibling,
                )
            )
            sibling_is_historical = (
                sibling_header is not None
                and sibling_header[1] == recovery["transaction_id"]
                and sibling_header[0] < recovery["revision"]
            )
            if not sibling_is_valid and not sibling_is_historical:
                return _recovery_report(
                    project,
                    removed=[],
                    preserved_drift={
                        owned["path"]
                        for owned, _candidate, _quarantine_path in quarantined
                        if owned["state"] in {"missing", "drifted"}
                    },
                    remaining_owned=remaining_owned,
                    recovery_manifest=recovery_manifest,
                    recovery_owned=_recovery_owned_records(project, quarantined),
                    unsafe_recovery=durable_sibling,
                )
            remaining_durable.remove(durable_sibling)
        recovery_entries.append((recovery, quarantine_root, quarantined, recovery_manifest))
    for recovery_manifest in sorted(remaining_durable):
        loaded = _load_recovery_journal(project, recovery_manifest)
        if loaded is None:
            return _unsafe_recovery_report(
                project,
                remaining_owned=remaining_owned,
                unsafe_recovery=recovery_manifest,
            )
        recovery, quarantine_root, quarantined = loaded
        recovery_entries.append((recovery, quarantine_root, quarantined, recovery_manifest))
    for recovery, quarantine_root, quarantined, recovery_manifest in recovery_entries:
        recovery_files = recovery["files"]
        records_by_path = {record["path"]: record for record in recovery_files}
        removed_paths = {
            owned["path"]
            for owned, _candidate, _quarantine_path in quarantined
            if owned["state"] == "removed"
        }
        journal_changed = False
        for owned, _candidate, quarantine_path in quarantined:
            record = records_by_path[owned["path"]]
            state = owned["state"]
            quarantine_exists = os.path.lexists(quarantine_path)
            if state == "finalizing" and not quarantine_exists:
                owned["state"] = "removed"
                record["state"] = "removed"
                record["artifact_present"] = False
                removed_paths.add(owned["path"])
                journal_changed = True
            elif state == "verifying":
                if not quarantine_exists:
                    owned["state"] = "missing"
                    record["state"] = "missing"
                    record["artifact_present"] = False
                    record.pop("observed_sha256", None)
                else:
                    observed_sha256 = _regular_file_sha256(quarantine_path)
                    if observed_sha256 == owned["sha256"]:
                        owned["state"] = "moved"
                        record["state"] = "moved"
                        record["artifact_present"] = True
                        record.pop("observed_sha256", None)
                    else:
                        owned["state"] = "drifted"
                        record["state"] = "drifted"
                        record["artifact_present"] = True
                        if observed_sha256 is None:
                            record.pop("observed_sha256", None)
                        else:
                            record["observed_sha256"] = observed_sha256
                journal_changed = True
        manual_paths = {
            owned["path"]
            for owned, _candidate, _quarantine_path in quarantined
            if owned["state"] in {"missing", "drifted"}
        }
        active = [
            item
            for item in quarantined
            if item[0]["state"] not in {"removed", "missing", "drifted"}
        ]
        if journal_changed:
            try:
                recovery_manifest = _write_quarantine_recovery_manifest(recovery_manifest, recovery)
            except OSError:
                return _recovery_report(
                    project,
                    removed=sorted(removed_paths),
                    preserved_drift=manual_paths,
                    remaining_owned=remaining_owned,
                    recovery_manifest=recovery_manifest,
                    recovery_owned=_recovery_owned_records(project, quarantined),
                )
        if manual_paths:
            return _recovery_report(
                project,
                removed=sorted(removed_paths),
                preserved_drift=manual_paths,
                remaining_owned=remaining_owned,
                recovery_manifest=recovery_manifest,
                recovery_owned=_recovery_owned_records(project, quarantined),
            )
        if registry is not None and registry_owned is None:
            return _recovery_report(
                project,
                removed=sorted(removed_paths),
                preserved_drift=set(),
                remaining_owned=remaining_owned,
                recovery_manifest=recovery_manifest,
                recovery_owned=_recovery_owned_records(project, active),
            )
        if registry is None and active:
            return _recovery_report(
                project,
                removed=sorted(removed_paths),
                preserved_drift={owned["path"] for owned, _candidate, _path in active},
                remaining_owned=[],
                recovery_manifest=recovery_manifest,
                recovery_owned=_recovery_owned_records(project, active),
            )
        preserved_drift: set[str] = set()
        retained: list[tuple[dict[str, str], Path, Path]] = []
        if active:
            registry_hashes = {
                owned["path"]: owned["sha256"] for owned, _candidate in registry_owned
            }
            ownership_states = [
                registry_hashes.get(owned["path"]) == owned["sha256"]
                for owned, _candidate, _quarantine_path in active
            ]
            if not all(ownership_states) and any(ownership_states):
                return _recovery_report(
                    project,
                    removed=sorted(removed_paths),
                    preserved_drift={owned["path"] for owned, _candidate, _path in active},
                    remaining_owned=remaining_owned,
                    recovery_manifest=recovery_manifest,
                    recovery_owned=_recovery_owned_records(project, active),
                )
            if all(ownership_states):
                for owned, candidate, quarantine_path in active:
                    if not os.path.lexists(quarantine_path):
                        if not os.path.lexists(candidate):
                            preserved_drift.add(owned["path"])
                            retained.append((owned, candidate, quarantine_path))
                        continue
                    if not _quarantine_regular_file_matches(
                        quarantine_root,
                        quarantine_path,
                        owned["sha256"],
                        agents_root=agents_root,
                    ):
                        preserved_drift.add(owned["path"])
                        retained.append((owned, candidate, quarantine_path))
                        continue
                    if os.path.lexists(candidate):
                        preserved_drift.add(owned["path"])
                        retained.append((owned, candidate, quarantine_path))
                        continue
                    record = records_by_path[owned["path"]]
                    record["state"] = "source"
                    owned["state"] = "source"
                    try:
                        recovery_manifest = _write_quarantine_recovery_manifest(recovery_manifest, recovery)
                        os.link(quarantine_path, candidate, follow_symlinks=False)
                        os.unlink(quarantine_path)
                    except OSError:
                        preserved_drift.add(owned["path"])
                        retained.append((owned, candidate, quarantine_path))
            else:
                for owned, candidate, quarantine_path in active:
                    if not os.path.lexists(quarantine_path):
                        continue
                    if not _quarantine_regular_file_matches(
                        quarantine_root,
                        quarantine_path,
                        owned["sha256"],
                        agents_root=agents_root,
                    ):
                        preserved_drift.add(owned["path"])
                        retained.append((owned, candidate, quarantine_path))
                        continue
                    record = records_by_path[owned["path"]]
                    record["state"] = "finalizing"
                    owned["state"] = "finalizing"
                    try:
                        recovery_manifest = _write_quarantine_recovery_manifest(recovery_manifest, recovery)
                        quarantine_path.unlink()
                    except OSError:
                        preserved_drift.add(owned["path"])
                        retained.append((owned, candidate, quarantine_path))
                        continue
                    removed_paths.add(owned["path"])
                    record["state"] = "removed"
                    owned["state"] = "removed"
                    try:
                        recovery_manifest = _write_quarantine_recovery_manifest(recovery_manifest, recovery)
                    except OSError:
                        retained.append((owned, candidate, quarantine_path))
        if retained:
            return _recovery_report(
                project,
                removed=sorted(removed_paths),
                preserved_drift=preserved_drift,
                remaining_owned=remaining_owned,
                recovery_manifest=recovery_manifest,
                recovery_owned=_recovery_owned_records(project, retained),
            )
        cleaned, retained_manifest = _cleanup_stale_recovery(
            quarantine_root,
            recovery_manifest,
            recovery,
        )
        if not cleaned:
            return _recovery_report(
                project,
                removed=sorted(removed_paths),
                preserved_drift=preserved_drift,
                remaining_owned=remaining_owned,
                recovery_manifest=retained_manifest or recovery_manifest,
                recovery_owned=[],
            )
    return None

def uninstall_project_adapter(project: Path | str) -> dict[str, object]:
    project_path = Path(project).resolve()
    skill_root = _safe_project_path(
        project_path,
        ".agents/skills",
        required_prefix=(".agents", "skills"),
    )
    agent_root = _safe_project_path(
        project_path,
        ".codex/agents",
        required_prefix=(".codex", "agents"),
    )
    registry_path = _safe_project_path(
        project_path,
        ".agents/registry.json",
        required_prefix=(".agents",),
    )
    if not registry_path.exists():
        stale_recovery = _recover_stale_uninstall(project_path, None)
        if stale_recovery is not None:
            return stale_recovery
        return _UninstallReport({
            "status": "PASS",
            "removed": [],
            "preserved_drift": [],
            "remaining_owned": [],
        })

    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    if not isinstance(registry, dict):
        raise ValueError("project .agents/registry.json must be an object")
    stale_recovery = _recover_stale_uninstall(project_path, registry)
    if stale_recovery is not None:
        return stale_recovery
    if "kit_adapter" not in registry:
        return _UninstallReport({
            "status": "PASS",
            "removed": [],
            "preserved_drift": [],
            "remaining_owned": [],
        })
    adapter = registry["kit_adapter"]
    if not isinstance(adapter, dict):
        return _partial_uninstall_report(adapter)
    if adapter.get("adapter_id") not in {
        "GameStudio-CodexKIT/per-project/v1",
        "GameStudio-CodexKIT/per-project/v2",
    }:
        return _partial_uninstall_report(adapter)

    normalized_files = _normalized_owned_files(project_path, adapter)
    if normalized_files is None:
        return _partial_uninstall_report(adapter)

    removals: list[tuple[dict[str, str], Path]] = []
    remaining_owned: list[dict[str, str]] = []
    preserved_drift: set[str] = set()
    preserved_directories: set[Path] = set()
    for owned, candidate in normalized_files:
        try:
            info = candidate.lstat()
        except FileNotFoundError:
            continue
        if _is_reparse_point(candidate) or not stat.S_ISREG(info.st_mode):
            preserved_drift.add(owned["path"])
            remaining_owned.append(owned)
            if stat.S_ISDIR(info.st_mode):
                preserved_directories.add(candidate)
            continue
        if hashlib.sha256(candidate.read_bytes()).hexdigest() != owned["sha256"]:
            preserved_drift.add(owned["path"])
            remaining_owned.append(owned)
            continue
        removals.append((owned, candidate))

    cleanup_directories: set[Path] = set()
    for owned, candidate in removals:
        cleanup_root = _owned_cleanup_root(
            project_path,
            owned["path"],
            skill_root=skill_root,
            agent_root=agent_root,
        )
        directory = candidate.parent
        while directory != cleanup_root:
            cleanup_directories.add(directory)
            directory = directory.parent

    if removals:
        for owned, candidate in removals:
            if not _owned_regular_file_matches(candidate, owned["sha256"]):
                preserved_drift.add(owned["path"])
                return _transaction_failure_report(normalized_files, preserved_drift)

        transaction_id = uuid.uuid4().hex
        quarantine_root = project_path / ".agents" / (
            f".adapter-uninstall-quarantine-{transaction_id}"
        )
        quarantined = [
            (owned, candidate, quarantine_root / f"{index:08d}.owned")
            for index, (owned, candidate) in enumerate(removals)
        ]
        recovery_path = quarantine_root / "recovery.json"
        recovery = _quarantine_recovery_payload(
            project_path,
            adapter,
            transaction_id,
            quarantined,
        )
        try:
            quarantine_root.mkdir(parents=True, exist_ok=False)
            recovery_path = _write_quarantine_recovery_manifest(recovery_path, recovery)
            for index, (owned, candidate, quarantine_path) in enumerate(quarantined):
                if not _owned_regular_file_matches(candidate, owned["sha256"]):
                    preserved_drift.add(owned["path"])
                    raise RuntimeError("owned target changed before quarantine")
                candidate.replace(quarantine_path)
                if not _owned_regular_file_matches(quarantine_path, owned["sha256"]):
                    preserved_drift.add(owned["path"])
                    raise RuntimeError("quarantined target does not match ownership hash")
                recovery["files"][index]["state"] = "moved"
        except (OSError, RuntimeError):
            restored = _restore_quarantined(quarantined, preserved_drift)
            if restored:
                _refresh_restored_recovery_records(recovery, quarantined)
                _remove_quarantine_recovery(quarantine_root, recovery_path, recovery)
            retained_manifest = _existing_recovery_manifest(
                quarantine_root,
                recovery_path,
            )
            if retained_manifest is not None:
                return _recovery_report(
                    project_path,
                    removed=[],
                    preserved_drift=preserved_drift,
                    remaining_owned=[owned for owned, _candidate in normalized_files],
                    recovery_manifest=retained_manifest,
                    recovery_owned=_recovery_owned_records(project_path, quarantined),
                )
            return _transaction_failure_report(normalized_files, preserved_drift)
    else:
        quarantine_root = None
        quarantined = []
        recovery_path = None
        recovery = None

    updated_registry = json.loads(json.dumps(registry))
    updated_adapter = updated_registry["kit_adapter"]
    updated_registry["skills"] = sorted(
        directory.name
        for directory in skill_root.iterdir()
        if directory.is_dir() and (directory / "SKILL.md").exists()
    ) if skill_root.exists() else []
    if remaining_owned:
        updated_adapter["files"] = sorted(remaining_owned, key=lambda item: item["path"])
    else:
        updated_registry.pop("kit_adapter", None)
    try:
        _write_registry_atomically(registry_path, updated_registry)
    except OSError:
        restored = _restore_quarantined(quarantined, preserved_drift)
        if restored:
            _refresh_restored_recovery_records(recovery, quarantined)
            _remove_quarantine_recovery(quarantine_root, recovery_path, recovery)
        retained_manifest = _existing_recovery_manifest(
            quarantine_root,
            recovery_path,
        )
        if retained_manifest is not None:
            return _recovery_report(
                project_path,
                removed=[],
                preserved_drift=preserved_drift,
                remaining_owned=[owned for owned, _candidate in normalized_files],
                recovery_manifest=retained_manifest,
                recovery_owned=_recovery_owned_records(project_path, quarantined),
            )
        return _transaction_failure_report(normalized_files, preserved_drift)

    removed, files_clean = _finalize_quarantined(
        quarantined,
        preserved_drift,
        recovery,
        recovery_path,
    )
    quarantine_clean = files_clean and _remove_quarantine_recovery(
        quarantine_root,
        recovery_path,
        recovery,
    )
    if not quarantine_clean:
        retained_manifest = _existing_recovery_manifest(
            quarantine_root,
            recovery_path,
        )
        if retained_manifest is None:
            retained_manifest = recovery_path
        if retained_manifest is None:
            raise RuntimeError("quarantine cleanup failed without recovery manifest")
        return _recovery_report(
            project_path,
            removed=removed,
            preserved_drift=preserved_drift,
            remaining_owned=remaining_owned,
            recovery_manifest=retained_manifest,
            recovery_owned=_recovery_owned_records(project_path, quarantined),
        )

    for directory in sorted(
        cleanup_directories,
        key=lambda path: len(path.parts),
        reverse=True,
    ):
        if any(
            directory == preserved or directory.is_relative_to(preserved)
            for preserved in preserved_directories
        ):
            continue
        try:
            if directory.is_dir() and not any(directory.iterdir()):
                directory.rmdir()
        except OSError:
            pass

    removed = sorted(removed)
    return _UninstallReport({
        "status": "PARTIAL" if remaining_owned else "PASS",
        "removed": removed,
        "preserved_drift": sorted(preserved_drift),
        "remaining_owned": sorted(remaining_owned, key=lambda item: item["path"]),
    })
def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Hermes, Codex, or project-local adapters.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--target", required=True, choices=["hermes", "codex", "per-project"])
    parser.add_argument("--output", required=True)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--apply", action="store_true")
    action.add_argument("--uninstall", action="store_true")
    parser.add_argument("--reviewer")
    parser.add_argument("--backup-root")
    parser.add_argument("--plan-digest")
    args = parser.parse_args(argv)
    if args.uninstall:
        if args.target != "per-project":
            parser.error("--uninstall is only supported for per-project adapters")
        if args.reviewer or args.backup_root or args.plan_digest:
            parser.error("--reviewer, --backup-root, and --plan-digest cannot be used with --uninstall")
        print(json.dumps(uninstall_project_adapter(Path(args.output)), indent=2))
        return 0
    if args.apply:
        if args.target != "per-project":
            parser.error("--apply is only supported for per-project adapters")
        if not args.reviewer or not args.reviewer.strip():
            parser.error("--reviewer is required with --apply")
        if not args.backup_root:
            parser.error("--backup-root is required with --apply")
        if not args.plan_digest or not args.plan_digest.strip():
            parser.error("--plan-digest is required with --apply")
        result = apply_project_adapter(
            Path(args.root),
            Path(args.output),
            reviewer=args.reviewer,
            backup_root=Path(args.backup_root),
            approved_plan_digest=args.plan_digest,
        )
    else:
        if args.reviewer or args.backup_root or args.plan_digest:
            parser.error("--reviewer, --backup-root, and --plan-digest require --apply")
        result = generate_adapter(Path(args.root), args.target, Path(args.output))
    print(json.dumps(result, indent=2))
    return 0

if __name__ == "__main__":
    sys.exit(main())
