from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import stat
import sys
from pathlib import Path, PurePosixPath
from typing import Any

try:
    from scripts.common import load_yaml
except ModuleNotFoundError:
    from common import load_yaml


MARKER = "Generated by scripts/generate_adapters.py. Do not edit manually."


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _is_reparse_point(path: Path) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    attributes = getattr(info, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return path.is_symlink() or bool(attributes & reparse_flag)


def _safe_project_path(
    project: Path,
    relative: str,
    *,
    required_prefix: tuple[str, ...],
) -> Path:
    normalized = relative.replace("\\", "/")
    pure = PurePosixPath(normalized)
    parts = pure.parts
    if pure.is_absolute() or not parts or ".." in parts or "." in parts:
        raise ValueError(f"unsafe project adapter path: {relative}")
    if parts[: len(required_prefix)] != required_prefix:
        raise ValueError(f"project adapter path is outside its owned scope: {relative}")

    project_root = project.resolve()
    candidate = project_root.joinpath(*parts)
    current = project_root
    if _is_reparse_point(current):
        raise ValueError(f"project root is a symlink or reparse point: {current}")
    for part in parts:
        current = current / part
        if current.exists() and _is_reparse_point(current):
            raise ValueError(f"symlink or reparse point is not allowed: {current}")

    owned_root = project_root.joinpath(*required_prefix).resolve()
    resolved = candidate.resolve()
    try:
        resolved.relative_to(owned_root)
    except ValueError as error:
        raise ValueError(f"project adapter path escapes its owned scope: {relative}") from error
    return candidate


def _generated_skill(text: str) -> str:
    if text.startswith("---\n"):
        return text.replace("---\n", f"---\n# {MARKER}\n", 1)
    return f"<!-- {MARKER} -->\n{text}"


def _generated_resource(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    if source.name == "SKILL.md":
        return _generated_skill(text)
    if source.suffix.casefold() in {".py", ".sh", ".ps1", ".yaml", ".yml", ".toml"}:
        return f"# {MARKER}\n\n{text}"
    if source.suffix.casefold() in {".md", ".txt"}:
        return f"<!-- {MARKER} -->\n{text}"
    raise ValueError(f"unsupported skill resource type: {source}")


def _skill_files(skill_file: Path) -> list[Path]:
    return sorted(path for path in skill_file.parent.rglob("*") if path.is_file())


def _capabilities(root: Path) -> list[dict[str, Any]]:
    registry = load_yaml(root / "registry" / "capabilities.yaml")
    return registry.get("capabilities", [])


def _prepare_managed_output(output: Path) -> None:
    if not output.exists():
        return
    for file in (item for item in output.rglob("*") if item.is_file()):
        if MARKER not in file.read_text(encoding="utf-8", errors="replace"):
            raise RuntimeError(f"refusing to replace unmanaged adapter file: {file}")
    shutil.rmtree(output)


def _write_standard_adapter(root: Path, target: str, output: Path) -> dict[str, object]:
    _prepare_managed_output(output)
    created: list[str] = []
    capabilities = _capabilities(root)
    for capability in capabilities:
        skill_file = root / capability["path"]
        for source in _skill_files(skill_file):
            relative_resource = source.relative_to(skill_file.parent)
            destination = output / "skills" / capability["id"] / relative_resource
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(_generated_resource(source), encoding="utf-8", newline="\n")
            created.append(destination.relative_to(output).as_posix())
    registry = {
        "_generated": MARKER,
        "schema_version": 1,
        "target": target,
        "skills": [capability["id"] for capability in capabilities],
    }
    (output / "registry.json").write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
    created.append("registry.json")
    return {"target": target, "created": sorted(created), "preserved": []}


def _read_project_registry(project: Path) -> dict[str, Any]:
    path = _safe_project_path(
        project,
        ".agents/registry.json",
        required_prefix=(".agents",),
    )
    if not path.exists():
        return {"schema_version": 1, "skills": []}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("project .agents/registry.json must be an object")
    return data


def _write_project_adapter(root: Path, project: Path) -> dict[str, object]:
    capabilities = _capabilities(root)
    created: list[str] = []
    preserved: list[str] = []
    owned_files: list[dict[str, str]] = []
    skill_root = _safe_project_path(
        project,
        ".agents/skills",
        required_prefix=(".agents", "skills"),
    )
    for capability in capabilities:
        skill_file = root / capability["path"]
        destination_skill = skill_root / capability["id"] / "SKILL.md"
        existing_skill = (
            destination_skill.read_text(encoding="utf-8", errors="replace")
            if destination_skill.exists()
            else ""
        )
        if destination_skill.exists() and MARKER not in existing_skill:
            preserved.append(destination_skill.relative_to(project).as_posix())
            continue
        for source in _skill_files(skill_file):
            relative_resource = source.relative_to(skill_file.parent)
            relative = PurePosixPath(
                ".agents",
                "skills",
                str(capability["id"]),
                *relative_resource.parts,
            ).as_posix()
            destination = _safe_project_path(
                project,
                relative,
                required_prefix=(".agents", "skills", str(capability["id"])),
            )
            existing_text = (
                destination.read_text(encoding="utf-8", errors="replace")
                if destination.exists()
                else ""
            )
            if destination.exists() and MARKER not in existing_text:
                preserved.append(destination.relative_to(project).as_posix())
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            generated_text = _generated_resource(source)
            destination.write_text(generated_text, encoding="utf-8", newline="\n")
            created.append(relative)
            owned_files.append({"path": relative, "sha256": _sha256_text(generated_text)})
    local_skill_names = sorted(
        directory.name
        for directory in skill_root.iterdir()
        if directory.is_dir() and (directory / "SKILL.md").exists()
    ) if skill_root.exists() else []
    registry = _read_project_registry(project)
    registry["schema_version"] = registry.get("schema_version", 1)
    registry["skills"] = local_skill_names
    registry["kit_adapter"] = {
        "_generated": MARKER,
        "adapter_id": "GameStudio-CodexKIT/per-project/v1",
        "source": "GameStudio-CodexKIT",
        "target": "per-project",
        "files": sorted(owned_files, key=lambda item: item["path"]),
    }
    registry_path = _safe_project_path(
        project,
        ".agents/registry.json",
        required_prefix=(".agents",),
    )
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
    created.append(registry_path.relative_to(project).as_posix())
    return {"target": "per-project", "created": sorted(created), "preserved": sorted(preserved)}


def generate_adapter(root: Path | str, target: str, output: Path | str) -> dict[str, object]:
    root_path = Path(root).resolve()
    output_path = Path(output).resolve()
    if target in {"hermes", "codex"}:
        return _write_standard_adapter(root_path, target, output_path)
    if target == "per-project":
        return _write_project_adapter(root_path, output_path)
    raise ValueError(f"unsupported adapter target: {target}")


def uninstall_project_adapter(project: Path | str) -> list[str]:
    project_path = Path(project).resolve()
    skill_root = _safe_project_path(
        project_path,
        ".agents/skills",
        required_prefix=(".agents", "skills"),
    )
    removed: list[str] = []
    registry_path = _safe_project_path(
        project_path,
        ".agents/registry.json",
        required_prefix=(".agents",),
    )
    if registry_path.exists():
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
        adapter = registry.get("kit_adapter", {})
        remaining_owned: list[dict[str, str]] = []
        if adapter.get("adapter_id") == "GameStudio-CodexKIT/per-project/v1":
            owned_by_skill: dict[str, list[dict[str, str]]] = {}
            for owned in adapter.get("files", []):
                relative = str(owned.get("path", ""))
                pure = PurePosixPath(relative.replace("\\", "/"))
                parts = pure.parts
                if (
                    pure.is_absolute()
                    or ".." in parts
                    or "." in parts
                    or len(parts) < 4
                    or parts[:2] != (".agents", "skills")
                ):
                    remaining_owned.append(owned)
                    continue
                owned_by_skill.setdefault(parts[2], []).append(owned)

            for skill_name, skill_files in sorted(owned_by_skill.items()):
                resolved: list[tuple[dict[str, str], Path]] = []
                drifted = False
                for owned in skill_files:
                    relative = str(owned.get("path", ""))
                    try:
                        candidate = _safe_project_path(
                            project_path,
                            relative,
                            required_prefix=(".agents", "skills", skill_name),
                        )
                    except ValueError:
                        drifted = True
                        break
                    resolved.append((owned, candidate))
                    if candidate.is_file() and hashlib.sha256(candidate.read_bytes()).hexdigest() != owned.get("sha256"):
                        drifted = True
                        break
                if drifted:
                    remaining_owned.extend(skill_files)
                    continue

                for _owned, candidate in sorted(
                    resolved,
                    key=lambda item: len(item[1].parts),
                    reverse=True,
                ):
                    if candidate.is_file():
                        candidate.unlink()
                skill_directory = skill_root / skill_name
                for directory in sorted(
                    (path for path in skill_directory.rglob("*") if path.is_dir()),
                    key=lambda path: len(path.parts),
                    reverse=True,
                ) if skill_directory.exists() else []:
                    if not any(directory.iterdir()):
                        directory.rmdir()
                if skill_directory.exists() and not any(skill_directory.iterdir()):
                    skill_directory.rmdir()
                removed.append(skill_name)
        registry["skills"] = sorted(
            directory.name
            for directory in skill_root.iterdir()
            if directory.is_dir() and (directory / "SKILL.md").exists()
        ) if skill_root.exists() else []
        if remaining_owned:
            adapter["files"] = remaining_owned
            registry["kit_adapter"] = adapter
        else:
            registry.pop("kit_adapter", None)
        registry_path.write_text(json.dumps(registry, indent=2) + "\n", encoding="utf-8")
    return sorted(set(removed))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Hermes, Codex, or project-local adapters.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--target", required=True, choices=["hermes", "codex", "per-project"])
    parser.add_argument("--output", required=True)
    parser.add_argument("--uninstall", action="store_true")
    args = parser.parse_args(argv)
    if args.uninstall:
        if args.target != "per-project":
            parser.error("--uninstall is only supported for per-project adapters")
        print(json.dumps({"removed": uninstall_project_adapter(Path(args.output))}, indent=2))
        return 0
    print(json.dumps(generate_adapter(Path(args.root), args.target, Path(args.output)), indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
