from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

try:
    from scripts.safe_mutation import apply_mutation, report_mutation
except ModuleNotFoundError:
    from safe_mutation import apply_mutation, report_mutation


GENERATED_HEADER = "Generated by scripts/project_scaffold.py. Do not edit manually."


def _files(root: Path) -> Iterable[Path]:
    for path in root.rglob("*"):
        if ".git" in path.parts or ".agents" in path.parts:
            continue
        if path.is_file():
            yield path


def detect_subsystems(root: Path | str) -> set[str]:
    root_path = Path(root).resolve()
    subsystems: set[str] = set()
    for assets in root_path.rglob("Assets"):
        if assets.is_dir() and (assets.parent / "ProjectSettings").is_dir():
            subsystems.add("unity")
            break
    for path in _files(root_path):
        suffix = path.suffix.casefold()
        if suffix in {".csproj", ".sln", ".vcxproj"} or path.name == "CMakeLists.txt":
            subsystems.add("server")
        if suffix == ".lua":
            subsystems.add("lua")
        if suffix == ".sql" or "database" in {part.casefold() for part in path.parts}:
            subsystems.add("database")
    return subsystems


def _agent_entries(subsystems: list[str]) -> list[dict[str, str]]:
    entries = [{"id": "orchestrator", "scope": "shared governance and integration"}]
    entries.extend({"id": subsystem, "scope": f"{subsystem} subsystem"} for subsystem in subsystems)
    return entries


def scaffold_files(root: Path | str) -> dict[Path, str]:
    root_path = Path(root).resolve()
    subsystems = sorted(detect_subsystems(root_path))
    subsystem_text = ", ".join(subsystems) if subsystems else "unclassified"
    skill_root = root_path / ".agents" / "skills"
    local_skills = sorted(
        directory.name
        for directory in skill_root.iterdir()
        if directory.is_dir() and (directory / "SKILL.md").is_file()
    ) if skill_root.exists() else []
    agents = f"""<!-- {GENERATED_HEADER} -->
# Project Agent Contract

- Detected subsystems: {subsystem_text}.
- Read-only inspection is the default.
- One writer owns each file or generated output.
- Preserve external, vendor, binary, generated, and credential paths.
- Use Verified, Snapshot, Unverified, and BLOCKED evidence labels.
- Do not commit, publish, start services, import databases, or perform destructive cleanup without explicit approval.
"""
    contract = f"""<!-- {GENERATED_HEADER} -->
# Agent Ownership Contract

The orchestrator owns shared governance and final verification. Subsystem agents own only exact declared paths. Reviewers are read-only. Generated files are changed through their source. External projects remain read-only unless separately authorized.
"""
    handoff = f"""<!-- {GENERATED_HEADER} -->
# HANDOFF

## Goal
Unverified.

## Scope Ownership and Do-Not-Touch
- Snapshot: detected subsystems are {subsystem_text}.

## Files Touched
None.

## Commands and Tests
None.

## Verified
None.

## Snapshot
Initial scaffold only.

## Unverified
Runtime topology, versions, ports, schemas, and owners require project intake.

## BLOCKED
Live verification has not run.

## Next Actions
1. Run project intake.
2. Verify subsystem owners.
3. Replace snapshot assumptions with commands.

## Reactivation Prompt
Inspect this repository read-only, verify the scaffold snapshot, and create a bounded task packet.
"""
    registry = {
        "_generated": GENERATED_HEADER,
        "schema_version": 1,
        "subsystems": subsystems,
        "agents": _agent_entries(subsystems),
        "skills": local_skills,
    }
    return {
        root_path / "AGENTS.md": agents,
        root_path / "HANDOFF.md": handoff,
        root_path / ".agents" / "CONTRACT.md": contract,
        root_path / ".agents" / "registry.json": json.dumps(registry, indent=2) + "\n",
    }


def _scaffold_operations(root: Path) -> tuple[list[dict[str, str]], list[str]]:
    operations: list[dict[str, str]] = []
    preserved: list[str] = []
    for path, content in scaffold_files(root).items():
        relative = path.relative_to(root).as_posix()
        if path.exists():
            preserved.append(relative)
            continue
        operations.append({"path": relative, "content": content})
    return operations, sorted(preserved)


def scaffold_project(root: Path | str) -> dict[str, object]:
    root_path = Path(root).resolve()
    operations, preserved = _scaffold_operations(root_path)
    report = report_mutation(root_path, operations)
    return {
        "status": "REPORT_ONLY",
        "root": str(root_path),
        "proposed": sorted(operation["path"] for operation in operations),
        "preserved": preserved,
        "subsystems": sorted(detect_subsystems(root_path)),
        "mutation_report": report,
    }


def apply_scaffold(
    root: Path | str,
    *,
    reviewer: str,
    backup_root: Path | str,
) -> dict[str, object]:
    if not reviewer.strip():
        raise ValueError("reviewer is required for scaffold apply")
    root_path = Path(root).resolve()
    operations, preserved = _scaffold_operations(root_path)
    manifest_path = apply_mutation(root_path, operations, backup_root)
    restore_script = Path(__file__).resolve().with_name("safe_mutation.py")
    return {
        "status": "PASS",
        "root": str(root_path),
        "created": sorted(operation["path"] for operation in operations),
        "preserved": preserved,
        "subsystems": sorted(detect_subsystems(root_path)),
        "reviewer": reviewer,
        "manifest": str(manifest_path),
        "restore_argv": [
            sys.executable,
            str(restore_script),
            "--mode",
            "restore",
            "--root",
            str(root_path),
            "--manifest",
            str(manifest_path),
        ],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Bootstrap project-local game studio governance.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--reviewer")
    parser.add_argument("--backup-root")
    args = parser.parse_args(argv)
    if args.apply:
        if not args.reviewer or not args.backup_root:
            parser.error("--apply requires --reviewer and --backup-root")
        report = apply_scaffold(
            Path(args.root),
            reviewer=args.reviewer,
            backup_root=Path(args.backup_root),
        )
    else:
        report = scaffold_project(Path(args.root))
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
