from __future__ import annotations

import argparse
import re
import stat
import sys
import unicodedata
from dataclasses import dataclass
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any

try:
    from scripts.common import load_yaml
except ModuleNotFoundError:
    from common import load_yaml

GENERATION_NOTICE = "Generated by scripts/sync_skill_resources.py. Do not edit manually."
HASH_GENERATED_MARKER = f"# {GENERATION_NOTICE}"
HTML_GENERATED_MARKER = f"<!-- {GENERATION_NOTICE} -->"
HASH_GENERATED_HEADER = f"{HASH_GENERATED_MARKER}\n\n"
HTML_GENERATED_HEADER = f"{HTML_GENERATED_MARKER}\n\n"
GENERATED_HEADER = HASH_GENERATED_HEADER
GENERATED_MARKERS_BY_SUFFIX = {
    ".py": HASH_GENERATED_MARKER,
    ".toml": HASH_GENERATED_MARKER,
    ".yaml": HASH_GENERATED_MARKER,
    ".yml": HASH_GENERATED_MARKER,
    ".ps1": HASH_GENERATED_MARKER,
    ".sh": HASH_GENERATED_MARKER,
    ".md": HTML_GENERATED_MARKER,
    ".txt": HTML_GENERATED_MARKER,
}
SUPPORTED_SUFFIXES = frozenset(GENERATED_MARKERS_BY_SUFFIX)
SKILL_ID = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
FORBIDDEN_COMPONENT_CHARACTERS = set('<>:"|?*')
RESERVED_DEVICE_BASENAMES = {
    "aux",
    "clock$",
    "con",
    "conin$",
    "conout$",
    "nul",
    "prn",
}
RESERVED_NUMBERED_DEVICE = re.compile(r"^(?:com|lpt)(?:[1-9¹²³])$", re.IGNORECASE)


@dataclass(frozen=True)
class SkillResource:
    skill_id: str
    source: Path
    destination: Path


def _is_reparse_point(path: Path) -> bool:
    try:
        info = path.lstat()
    except FileNotFoundError:
        return False
    attributes = getattr(info, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return path.is_symlink() or bool(attributes & reparse_flag)

def _validate_portable_component(part: str, *, label: str, value: str) -> None:
    device_basename = part.split(".", 1)[0].rstrip(" .").casefold()
    if (
        any(unicodedata.category(character) == "Cc" for character in part)
        or any(character in FORBIDDEN_COMPONENT_CHARACTERS for character in part)
        or part.endswith((".", " "))
        or device_basename in RESERVED_DEVICE_BASENAMES
        or RESERVED_NUMBERED_DEVICE.fullmatch(device_basename)
    ):
        raise ValueError(f"unsafe {label} component {part!r}: {value}")


def _relative_parts(value: Any, *, label: str) -> tuple[str, ...]:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{label} must be a non-empty relative path")
    normalized = value.replace("\\", "/")
    raw_parts = normalized.split("/")
    posix = PurePosixPath(normalized)
    windows = PureWindowsPath(value)
    if (
        posix.is_absolute()
        or windows.is_absolute()
        or windows.drive
        or any(part in {"", ".", ".."} for part in raw_parts)
    ):
        raise ValueError(f"unsafe {label}: {value}")
    for part in raw_parts:
        _validate_portable_component(part, label=label, value=value)
    return tuple(raw_parts)


def _safe_path(
    base: Path,
    parts: tuple[str, ...],
    *,
    label: str,
    owning_root: Path | None = None,
) -> Path:
    base_path = base.resolve()
    if _is_reparse_point(base_path):
        raise ValueError(f"{label} root is a symlink or reparse point: {base_path}")
    candidate = base_path.joinpath(*parts)
    current = base_path
    for part in parts:
        current = current / part
        if _is_reparse_point(current):
            raise ValueError(f"symlink or reparse point is not allowed: {current}")
    resolved = candidate.resolve()
    try:
        resolved.relative_to(base_path)
    except ValueError as error:
        raise ValueError(f"{label} escapes its owned scope: {'/'.join(parts)}") from error
    if owning_root is not None:
        resolved_owner = owning_root.resolve()
        try:
            resolved_owner.relative_to(base_path)
            resolved.relative_to(resolved_owner)
        except ValueError as error:
            raise ValueError(f"{label} escapes its owning skill root: {'/'.join(parts)}") from error
    return candidate


def _normalize_resource(root: Path, skill_id: str, entry: Any) -> SkillResource:
    if isinstance(entry, str):
        source_value = f"scripts/{entry}"
        destination_value = f"scripts/{entry}"
    elif isinstance(entry, dict) and set(entry) == {"source", "destination"}:
        source_value = entry["source"]
        destination_value = entry["destination"]
    else:
        raise ValueError(
            f"resource for {skill_id} must be a script name or a source/destination mapping"
        )

    source_parts = _relative_parts(source_value, label=f"source path for {skill_id}")
    destination_parts = _relative_parts(
        destination_value, label=f"destination path for {skill_id}"
    )
    source = _safe_path(root, source_parts, label="repository resource path")
    skill_root = root / "skills" / skill_id
    destination = _safe_path(
        root,
        ("skills", skill_id, *destination_parts),
        label=f"resource destination for {skill_id}",
        owning_root=skill_root,
    )
    try:
        destination.relative_to(skill_root)
    except ValueError as error:
        raise ValueError(
            f"resource destination escapes skills/{skill_id}: {destination_value}"
        ) from error
    source_suffix = source.suffix.casefold()
    destination_suffix = destination.suffix.casefold()
    if source_suffix not in SUPPORTED_SUFFIXES or destination_suffix not in SUPPORTED_SUFFIXES:
        raise ValueError(f"unsupported resource suffix for {skill_id}: {source_value} -> {destination_value}")
    if source_suffix != destination_suffix:
        raise ValueError(f"resource suffix mismatch for {skill_id}: {source_value} -> {destination_value}")
    if not source.is_file():
        raise ValueError(f"missing source resource for {skill_id}: {source_value}")
    return SkillResource(skill_id=skill_id, source=source, destination=destination)

def generated_marker(path: Path) -> str:
    try:
        return GENERATED_MARKERS_BY_SUFFIX[path.suffix.casefold()]
    except KeyError as error:
        raise ValueError(f"unsupported resource suffix: {path}") from error


def generated_header(path: Path) -> str:
    return f"{generated_marker(path)}\n\n"


def _read_resource_text(path: Path) -> str:
    try:
        content = path.read_text(encoding="utf-8")
    except UnicodeError as error:
        raise ValueError(f"binary or non-UTF-8 resource: {path}") from error
    if "\x00" in content:
        raise ValueError(f"binary or non-UTF-8 resource: {path}")
    return content


def _is_owned_generated_resource(path: Path, content: str) -> bool:
    try:
        marker = generated_marker(path)
    except ValueError:
        return False
    first_line = content.split("\n", 1)[0]
    return first_line == marker


def _recheck_destination(root: Path, resource: SkillResource) -> None:
    relative = resource.destination.relative_to(root)
    _safe_path(
        root,
        relative.parts,
        label=f"resource destination for {resource.skill_id}",
        owning_root=root / "skills" / resource.skill_id,
    )


def load_skill_resources(root: Path | str) -> tuple[list[SkillResource], list[SkillResource]]:
    root_path = Path(root).resolve()
    registry_path = root_path / "registry" / "skill-resources.yaml"
    registry = load_yaml(registry_path)
    if not isinstance(registry, dict) or set(registry) != {
        "schema_version",
        "bundled",
        "repository_only",
    }:
        raise ValueError("skill resource registry has an invalid top-level schema")
    if registry.get("schema_version") != 2:
        raise ValueError("skill resource registry schema_version must be 2")

    normalized_sections: list[list[SkillResource]] = []
    destinations: set[Path] = set()
    for section in ("bundled", "repository_only"):
        mapping = registry.get(section)
        if not isinstance(mapping, dict):
            raise ValueError(f"skill resource registry {section} section must be a mapping")
        normalized: list[SkillResource] = []
        for skill_id, entries in sorted(mapping.items(), key=lambda item: str(item[0])):
            if not isinstance(skill_id, str) or not SKILL_ID.fullmatch(skill_id):
                raise ValueError(f"invalid skill id in {section} resource registry: {skill_id}")
            if not (root_path / "skills" / skill_id / "SKILL.md").is_file():
                raise ValueError(f"unknown skill in {section} resource registry: {skill_id}")
            if not isinstance(entries, list) or not entries:
                raise ValueError(f"{section} resources for {skill_id} must be a non-empty list")
            for entry in entries:
                resource = _normalize_resource(root_path, skill_id, entry)
                if resource.destination in destinations:
                    raise ValueError(
                        f"duplicate resource destination for {skill_id}: "
                        f"{resource.destination.relative_to(root_path).as_posix()}"
                    )
                destinations.add(resource.destination)
                normalized.append(resource)
        normalized_sections.append(sorted(normalized, key=lambda item: str(item.destination)))
    return normalized_sections[0], normalized_sections[1]


def sync_skill_resources(root: Path | str, *, check: bool = False) -> list[Path]:
    root_path = Path(root).resolve()
    bundled, _repository_only = load_skill_resources(root_path)
    expected_paths = {resource.destination for resource in bundled}
    drift: list[Path] = []

    for resource in bundled:
        expected = generated_header(resource.destination) + _read_resource_text(resource.source)
        observed = (
            _read_resource_text(resource.destination)
            if resource.destination.is_file()
            else None
        )
        if observed == expected:
            continue
        drift.append(resource.destination)
        if not check:
            resource.destination.parent.mkdir(parents=True, exist_ok=True)
            _recheck_destination(root_path, resource)
            resource.destination.write_text(expected, encoding="utf-8")

    skill_root = root_path / "skills"
    for generated in sorted(path for path in skill_root.rglob("*") if path.is_file()):
        if generated in expected_paths:
            continue
        try:
            body = _read_resource_text(generated)
        except ValueError:
            continue
        if not _is_owned_generated_resource(generated, body):
            continue
        relative = generated.relative_to(root_path)
        owner = root_path / "skills" / relative.parts[1]
        _safe_path(
            root_path,
            relative.parts,
            label="generated resource path",
            owning_root=owner,
        )
        drift.append(generated)
        if not check:
            _safe_path(
                root_path,
                relative.parts,
                label="generated resource path",
                owning_root=owner,
            )
            generated.unlink()

    return sorted(set(drift))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Synchronize standalone resources into canonical skill folders."
    )
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--check", action="store_true", help="report drift without writing files")
    args = parser.parse_args(argv)

    try:
        drift = sync_skill_resources(args.root, check=args.check)
    except (OSError, ValueError) as error:
        print(f"skill-resources: ERROR: {error}")
        return 1

    root = Path(args.root).resolve()
    for path in drift:
        print(path.relative_to(root).as_posix())
    if args.check and drift:
        print(f"skill-resources: {len(drift)} generated file(s) out of sync")
        return 1
    action = "synced" if drift else "already in sync"
    print(f"skill-resources: {len(drift)} generated file(s) {action}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
