# Generated by scripts/sync_skill_resources.py. Do not edit manually.

from __future__ import annotations

from copy import deepcopy
from typing import Any


def plan_save_migration(
    save: dict[str, Any], target_version: int, migrations: list[dict[str, Any]]
) -> dict[str, Any]:
    source = deepcopy(save)
    current_version = source.get("schema_version")
    if not isinstance(current_version, int) or current_version > target_version:
        return {
            "verdict": "BLOCKED",
            "reasons": ["unknown or newer save schema version"],
            "rollback": source,
        }
    migration_by_version = {
        migration.get("from_version"): migration
        for migration in migrations
        if isinstance(migration.get("from_version"), int)
    }
    migrated = deepcopy(source)
    applied: list[dict[str, int]] = []
    while migrated["schema_version"] < target_version:
        migration = migration_by_version.get(migrated["schema_version"])
        if not migration or migration.get("to_version") != migrated["schema_version"] + 1:
            return {
                "verdict": "BLOCKED",
                "reasons": [f"no recognized migration from version {migrated['schema_version']}"],
                "rollback": source,
            }
        data = migrated.get("data")
        if not isinstance(data, dict):
            return {
                "verdict": "BLOCKED",
                "reasons": ["save data must be an object"],
                "rollback": source,
            }
        for old_name, new_name in migration.get("rename", {}).items():
            if old_name in data:
                data[new_name] = data.pop(old_name)
        for name, value in migration.get("defaults", {}).items():
            data.setdefault(name, deepcopy(value))
        for name in migration.get("remove", []):
            data.pop(name, None)
        previous = migrated["schema_version"]
        migrated["schema_version"] = migration["to_version"]
        applied.append({"from_version": previous, "to_version": migrated["schema_version"]})
    return {
        "verdict": "PASS",
        "migrated": migrated,
        "rollback": source,
        "applied": applied,
        "limitations": ["Fixture migration only; no live player save was modified."],
    }
